SELECT
  A.ID_UNIDADE_ORG,
  A.ID_UNID_ORG_TRAMITE,
  B.TX_UNIDADE_ESTOQUE,
  C.NB_COD_UNIDADE,
  C.ORGAO
FROM
  UNID_TRAMITE_ESTOQUE A,
  UNIDADE_ESTOQUE B,
  V_UNIDADE_ORG_ATIVO C
WHERE
  A.ID_UNIDADE_ORG        = B.ID_UNIDADE_ORG
AND A.ID_UNID_ORG_TRAMITE = C.ID_UNIDADE_ORG
and B.ID_UNIDADE_ORG = 83
ORDER BY
A.ID_UNIDADE_ORG,
  C.ORGAO