SELECT
  A.ID_UNIDADE_ORG,
  A.TX_UNIDADE_ESTOQUE,
  B.CS_TIPO_RESPONSAVEL,
  C.ID_UNIDADE_GESTORA,
  C.ID_PESSOA_FUNCIONARIO,
  D.ID_USUARIO,
  D.TX_LOGIN
FROM
  UNIDADE_ESTOQUE A,
  UNID_EST_RESPONSAVEL_2 B,
  FUNCIONARIO_2 C,
  USUARIO D
WHERE
  D.ID_PESSOA_FUNCIONARIO   = C.ID_PESSOA_FUNCIONARIO
AND D.ID_UNIDADE_GESTORA    = C.ID_UNIDADE_GESTORA
AND C.ID_PESSOA_FUNCIONARIO = B.ID_PESSOA_FUNCIONARIO
AND C.ID_UNIDADE_GESTORA    = B.ID_UNIDADE_GESTORA
AND B.ID_UNIDADE_ORG        = A.ID_UNIDADE_ORG
AND D.TX_LOGIN = USER
AND A.TX_UNIDADE_ESTOQUE LIKE UPPER('%semas%')
ORDER BY
  A.TX_UNIDADE_ESTOQUE