SELECT
  ID_UNIDADE_ORG CODIGO,
  ORGAO TX_ORGAO,
  NB_COD_UNIDADE,
  NB_COD_UNIDADE
  ||'-'
  ||ORGAO AS ORGAO
FROM
  V_UNIDADE_ORG_ATIVO V_unidade_org
GROUP BY
  ID_UNIDADE_ORG,
  ORGAO,
  NB_COD_UNIDADE,
  NB_COD_UNIDADE
  ||'-'
  ||ORGAO
ORDER BY
  TX_ORGAO ASC,
  NB_COD_UNIDADE DESC