SELECT
  A.ID_UNIDADE_ORG,
  B.NB_CODIGO_UNIDADE,
  B.TX_SIGLA_UNIDADE
  || ' - '
  || A.TX_UNIDADE_ORG,
  B.CS_TIPO_UNID_ORG,
  B.CS_ATIVA
FROM
  V_UNIDADE_ORG_A A,
  UNIDADE_ORG B
WHERE
  B.NB_CODIGO_UNIDADE = A.COD_UNIDADE