--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Março-21-2014   
--------------------------------------------------------
DROP TABLE "SEMAD"."CONTRATO_CP" cascade constraints;
DROP TABLE "SEMAD"."FUNCIONARIO_2" cascade constraints;
DROP TABLE "SEMAD"."TIPO_UC" cascade constraints;
DROP TABLE "SEMAD"."UNIDADE_EXEC_ORC" cascade constraints;
DROP TABLE "SEMAD"."CAMPO" cascade constraints;
DROP TABLE "SEMAD"."TABELA" cascade constraints;
DROP TABLE "SEMAD"."USUARIO" cascade constraints;
DROP TABLE "SEMAD"."VALOR_HISTORICO" cascade constraints;
--------------------------------------------------------
--  DDL for Table CONTRATO_CP
--------------------------------------------------------

  CREATE TABLE "SEMAD"."CONTRATO_CP" 
   (	"ID_CONTRATO_CP" NUMBER(*,0), 
	"NB_CODIGO" VARCHAR2(20 BYTE), 
	"DT_INICIO_VALIDADE" DATE, 
	"DT_FIM_VALIDADE" DATE, 
	"CS_TIPO_PRAZO" NUMBER(*,0), 
	"NB_PROC_ADMIN" VARCHAR2(50 BYTE), 
	"NB_VALOR_GLOBAL" NUMBER(12,2), 
	"TX_OBJETO" VARCHAR2(2000 BYTE), 
	"DT_CADASTRO" DATE, 
	"DT_ALTERACAO" DATE, 
	"NB_PRAZO" NUMBER(*,0), 
	"ID_UNID_GEST_RESP" NUMBER(*,0), 
	"ID_UNID_GEST_CADASTRO" NUMBER(*,0), 
	"ID_PESSOA_RESP" NUMBER(*,0), 
	"ID_PESSOA_CADASTRO" NUMBER(*,0), 
	"ID_UNID_GEST_ALTERACAO" NUMBER(*,0), 
	"ID_PESSOA_ALTERACAO" NUMBER(*,0), 
	"TX_OBSERVACAO" VARCHAR2(2000 BYTE), 
	"ID_UNIDADE_ORC" NUMBER, 
	"CS_TIPO_CONTRATO_CP" NUMBER, 
	"ID_MODALIDADE_CP" NUMBER, 
	"ID_PESSOA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
 

   COMMENT ON COLUMN "SEMAD"."CONTRATO_CP"."ID_PESSOA_RESP" IS 'É o identificador único das pessoa físicas que são funcionários da PMM.';
 
   COMMENT ON COLUMN "SEMAD"."CONTRATO_CP"."ID_PESSOA_CADASTRO" IS 'É o identificador único das pessoa físicas que são funcionários da PMM.';
 
   COMMENT ON COLUMN "SEMAD"."CONTRATO_CP"."ID_PESSOA_ALTERACAO" IS 'É o identificador único das pessoa físicas que são funcionários da PMM.';
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."CONTRATO_CP" TO "THIAGOQUEIROZ";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS_CONTRAT";
 
  GRANT SELECT ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS_CONS";
--------------------------------------------------------
--  DDL for Table FUNCIONARIO_2
--------------------------------------------------------

  CREATE TABLE "SEMAD"."FUNCIONARIO_2" 
   (	"ID_UNIDADE_GESTORA" NUMBER, 
	"ID_PESSOA_FUNCIONARIO" NUMBER, 
	"DT_CADASTRO" DATE, 
	"NB_ORGAO_RB" NUMBER, 
	"NB_TEMPLATE_RB" NUMBER, 
	"NB_SCORE_RB" NUMBER, 
	"CS_TIPO_FUNCIONARIO" NUMBER, 
	"CS_SITUACAO_FUNCIONARIO" NUMBER, 
	"TX_NOME_GUERRA" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
 

   COMMENT ON COLUMN "SEMAD"."FUNCIONARIO_2"."ID_PESSOA_FUNCIONARIO" IS 'E o identificador unico das pessoa fisicas.';
 
   COMMENT ON TABLE "SEMAD"."FUNCIONARIO_2"  IS 'Representa os funcionarios da PMM.';
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PONTOELETRONICO_ADMIN";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "XPTO_CONNECT";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "LICITAC?O";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "ESTOQUE";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "ORGANIZACIONAL";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PROT_SEMSA";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PROT_LICITACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "APLICAR_PESSOAS";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PROT_CONSULTORES";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PROT_TRAMITE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "CONTAS_PUBLICAS";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PROT_CONS_EXT";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PATRIMONIO";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "COLETORDEPONTO";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PROT_TRAM_SEMSA";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PROT_IMPLURB";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PROT_CONS_IMPL";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PROT_TRAM_IMPL";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "ESTOQUE_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PROT_CML";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PONTO_SEMEF";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PONTO_CONS_SEMEF";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "ESTOQUE_KITS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PONTO_SEMAD";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "USUARIO_ADMIN";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PONTO_CONSULTA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PONTO_SEMASC";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "ESTOQUE_ADMIN";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "GESTAOCONTASPUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PONTO_SEMASDH";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "EST_OPERADOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "EST_ATENDENTE";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "EST_AUTORIZACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "EST_GESTOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PONTO_SEMINF";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PONTO_MANAUSTRANS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PONTO_SEMMAS";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "SEMAD_LNK";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "MAYCON";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."FUNCIONARIO_2" TO "IWAMOTO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PONTO_FDT";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "VOYAGE_SOLICITANTE";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "VOYAGE_GESTOR";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "EST_RM";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PONTOELETRONICOV2_CONS";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "VOYAGE_GESTOR_PASSAGEM";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."FUNCIONARIO_2" TO "NEILA_SEMAD";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "JURIDICO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."FUNCIONARIO_2" TO "LILIANE_FIGUEIREDO";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "JURIDICO_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "JURIDICO_OPERACIONAL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "JURIDICO_GESTORAUXILIAR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "JURIDICO_GESTOR";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "JURIDICO_OPERACIONALTCE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "EST_ALMOXPEQUENOS";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "ORGANIZACIONAL_ADM";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PATRIMONIO_IMOVEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PATRIMONIO_IMOVEL_REL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PATRIMONIO_MOVEL_CAD";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "PATRIMONIO_MOVEL_REL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "GESTAOCONTASPUBLICAS_CONTRAT";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "PATRIMONIO_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "IRP";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "TESTES";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "GESTAOESPM";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "EST_CONTABIL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "IRP_GESTOR_RP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "IRP_GESTOR_CATALOGACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_2" TO "IRP_SOLICITANTE";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "EST_INVENTARIO";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_2" TO "HABITACAO";
--------------------------------------------------------
--  DDL for Table TIPO_UC
--------------------------------------------------------

  CREATE TABLE "SEMAD"."TIPO_UC" 
   (	"CS_TIPO_UC" NUMBER(*,0), 
	"TX_TIPO_UC" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "CONTAS_PUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."TIPO_UC" TO "NEILA_SEMAD";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_PARAMET";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_CONTRAT";
 
  GRANT SELECT ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_CONS";
--------------------------------------------------------
--  DDL for Table UNIDADE_EXEC_ORC
--------------------------------------------------------

  CREATE TABLE "SEMAD"."UNIDADE_EXEC_ORC" 
   (	"ID_UNIDADE_EXEC_ORC" NUMBER, 
	"DT_CADASTRO" DATE, 
	"TX_UNIDADE_EXEC_ORC" VARCHAR2(80 BYTE), 
	"CS_ATIVA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "CONTAS_PUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS";
 
  GRANT SELECT ON "SEMAD"."UNIDADE_EXEC_ORC" TO "SEMAD_LNK";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."UNIDADE_EXEC_ORC" TO "THIAGOQUEIROZ";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_AGUA_RE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_CONTRAT";
 
  GRANT SELECT ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "IRP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "IRP_GESTOR_BP";
--------------------------------------------------------
--  DDL for Table CAMPO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."CAMPO" 
   (	"NB_CAMPO" NUMBER, 
	"ID_TABELA" NUMBER, 
	"TX_CAMPO" VARCHAR2(80 BYTE), 
	"CS_TIPO_CAMPO" NUMBER, 
	"TX_TITULO" VARCHAR2(80 BYTE), 
	"TX_DESCRICAO" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
  GRANT SELECT ON "SEMAD"."CAMPO" TO "AUDITORIA";
 
  GRANT SELECT ON "SEMAD"."CAMPO" TO "USUARIO_ADMIN";
 
  GRANT SELECT ON "SEMAD"."CAMPO" TO "SEMAD_LNK";
--------------------------------------------------------
--  DDL for Table TABELA
--------------------------------------------------------

  CREATE TABLE "SEMAD"."TABELA" 
   (	"TX_NOME" VARCHAR2(80 BYTE), 
	"ID_TABELA" NUMBER, 
	"ID_SERVIDOR" NUMBER, 
	"CS_ATUALIZACAO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
  GRANT SELECT ON "SEMAD"."TABELA" TO "AUDITORIA";
 
  GRANT SELECT ON "SEMAD"."TABELA" TO "USUARIO_ADMIN";
 
  GRANT SELECT ON "SEMAD"."TABELA" TO "SEMAD_LNK";
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."USUARIO" 
   (	"ID_USUARIO" NUMBER(5,0), 
	"TX_LOGIN" VARCHAR2(20 BYTE), 
	"CS_SITUACAO" NUMBER DEFAULT 0, 
	"TX_CONFIGURACAO" LONG, 
	"ID_PESSOA_FUNCIONARIO" NUMBER, 
	"TX_MOTIVO_SITUACAO" VARCHAR2(200 BYTE), 
	"ID_UNIDADE_GESTORA" NUMBER, 
	"DT_ULTIMO_ACESSO" DATE, 
	"TX_IP_ULTIMO_ACESSO" VARCHAR2(15 BYTE), 
	"TX_EMAIL_PMM" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCA_DATA" ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "BANCOPRECO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "BP_FINALIZADORES";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "AUDITORIA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "XPTO_CONNECT";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ADMINISTRADORES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "LICITAC?O";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ESTOQUE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "Q_BANCO_PRECOS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "BP_CADASTRO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_SEMSA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_LICITACAO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "BP_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "APLICAR_PESSOAS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CONSULTORES";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_TRAMITE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "CONTAS_PUBLICAS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "BP_MATERIAL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "WORKFLOW";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CONS_EXT";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "PATRIMONIO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "COLETORDEPONTO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_TRAM_SEMSA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PONTO_ELETRONICO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_IMPLURB";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CONS_IMPL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_TRAM_IMPL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "WOKF_EXTERNO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "ESTOQUE_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CML";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PRE_CADASTRO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PONTO_SEMEF";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ESTOQUE_KITS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "REGISTROPRECOS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "USUARIO_ADMIN";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ESTOQUE_ADMIN";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GESTAOESCOLAR";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_OPERADOR";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_ATENDENTE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_AUTORIZACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "EST_GESTOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GE_OPERADOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "R_BANCOPRECOS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_RECEBIMENTO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GE_GESTOR";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "SEMAD_LNK";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "THIAGO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "VALERIA";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "ROSANA";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "TACIANA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "MAYCON";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "JUSSARA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "VALDERI";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "SARYTA_GARCEZ";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "IWAMOTO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "BERNARDO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "ANDRE_PINHEIRO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "IVY_SA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_SOLICITANTE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_GESTOR";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "EST_RM";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_GESTOR_PASSAGEM";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "ROBSON";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "NEILA_SEMAD";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "JURIDICO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PGM";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "KEYCE_MARQUES";
 
  GRANT ALTER, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_CONSULTA";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_OPERACIONAL";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_GESTORAUXILIAR";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_GESTOR";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_OPERACIONALTCE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_ALMOXPEQUENOS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "HABITACAO_CADASTRO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_IMOVEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_IMOVEL_REL";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_CAD";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_REL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_CEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOESCOLAR_CONSULTA";
 
  GRANT ALTER, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JUR_DISTRIBUICAO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "EMANUELLE_ALVES";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JAMILE_BREVAL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_MOV_IND";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PATRIMONIO_CONS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_CONS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "TESTES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PONTOELETRONICOV2_RH";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_CONTABIL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_GESTOR_RP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_GESTOR_BP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_GESTOR_CATALOGACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_SOLICITANTE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_INVENTARIO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "HABITACAO";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_MOVI";
-- Não é possível renderizar a DLL TABLE para o objeto SEMAD.VALOR_HISTORICO com o DBMS_METADATA tentando um gerador interno.
ALTER TABLE SEMAD.VALOR_HISTORICO
ADD CONSTRAINT IDX_FK1_VALOR_HISTORICO FOREIGN KEY
(
  ID_USUARIO 
, NB_TRANSACAO_HISTORICO 
, ID_TABELA 
)
REFERENCES SEMAD.TRANSACAO_HISTORICO
(
  ID_USUARIO 
, NB_TRANSACAO_HISTORICO 
, ID_TABELA 
)
ENABLE
ALTER TABLE SEMAD.VALOR_HISTORICO
ADD CONSTRAINT IDX_FK2_VALOR_HISTORICO FOREIGN KEY
(
  ID_TABELA 
, NB_CAMPO 
)
REFERENCES SEMAD.CAMPO
(
  ID_TABELA 
, NB_CAMPO 
)
ENABLECREATE TABLE SEMAD.VALOR_HISTORICO 
(
  ID_TABELA NUMBER NOT NULL 
, NB_TRANSACAO_HISTORICO NUMBER NOT NULL 
, NB_CAMPO NUMBER NOT NULL 
, ID_USUARIO NUMBER NOT NULL 
, NB_VALOR_HISTORICO NUMBER NOT NULL 
, NB_VALOR_VARCHAR2000 VARCHAR2(4000 BYTE) 
, NB_OLD_VARCHAR2000 VARCHAR2(4000 BYTE) 
, NB_OLD_LONG_RAW BLOB 
, CONSTRAINT IDX_PK_VALOR_HISTORICO PRIMARY KEY 
  (
    NB_CAMPO 
  , ID_TABELA 
  , ID_USUARIO 
  , NB_TRANSACAO_HISTORICO 
  , NB_VALOR_HISTORICO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "PMM_DATA" 
PCTFREE 10 
INITRANS 10 
STORAGE 
( 
  INITIAL 1109393408 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
) 
LOB (NB_OLD_LONG_RAW) STORE AS SYS_LOB0000098230C00008$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  PCTVERSION 10 
  NOCACHE 
  LOGGING  
)CREATE INDEX SEMAD.IDX_FK3_VALOR_HISTORICO ON SEMAD.VALOR_HISTORICO (ID_TABELA ASC) 
LOGGING 
TABLESPACE "PMM_INDEX" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 570425344 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SEMAD.IDX_FK5_VALOR_HISTORICO ON SEMAD.VALOR_HISTORICO (ID_TABELA ASC, NB_TRANSACAO_HISTORICO ASC, NB_CAMPO ASC, ID_USUARIO ASC) 
LOGGING 
TABLESPACE "PMM_INDEX" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 995098624 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."VALOR_HISTORICO" TO "AUDITORIA";
 
  GRANT SELECT ON "SEMAD"."VALOR_HISTORICO" TO "USUARIO_ADMIN";
 
  GRANT SELECT ON "SEMAD"."VALOR_HISTORICO" TO "SEMAD_LNK";
REM INSERTING into SEMAD.CONTRATO_CP
SET DEFINE OFF;
Insert into SEMAD.CONTRATO_CP (ID_CONTRATO_CP,NB_CODIGO,DT_INICIO_VALIDADE,DT_FIM_VALIDADE,CS_TIPO_PRAZO,NB_PROC_ADMIN,NB_VALOR_GLOBAL,TX_OBJETO,DT_CADASTRO,DT_ALTERACAO,NB_PRAZO,ID_UNID_GEST_RESP,ID_UNID_GEST_CADASTRO,ID_PESSOA_RESP,ID_PESSOA_CADASTRO,ID_UNID_GEST_ALTERACAO,ID_PESSOA_ALTERACAO,TX_OBSERVACAO,ID_UNIDADE_ORC,CS_TIPO_CONTRATO_CP,ID_MODALIDADE_CP,ID_PESSOA) values ('561','00001/2013/SEMAD',to_date('12/08/13','DD/MM/RR'),to_date('07/08/14','DD/MM/RR'),'1','123','0,01','TESTE DE CONTRATO DE ESTAGIO REMUNERADO',to_date('12/08/13','DD/MM/RR'),to_date('12/08/13','DD/MM/RR'),'360','83','83','19824','141519','83','141519','TESTE DE CONTRATO DE ESTAGIO REMUNERADO','83','10',null,null);
Insert into SEMAD.CONTRATO_CP (ID_CONTRATO_CP,NB_CODIGO,DT_INICIO_VALIDADE,DT_FIM_VALIDADE,CS_TIPO_PRAZO,NB_PROC_ADMIN,NB_VALOR_GLOBAL,TX_OBJETO,DT_CADASTRO,DT_ALTERACAO,NB_PRAZO,ID_UNID_GEST_RESP,ID_UNID_GEST_CADASTRO,ID_PESSOA_RESP,ID_PESSOA_CADASTRO,ID_UNID_GEST_ALTERACAO,ID_PESSOA_ALTERACAO,TX_OBSERVACAO,ID_UNIDADE_ORC,CS_TIPO_CONTRATO_CP,ID_MODALIDADE_CP,ID_PESSOA) values ('541','2013/0001 NB_CODIGO',to_date('01/04/13','DD/MM/RR'),to_date('13/04/13','DD/MM/RR'),'1',null,null,'TESTE OBJETO',to_date('15/04/13','DD/MM/RR'),to_date('15/04/13','DD/MM/RR'),'12','83','83','141519','141519','83','141519','TESTE OBSERVACAO','83','3',null,null);
Insert into SEMAD.CONTRATO_CP (ID_CONTRATO_CP,NB_CODIGO,DT_INICIO_VALIDADE,DT_FIM_VALIDADE,CS_TIPO_PRAZO,NB_PROC_ADMIN,NB_VALOR_GLOBAL,TX_OBJETO,DT_CADASTRO,DT_ALTERACAO,NB_PRAZO,ID_UNID_GEST_RESP,ID_UNID_GEST_CADASTRO,ID_PESSOA_RESP,ID_PESSOA_CADASTRO,ID_UNID_GEST_ALTERACAO,ID_PESSOA_ALTERACAO,TX_OBSERVACAO,ID_UNIDADE_ORC,CS_TIPO_CONTRATO_CP,ID_MODALIDADE_CP,ID_PESSOA) values ('322','2012/0001',to_date('01/01/12','DD/MM/RR'),to_date('01/01/13','DD/MM/RR'),'2','123456','65000','teste objeto',to_date('22/01/13','DD/MM/RR'),to_date('12/08/13','DD/MM/RR'),'12','83','83','141519','141519','83','141519','teste obs','83','2',null,null);
Insert into SEMAD.CONTRATO_CP (ID_CONTRATO_CP,NB_CODIGO,DT_INICIO_VALIDADE,DT_FIM_VALIDADE,CS_TIPO_PRAZO,NB_PROC_ADMIN,NB_VALOR_GLOBAL,TX_OBJETO,DT_CADASTRO,DT_ALTERACAO,NB_PRAZO,ID_UNID_GEST_RESP,ID_UNID_GEST_CADASTRO,ID_PESSOA_RESP,ID_PESSOA_CADASTRO,ID_UNID_GEST_ALTERACAO,ID_PESSOA_ALTERACAO,TX_OBSERVACAO,ID_UNIDADE_ORC,CS_TIPO_CONTRATO_CP,ID_MODALIDADE_CP,ID_PESSOA) values ('562','123456',to_date('09/09/13','DD/MM/RR'),to_date('09/09/14','DD/MM/RR'),'2',null,null,null,to_date('09/09/13','DD/MM/RR'),to_date('09/09/13','DD/MM/RR'),'12','83','83','141519','141519','83','141519',null,'83','10',null,null);
--------------------------------------------------------
--  DDL for Index XIF8CONTRATO_CP
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF8CONTRATO_CP" ON "SEMAD"."CONTRATO_CP" ("ID_UNIDADE_ORC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKCONTRATO_CP
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKCONTRATO_CP" ON "SEMAD"."CONTRATO_CP" ("ID_CONTRATO_CP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF3CONTRATO_CP
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF3CONTRATO_CP" ON "SEMAD"."CONTRATO_CP" ("ID_UNID_GEST_RESP", "ID_PESSOA_RESP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF4CONTRATO_CP
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF4CONTRATO_CP" ON "SEMAD"."CONTRATO_CP" ("ID_UNID_GEST_CADASTRO", "ID_PESSOA_CADASTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF5CONTRATO_CP
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF5CONTRATO_CP" ON "SEMAD"."CONTRATO_CP" ("ID_UNID_GEST_ALTERACAO", "ID_PESSOA_ALTERACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  Constraints for Table CONTRATO_CP
--------------------------------------------------------

  ALTER TABLE "SEMAD"."CONTRATO_CP" MODIFY ("ID_CONTRATO_CP" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" MODIFY ("NB_CODIGO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" MODIFY ("DT_INICIO_VALIDADE" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" MODIFY ("DT_FIM_VALIDADE" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" MODIFY ("ID_UNID_GEST_RESP" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" MODIFY ("ID_UNID_GEST_CADASTRO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" MODIFY ("ID_PESSOA_RESP" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" MODIFY ("ID_PESSOA_CADASTRO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" MODIFY ("ID_UNID_GEST_ALTERACAO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" MODIFY ("ID_PESSOA_ALTERACAO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" ADD PRIMARY KEY ("ID_CONTRATO_CP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA"  ENABLE;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."CONTRATO_CP" TO "THIAGOQUEIROZ";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS_CONTRAT";
 
  GRANT SELECT ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS_CONS";
--------------------------------------------------------
--  Ref Constraints for Table CONTRATO_CP
--------------------------------------------------------

  ALTER TABLE "SEMAD"."CONTRATO_CP" ADD CONSTRAINT "CONTRATO_CP_TIPO_UC_FK1" FOREIGN KEY ("CS_TIPO_CONTRATO_CP")
	  REFERENCES "SEMAD"."TIPO_UC" ("CS_TIPO_UC") ENABLE;
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" ADD FOREIGN KEY ("ID_UNID_GEST_ALTERACAO", "ID_PESSOA_ALTERACAO")
	  REFERENCES "SEMAD"."FUNCIONARIO_2" ("ID_UNIDADE_GESTORA", "ID_PESSOA_FUNCIONARIO") ENABLE;
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" ADD FOREIGN KEY ("ID_UNID_GEST_CADASTRO", "ID_PESSOA_CADASTRO")
	  REFERENCES "SEMAD"."FUNCIONARIO_2" ("ID_UNIDADE_GESTORA", "ID_PESSOA_FUNCIONARIO") ENABLE;
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" ADD FOREIGN KEY ("ID_UNID_GEST_RESP", "ID_PESSOA_RESP")
	  REFERENCES "SEMAD"."FUNCIONARIO_2" ("ID_UNIDADE_GESTORA", "ID_PESSOA_FUNCIONARIO") ENABLE;
 
  ALTER TABLE "SEMAD"."CONTRATO_CP" ADD FOREIGN KEY ("ID_UNIDADE_ORC")
	  REFERENCES "SEMAD"."UNIDADE_EXEC_ORC" ("ID_UNIDADE_EXEC_ORC") ON DELETE SET NULL ENABLE;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."CONTRATO_CP" TO "THIAGOQUEIROZ";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS_CONTRAT";
 
  GRANT SELECT ON "SEMAD"."CONTRATO_CP" TO "GESTAOCONTASPUBLICAS_CONS";
--------------------------------------------------------
--  DDL for Trigger T_AVS_IUD_CONTRATO_CP
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SEMAD"."T_AVS_IUD_CONTRATO_CP" 
  AFTER
  INSERT OR DELETE OR UPDATE
  on semad.Contrato_CP
  REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
  
declare
  pnb_Valor_Historico number;
  pID_Tabela number;
  pnb_Campo number;
  pnb_Transacao number;
  pID_Usuario number;
  pcs_evento number;
begin
  select id_usuario into pid_usuario
  from usuario
  where tx_login = user;
  if inserting then
     pcs_evento := 1;
  else
     if updating then
        pcs_evento := 2;
     else
        pcs_evento := 3;
     end if;
  end if;
  pID_Tabela := semad.F_AVS_Busca_Tabela('CONTRATO_CP');
  pnb_Transacao := semad.F_AVS_Cadastra_Transacao(pID_Tabela,pID_usuario,pcs_evento );
  -- insere valor do campo ID_Contrato_CP --
  pnb_Campo := semad.F_AVS_Busca_Campo('ID_CONTRATO_CP',pID_Tabela,'INTEGER'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Contrato_CP,
          :old.ID_Contrato_CP);
  
-- insere valor do campo ID_Unid_Gest_Resp --
  pnb_Campo := semad.F_AVS_Busca_Campo('ID_UNID_GEST_RESP',pID_Tabela,'INTEGER'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Unid_Gest_Resp,
          :old.ID_Unid_Gest_Resp);
  
-- insere valor do campo ID_Pessoa_Resp --
  pnb_Campo := semad.F_AVS_Busca_Campo('ID_PESSOA_RESP',pID_Tabela,'INTEGER'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Pessoa_Resp,
          :old.ID_Pessoa_Resp);
  
-- insere valor do campo ID_Unid_Gest_Cadastro --
  pnb_Campo := semad.F_AVS_Busca_Campo('ID_UNID_GEST_CADASTRO',pID_Tabela,'INTEGER'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Unid_Gest_Cadastro,
          :old.ID_Unid_Gest_Cadastro);
  
-- insere valor do campo ID_Pessoa_Cadastro --
  pnb_Campo := semad.F_AVS_Busca_Campo('ID_PESSOA_CADASTRO',pID_Tabela,'INTEGER'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Pessoa_Cadastro,
          :old.ID_Pessoa_Cadastro);
  
-- insere valor do campo nb_Codigo --
  pnb_Campo := semad.F_AVS_Busca_Campo('NB_CODIGO',pID_Tabela,'VARCHAR2(20)'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.nb_Codigo,
          :old.nb_Codigo);
  
-- insere valor do campo cs_Tipo_Prazo --
  pnb_Campo := semad.F_AVS_Busca_Campo('CS_TIPO_PRAZO',pID_Tabela,'INTEGER'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.cs_Tipo_Prazo,
          :old.cs_Tipo_Prazo);
  
-- insere valor do campo dt_Inicio_Validade --
  pnb_Campo := semad.F_AVS_Busca_Campo('DT_INICIO_VALIDADE',pID_Tabela,'DATE'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.dt_Inicio_Validade,
          :old.dt_Inicio_Validade);
  
-- insere valor do campo dt_Fim_Validade --
  pnb_Campo := semad.F_AVS_Busca_Campo('DT_FIM_VALIDADE',pID_Tabela,'DATE'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.dt_Fim_Validade,
          :old.dt_Fim_Validade);
  
-- insere valor do campo nb_Proc_Admin --
  pnb_Campo := semad.F_AVS_Busca_Campo('NB_PROC_ADMIN',pID_Tabela,'VARCHAR2(50)'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.nb_Proc_Admin,
          :old.nb_Proc_Admin);
  
-- insere valor do campo nb_Valor_Global --
  pnb_Campo := semad.F_AVS_Busca_Campo('NB_VALOR_GLOBAL',pID_Tabela,'NUMBER(12,2)'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.nb_Valor_Global,
          :old.nb_Valor_Global);
  
-- insere valor do campo tx_Objeto --
  pnb_Campo := semad.F_AVS_Busca_Campo('TX_OBJETO',pID_Tabela,'VARCHAR2(2000)'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.tx_Objeto,
          :old.tx_Objeto);
  
-- insere valor do campo dt_Cadastro --
  pnb_Campo := semad.F_AVS_Busca_Campo('DT_CADASTRO',pID_Tabela,'DATE'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.dt_Cadastro,
          :old.dt_Cadastro);
  
-- insere valor do campo dt_Alteracao --
  pnb_Campo := semad.F_AVS_Busca_Campo('DT_ALTERACAO',pID_Tabela,'DATE'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.dt_Alteracao,
          :old.dt_Alteracao);
  
-- insere valor do campo nb_Prazo --
  pnb_Campo := semad.F_AVS_Busca_Campo('NB_PRAZO',pID_Tabela,'INTEGER'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.nb_Prazo,
          :old.nb_Prazo);
  
-- insere valor do campo ID_Unid_Gest_Alteracao --
  pnb_Campo := semad.F_AVS_Busca_Campo('ID_UNID_GEST_ALTERACAO',pID_Tabela,'INTEGER'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Unid_Gest_Alteracao,
          :old.ID_Unid_Gest_Alteracao);
  
-- insere valor do campo ID_Pessoa_Alteracao --
  pnb_Campo := semad.F_AVS_Busca_Campo('ID_PESSOA_ALTERACAO',pID_Tabela,'INTEGER'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Pessoa_Alteracao,
          :old.ID_Pessoa_Alteracao);
  
-- insere valor do campo tx_Observacao --
  pnb_Campo := semad.F_AVS_Busca_Campo('TX_OBSERVACAO',pID_Tabela,'VARCHAR2(2000)'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.tx_Observacao,
          :old.tx_Observacao);
  
-- insere valor do campo cs_Tipo_Contrato_CP --
  pnb_Campo := semad.F_AVS_Busca_Campo('CS_TIPO_CONTRATO_CP',pID_Tabela,'INTEGER'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.cs_Tipo_Contrato_CP,
          :old.cs_Tipo_Contrato_CP);
  
-- insere valor do campo ID_Unidade_Orc --
  pnb_Campo := semad.F_AVS_Busca_Campo('ID_UNIDADE_ORC',pID_Tabela,'INTEGER'); 
  pnb_Valor_Historico := semad.F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Unidade_Orc,
          :old.ID_Unidade_Orc);
  

end; --
/
ALTER TRIGGER "SEMAD"."T_AVS_IUD_CONTRATO_CP" ENABLE;
--------------------------------------------------------
--  DDL for Function F_AVS_BUSCA_CAMPO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SEMAD"."F_AVS_BUSCA_CAMPO" 
  (ptx_campo IN campo.tx_campo%type,
   pid_tabela IN tabela.id_tabela%type,
   ptx_tipo_campo IN tipo_campo.tx_tipo_campo%type)
RETURN  campo.nb_campo%type IS pnb_campo campo.nb_campo%type;

   pid_servidor   number;
   numregs        number;
   pcs_tipo_campo number;
BEGIN
    pnb_campo := 0;
    numregs := 0;
    
    select max(nb_campo) into numregs
    from campo
    where tx_campo = ptx_campo and
          id_tabela = pid_tabela;
     
    if numregs > 0 then
      select nb_campo into pnb_campo
      from campo
      where tx_campo = ptx_campo and
            id_tabela = pid_tabela;
    else
      select max(id_servidor) into pid_servidor
      from parametros_default;
      pcs_tipo_campo := F_Busca_Tipo_Campo(ptx_tipo_campo,pid_servidor);
      pnb_campo := F_G_PK_campo(pid_tabela);
      insert into campo (id_tabela, nb_campo, tx_campo,cs_tipo_campo)
             values (pid_tabela, pnb_campo, ptx_campo,pcs_tipo_campo);
    end if;

    RETURN pnb_campo;
END;


-- End of DDL script for F_AVS_BUSCA_CAMPO

/
--------------------------------------------------------
--  DDL for Function F_AVS_BUSCA_TABELA
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SEMAD"."F_AVS_BUSCA_TABELA" 
  (ptx_tabela IN Tabela.tx_nome%type)
RETURN  Tabela.ID_Tabela%type IS Pid_Tabela Tabela.ID_Tabela%type;
   pid_servidor number;
   numregs number;
BEGIN
    numregs := 0;
    select count(id_tabela) into numregs
    from tabela
    where tx_nome = ptx_tabela;
    if numregs <> 0 then
       select id_tabela into Pid_Tabela
       from tabela
       where tx_nome = ptx_tabela;
    else
      pid_tabela := F_G_PK_Tabela();
      select max(id_servidor) into pid_servidor
           from parametros_default;
      insert into tabela (id_tabela, tx_nome, id_servidor, cs_atualizacao)
             values (pid_tabela, ptx_tabela, pid_servidor,2);
    end if;
    RETURN Pid_Tabela;
END;


-- End of DDL script for F_AVS_BUSCA_TABELA

/
--------------------------------------------------------
--  DDL for Function F_AVS_CADASTRA_TRANSACAO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SEMAD"."F_AVS_CADASTRA_TRANSACAO" 
  ( pID_Tabela IN Tabela.ID_Tabela%type,
    pID_Usuario IN Usuario.ID_Usuario%type,
    pcs_evento IN number)
  RETURN  number IS pnb_Transacao number;
BEGIN
  pnb_transacao := F_G_PK_transacao_historico(pid_usuario,pid_tabela);
  insert into transacao_historico (id_tabela, id_usuario, nb_transacao_historico, dt_transacao_historico, cs_evento)
  values (pid_tabela, pid_usuario, pnb_transacao, sysdate, pcs_evento);
  RETURN pnb_transacao;
END; -- F_AVS_CADASTRA_TRANSACAO

-- End of DDL script for F_AVS_CADASTRA_TRANSACAO

/
--------------------------------------------------------
--  DDL for Function F_G_PK_VALOR_HISTORICO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SEMAD"."F_G_PK_VALOR_HISTORICO" 
(PID_TABELA NUMBER,PNB_TRANSACAO_HISTORICO NUMBER,PNB_CAMPO NUMBER,PID_USUARIO NUMBER)
RETURN NUMBER IS V_N_VALOR_HISTORICO NUMBER;
BEGIN
   SELECT COUNT (*) INTO  V_N_VALOR_HISTORICO
   FROM VALOR_HISTORICO
   WHERE(ID_TABELA = PID_TABELA AND NB_TRANSACAO_HISTORICO = PNB_TRANSACAO_HISTORICO AND NB_CAMPO = PNB_CAMPO AND ID_USUARIO = PID_USUARIO );
    IF V_N_VALOR_HISTORICO = 0 THEN
        V_N_VALOR_HISTORICO := 1;
    ELSE
        SELECT MAX(NB_VALOR_HISTORICO) + 1
        INTO V_N_VALOR_HISTORICO
        FROM VALOR_HISTORICO
        WHERE (ID_TABELA = PID_TABELA AND NB_TRANSACAO_HISTORICO = PNB_TRANSACAO_HISTORICO AND NB_CAMPO = PNB_CAMPO AND ID_USUARIO = PID_USUARIO );
     END IF;
     RETURN V_N_VALOR_HISTORICO;
END; -- F_G_PK_VALOR_HISTORICO

/
