--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Março-21-2014   
--------------------------------------------------------
DROP TABLE "SEMAD"."ORGAO_GESTOR_EMAIL" cascade constraints;
DROP TABLE "SEMAD"."ORGAO_GESTOR_ESTAGIO" cascade constraints;
--------------------------------------------------------
--  DDL for Table ORGAO_GESTOR_EMAIL
--------------------------------------------------------

  CREATE TABLE "SEMAD"."ORGAO_GESTOR_EMAIL" 
   (	"ID_ORGAO_GESTOR_ESTAGIO" NUMBER, 
	"NB_ORGAO_GESTOR_EMAIL" NUMBER, 
	"TX_EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Table ORGAO_GESTOR_ESTAGIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."ORGAO_GESTOR_ESTAGIO" 
   (	"ID_ORGAO_GESTOR_ESTAGIO" NUMBER(*,0), 
	"TX_ORGAO_GESTOR_ESTAGIO" VARCHAR2(255 BYTE), 
	"DT_CADASTRO" DATE, 
	"DT_ATUALIZACAO" DATE, 
	"ID_UNIDADE_ORG" NUMBER(*,0), 
	"TX_CNPJ" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
 

   COMMENT ON COLUMN "SEMAD"."ORGAO_GESTOR_ESTAGIO"."ID_UNIDADE_ORG" IS 'Identificador único de uma unidade organizacional.';
REM INSERTING into SEMAD.ORGAO_GESTOR_EMAIL
SET DEFINE OFF;
Insert into SEMAD.ORGAO_GESTOR_EMAIL (ID_ORGAO_GESTOR_ESTAGIO,NB_ORGAO_GESTOR_EMAIL,TX_EMAIL) values ('2','1','andre.sousa@pmm.am.gov.br');
Insert into SEMAD.ORGAO_GESTOR_EMAIL (ID_ORGAO_GESTOR_ESTAGIO,NB_ORGAO_GESTOR_EMAIL,TX_EMAIL) values ('2','2','rodrigo.cabral@pmm.am.gov.br');
--------------------------------------------------------
--  DDL for Index ORGAO_GESTOR_EMAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."ORGAO_GESTOR_EMAIL_PK" ON "SEMAD"."ORGAO_GESTOR_EMAIL" ("ID_ORGAO_GESTOR_ESTAGIO", "NB_ORGAO_GESTOR_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  Constraints for Table ORGAO_GESTOR_EMAIL
--------------------------------------------------------

  ALTER TABLE "SEMAD"."ORGAO_GESTOR_EMAIL" ADD CONSTRAINT "ORGAO_GESTOR_EMAIL_PK" PRIMARY KEY ("ID_ORGAO_GESTOR_ESTAGIO", "NB_ORGAO_GESTOR_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA"  ENABLE;
 
  ALTER TABLE "SEMAD"."ORGAO_GESTOR_EMAIL" MODIFY ("ID_ORGAO_GESTOR_ESTAGIO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ORGAO_GESTOR_EMAIL" MODIFY ("NB_ORGAO_GESTOR_EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ORGAO_GESTOR_EMAIL" MODIFY ("TX_EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ORGAO_GESTOR_EMAIL
--------------------------------------------------------

  ALTER TABLE "SEMAD"."ORGAO_GESTOR_EMAIL" ADD CONSTRAINT "ORGAO_GESTOR_EMAIL_ORGAO__FK1" FOREIGN KEY ("ID_ORGAO_GESTOR_ESTAGIO")
	  REFERENCES "SEMAD"."ORGAO_GESTOR_ESTAGIO" ("ID_ORGAO_GESTOR_ESTAGIO") ENABLE;
