--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Março-21-2014   
--------------------------------------------------------
DROP TABLE "SEMAD"."UNIDADE_EXEC_ORC" cascade constraints;
--------------------------------------------------------
--  DDL for Table UNIDADE_EXEC_ORC
--------------------------------------------------------

  CREATE TABLE "SEMAD"."UNIDADE_EXEC_ORC" 
   (	"ID_UNIDADE_EXEC_ORC" NUMBER, 
	"DT_CADASTRO" DATE, 
	"TX_UNIDADE_EXEC_ORC" VARCHAR2(80 BYTE), 
	"CS_ATIVA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "CONTAS_PUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS";
 
  GRANT SELECT ON "SEMAD"."UNIDADE_EXEC_ORC" TO "SEMAD_LNK";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."UNIDADE_EXEC_ORC" TO "THIAGOQUEIROZ";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_AGUA_RE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_CONTRAT";
 
  GRANT SELECT ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "IRP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "IRP_GESTOR_BP";
REM INSERTING into SEMAD.UNIDADE_EXEC_ORC
SET DEFINE OFF;
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('83',to_date('08/10/02','DD/MM/RR'),'Secretaria Municipal de Administração','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('79',to_date('06/01/03','DD/MM/RR'),'Câmara Municipal de Manaus','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('80',to_date('06/01/03','DD/MM/RR'),'Gabinete do Prefeito/Gabinete do Vice-Prefeito','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('81',to_date('06/01/03','DD/MM/RR'),'Gabinete Civil','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('82',to_date('06/01/03','DD/MM/RR'),'Procuradoria Geral do Município','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('84',to_date('06/01/03','DD/MM/RR'),'Secretaria Municipal de Finanças, Planejamento e Tecnologia da Informação','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('116',to_date('06/01/03','DD/MM/RR'),'Secretaria Municipal de Meio Ambiente e Sustentabilidade','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('118',to_date('06/01/03','DD/MM/RR'),'Gabinete Militar','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('119',to_date('06/01/03','DD/MM/RR'),'Secretaria Municipal de Educação','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('120',to_date('06/01/03','DD/MM/RR'),'Secretaria Municipal de Comunicação','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('121',to_date('06/01/03','DD/MM/RR'),'Auditoria Geral do Município','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('122',to_date('06/01/03','DD/MM/RR'),'Secretaria Municipal de Saúde','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('123',to_date('06/01/03','DD/MM/RR'),'Secretaria Municipal de Infraestrutura','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('124',to_date('12/02/04','DD/MM/RR'),'Secretaria Municipal de Produção e Abastecimento','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('125',to_date('06/01/03','DD/MM/RR'),'Secretaria Municipal de Desporto e Lazer','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('126',to_date('16/04/04','DD/MM/RR'),'Secretaria Municipal de Assistência Social e Direitos Humanos','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('127',to_date('06/01/03','DD/MM/RR'),'Secretaria Municipal de Defesa Civil','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('128',to_date('06/01/03','DD/MM/RR'),'Secretaria Municipal de Juventude','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('129',to_date('06/01/03','DD/MM/RR'),'Secretaria Municipal de Trabalho e Desenvolvimento Social','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('130',to_date('06/01/03','DD/MM/RR'),'Secretaria Especial Para Assuntos de Apoio Comunitário','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('131',to_date('06/01/03','DD/MM/RR'),'Secretaria Especial Para Articulação de Políticas Públicas','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('132',to_date('06/01/03','DD/MM/RR'),'Secretaria Especial Para Assuntos Particulares','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('133',to_date('06/01/03','DD/MM/RR'),'Instituto Municipal de Previdência e Assistência Social','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('134',to_date('06/01/03','DD/MM/RR'),'Fundação Doutor Thomas','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('135',to_date('06/01/03','DD/MM/RR'),'Empresa Municipal de Urbanização','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('136',to_date('06/01/03','DD/MM/RR'),'Superintendência Municipal de Transportes Urbanos','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('137',to_date('06/01/03','DD/MM/RR'),'Fundação Municipal de Cultura e Artes','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('138',to_date('06/01/03','DD/MM/RR'),'Fundação Municipal de Eventos e Turismo','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('539',to_date('06/01/03','DD/MM/RR'),'Gabinete do Governador/Gabinete do Vice-Governador','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('541',to_date('06/01/03','DD/MM/RR'),'Secretaria Estadual de Administração','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('544',to_date('06/01/03','DD/MM/RR'),'Secretaria Estadual de Educação','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('1068',to_date('08/06/04','DD/MM/RR'),'Secretaria Extraordinária de Projetos Especiais','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('1067',to_date('08/06/04','DD/MM/RR'),'Secretaria Municipal de Limpeza Públicos','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('1070',to_date('15/06/04','DD/MM/RR'),'Secretaria Municipal de Assuntos Federativos','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('1116',to_date('04/08/04','DD/MM/RR'),'Ouvidoria Geral do Município','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('865',to_date('05/02/04','DD/MM/RR'),'Instituto Municipal de Ordem Social e Planejamento Urbano','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('1117',to_date('04/08/04','DD/MM/RR'),'Secretaria Municipal de Defesa do Consumidor - PROCOM MANAUS','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('1361',to_date('12/01/07','DD/MM/RR'),'Secretaria Municipal de Planejamento e Administração','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('1888',to_date('28/02/13','DD/MM/RR'),'Secretaria Municipal de Projetos Especiais e Gestão Tecnológica','0');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('4824',to_date('01/03/13','DD/MM/RR'),'Secretaria Municipal de Habitação e Assuntos Fundiários','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('5050',to_date('14/03/13','DD/MM/RR'),'Fundo Municipal de Fomento à Micro e Pequena Empresa','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('5060',to_date('14/06/13','DD/MM/RR'),'Secretaria Municipal de Saúde - SEMSA SUS','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('5070',to_date('11/12/13','DD/MM/RR'),'Fundo Único de Previdência do Município de Manaus','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('5000',to_date('11/03/13','DD/MM/RR'),'Fundação Municipal de Inclusão Socioeducacional','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('5010',to_date('11/03/13','DD/MM/RR'),'Controladoria Geral do Município','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('5020',to_date('11/03/13','DD/MM/RR'),'Secretaria Municipal de Administração e Coordenação de Bairros','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('5030',to_date('11/03/13','DD/MM/RR'),'Instituto Municipal de Engenharia e Fiscalização do Trânsito','1');
Insert into SEMAD.UNIDADE_EXEC_ORC (ID_UNIDADE_EXEC_ORC,DT_CADASTRO,TX_UNIDADE_EXEC_ORC,CS_ATIVA) values ('5040',to_date('11/03/13','DD/MM/RR'),'Fundação Escola de Serviço Público Municipal','1');
--------------------------------------------------------
--  DDL for Index IDX_PK_UNIDADE_EXEC_ORC
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."IDX_PK_UNIDADE_EXEC_ORC" ON "SEMAD"."UNIDADE_EXEC_ORC" ("ID_UNIDADE_EXEC_ORC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_INDEX" ;
--------------------------------------------------------
--  Constraints for Table UNIDADE_EXEC_ORC
--------------------------------------------------------

  ALTER TABLE "SEMAD"."UNIDADE_EXEC_ORC" ADD CONSTRAINT "IDX_PK_UNIDADE_EXEC_ORC" PRIMARY KEY ("ID_UNIDADE_EXEC_ORC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_INDEX"  ENABLE;
 
  ALTER TABLE "SEMAD"."UNIDADE_EXEC_ORC" MODIFY ("ID_UNIDADE_EXEC_ORC" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."UNIDADE_EXEC_ORC" MODIFY ("DT_CADASTRO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."UNIDADE_EXEC_ORC" MODIFY ("TX_UNIDADE_EXEC_ORC" NOT NULL ENABLE);
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "CONTAS_PUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS";
 
  GRANT SELECT ON "SEMAD"."UNIDADE_EXEC_ORC" TO "SEMAD_LNK";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."UNIDADE_EXEC_ORC" TO "THIAGOQUEIROZ";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_AGUA_RE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_CONTRAT";
 
  GRANT SELECT ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "IRP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "IRP_GESTOR_BP";
GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "CONTAS_PUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS";
 
  GRANT SELECT ON "SEMAD"."UNIDADE_EXEC_ORC" TO "SEMAD_LNK";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."UNIDADE_EXEC_ORC" TO "THIAGOQUEIROZ";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_AGUA_RE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_CONTRAT";
 
  GRANT SELECT ON "SEMAD"."UNIDADE_EXEC_ORC" TO "GESTAOCONTASPUBLICAS_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "IRP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."UNIDADE_EXEC_ORC" TO "IRP_GESTOR_BP";
