DROP
  TABLE "SEMAD"."AGENCIA_ESTAGIO_EMAIL" CASCADE CONSTRAINTS;

CREATE
  TABLE "SEMAD"."AGENCIA_ESTAGIO_EMAIL"
  (
    "NB_AGENCIA_ESTAGIO_EMAIL" NUMBER NOT NULL ENABLE,
    "ID_AGENCIA_ESTAGIO"       NUMBER NOT NULL ENABLE,
    "TX_EMAIL"         VARCHAR2(100 BYTE) NOT NULL ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
    CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "PMM_DATA";
ALTER TABLE "SEMAD"."AGENCIA_ESTAGIO_EMAIL" ADD CONSTRAINT
"AGENCIA_ESTAGIO_EMAIL_PK" PRIMARY KEY
(
  "ID_AGENCIA_ESTAGIO", "NB_AGENCIA_ESTAGIO_EMAIL"
)
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE
(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
  DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "PMM_DATA" ENABLE;

CREATE OR REPLACE PUBLIC SYNONYM AGENCIA_ESTAGIO_EMAIL FOR SEMAD.AGENCIA_ESTAGIO_EMAIL;

CREATE OR REPLACE
FUNCTION       SEMAD.F_G_PK_AGENCIA_ESTAGIO_EMAIL
(PID_AGENCIA_ESTAGIO INTEGER)
RETURN NUMBER IS V_N_AGENCIA_ESTAGIO_EMAIL NUMBER;
BEGIN
   SELECT COUNT (*)
   INTO  V_N_AGENCIA_ESTAGIO_EMAIL
   FROM AGENCIA_ESTAGIO_EMAIL
   WHERE(ID_AGENCIA_ESTAGIO = PID_AGENCIA_ESTAGIO);
    IF V_N_AGENCIA_ESTAGIO_EMAIL = 0 THEN
        V_N_AGENCIA_ESTAGIO_EMAIL := 1;
    ELSE
        SELECT MAX(NB_AGENCIA_ESTAGIO_EMAIL) + 1
        INTO V_N_AGENCIA_ESTAGIO_EMAIL
        FROM AGENCIA_ESTAGIO_EMAIL
        WHERE (ID_AGENCIA_ESTAGIO = PID_AGENCIA_ESTAGIO);
     END IF;
     RETURN V_N_AGENCIA_ESTAGIO_EMAIL;
END;

CREATE OR REPLACE PUBLIC SYNONYM F_G_PK_AGENCIA_ESTAGIO_EMAIL FOR SEMAD.F_G_PK_AGENCIA_ESTAGIO_EMAIL;