DROP
  TABLE "SEMAD"."AGENTE_SETORIAL_EMAIL" CASCADE CONSTRAINTS;
CREATE
  TABLE "SEMAD"."AGENTE_SETORIAL_EMAIL"
  (
    "NB_AGENTE_SETORIAL_EMAIL" NUMBER NOT NULL ENABLE,
    "ID_SETORIAL_ESTAGIO"      NUMBER NOT NULL ENABLE,
    "TX_EMAIL"                 VARCHAR2(100 BYTE) NOT NULL ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
    CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "PMM_DATA" ;
ALTER TABLE "SEMAD"."AGENTE_SETORIAL_EMAIL" ADD CONSTRAINT
"AGENTE_SETORIAL_EMAIL_PK" PRIMARY KEY
(
  "NB_AGENTE_SETORIAL_EMAIL", "ID_SETORIAL_ESTAGIO"
)
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE
(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
  DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "PMM_DATA" ENABLE;
ALTER TABLE "SEMAD"."AGENTE_SETORIAL_EMAIL" ADD CONSTRAINT
"AGENTE_SETORIAL_EMAIL_AGE_FK1" FOREIGN KEY
(
  "ID_SETORIAL_ESTAGIO"
)
REFERENCES "SEMAD"."AGENTE_SETORIAL_ESTAGIO"
(
  "ID_SETORIAL_ESTAGIO"
)
ENABLE;
CREATE
  INDEX "SEMAD"."AGENTE_SETORIAL_EMAIL_INDEX1" ON "SEMAD".
  "AGENTE_SETORIAL_EMAIL"
  (
    "ID_SETORIAL_ESTAGIO"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
    CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "PMM_DATA" ;

CREATE OR REPLACE PUBLIC SYNONYM AGENTE_SETORIAL_EMAIL FOR SEMAD.AGENTE_SETORIAL_EMAIL;

CREATE OR REPLACE
FUNCTION       SEMAD.F_G_PK_AGENTE_SETORIAL_EMAIL
(PID_SETORIAL_ESTAGIO INTEGER)
RETURN NUMBER IS V_N_AGENTE_SETORIAL_EMAIL NUMBER;
BEGIN
   SELECT COUNT (*) INTO  V_N_AGENTE_SETORIAL_EMAIL
   FROM AGENTE_SETORIAL_EMAIL
   WHERE(ID_SETORIAL_ESTAGIO = PID_SETORIAL_ESTAGIO);
    IF V_N_AGENTE_SETORIAL_EMAIL = 0 THEN
        V_N_AGENTE_SETORIAL_EMAIL := 1;
    ELSE
        SELECT MAX(NB_AGENTE_SETORIAL_EMAIL) + 1
        INTO V_N_AGENTE_SETORIAL_EMAIL
        FROM AGENTE_SETORIAL_EMAIL
        WHERE (ID_SETORIAL_ESTAGIO = PID_SETORIAL_ESTAGIO);
     END IF;
     RETURN V_N_AGENTE_SETORIAL_EMAIL;
END;

CREATE OR REPLACE PUBLIC SYNONYM F_G_PK_AGENTE_SETORIAL_EMAIL FOR SEMAD.F_G_PK_AGENTE_SETORIAL_EMAIL;