--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Março-21-2014   
--------------------------------------------------------
DROP TABLE "SEMAD"."ESTAGIARIO_SELECAO" cascade constraints;
DROP TABLE "SEMAD"."BOLSA_ESTAGIO" cascade constraints;
DROP TABLE "SEMAD"."CURSO_ESTAGIO" cascade constraints;
DROP TABLE "SEMAD"."ESTAGIARIO" cascade constraints;
DROP TABLE "SEMAD"."INSTITUICAO_ENSINO" cascade constraints;
DROP TABLE "SEMAD"."ORGAO_ESTAGIO" cascade constraints;
DROP TABLE "SEMAD"."SELECAO_ESTAGIO" cascade constraints;
DROP TABLE "SEMAD"."SUPERVISOR_ESTAGIO" cascade constraints;
DROP TABLE "SEMAD"."TIPO_VAGA_ESTAGIO" cascade constraints;
DROP TABLE "SEMAD"."USUARIO" cascade constraints;
DROP TABLE "SEMAD"."CAMPO" cascade constraints;
DROP TABLE "SEMAD"."TABELA" cascade constraints;
DROP TABLE "SEMAD"."VALOR_HISTORICO" cascade constraints;
--------------------------------------------------------
--  DDL for Table ESTAGIARIO_SELECAO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."ESTAGIARIO_SELECAO" 
   (	"ID_SELECAO_ESTAGIO" NUMBER(*,0), 
	"CS_SITUACAO" NUMBER(*,0), 
	"TX_MOTIVO_SITUACAO" VARCHAR2(255 BYTE), 
	"ID_USUARIO_CADASTRO" NUMBER, 
	"ID_PESSOA_ESTAGIARIO" NUMBER(*,0), 
	"CS_ESCOLARIDADE" NUMBER, 
	"ID_CURSO_ESTAGIO" NUMBER, 
	"NB_PERIODO_ANO" NUMBER, 
	"CS_TURNO" NUMBER, 
	"ID_INSTITUICAO_ENSINO" NUMBER, 
	"ID_ORGAO_ESTAGIO" NUMBER, 
	"CS_TIPO_VAGA_ESTAGIO" NUMBER, 
	"TX_HORA_INICIO" VARCHAR2(20 BYTE), 
	"TX_HORA_FINAL" VARCHAR2(20 BYTE), 
	"ID_BOLSA_ESTAGIO" NUMBER, 
	"ID_PESSOA_SUPERVISOR" NUMBER, 
	"ID_USUARIO_ATUALIZACAO" NUMBER, 
	"DT_CADASTRO" DATE, 
	"DT_ATUALIZACAO" DATE, 
	"CS_CARGA_HORARIA" NUMBER, 
	"TX_ATIVIDADES" VARCHAR2(400 BYTE), 
	"NB_VALOR_TRANSPORTE" NUMBER, 
	"TX_LOCAL_ESTAGIO" VARCHAR2(255 BYTE), 
	"DT_INICIO" DATE, 
	"DT_FINAL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
 

   COMMENT ON COLUMN "SEMAD"."ESTAGIARIO_SELECAO"."CS_SITUACAO" IS '1 - Em Análise; 
2 - Aprovado; 
3 - Reprovado; 
4 - Cancelado; 
5 - Autorizado.';
 
   COMMENT ON COLUMN "SEMAD"."ESTAGIARIO_SELECAO"."ID_USUARIO_CADASTRO" IS 'Código do usuário do BD.';
 
   COMMENT ON COLUMN "SEMAD"."ESTAGIARIO_SELECAO"."ID_PESSOA_ESTAGIARIO" IS '';
--------------------------------------------------------
--  DDL for Table BOLSA_ESTAGIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."BOLSA_ESTAGIO" 
   (	"ID_BOLSA_ESTAGIO" NUMBER(*,0), 
	"TX_BOLSA_ESTAGIO" VARCHAR2(255 BYTE), 
	"NB_VALOR" NUMBER(12,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Table CURSO_ESTAGIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."CURSO_ESTAGIO" 
   (	"ID_CURSO_ESTAGIO" NUMBER(*,0), 
	"TX_CURSO_ESTAGIO" VARCHAR2(255 BYTE), 
	"CS_AREA_CONHECIMENTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Table ESTAGIARIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."ESTAGIARIO" 
   (	"ID_PESSOA_ESTAGIARIO" NUMBER(*,0), 
	"ID_PESSOA_FUNCIONARIO" NUMBER(*,0), 
	"NB_FUNCIONARIO" NUMBER(*,0), 
	"TX_CEP" VARCHAR2(20 BYTE), 
	"TX_ENDERECO" VARCHAR2(255 BYTE), 
	"NB_NUMERO" NUMBER, 
	"TX_COMPLEMENTO" VARCHAR2(255 BYTE), 
	"TX_BAIRRO" VARCHAR2(100 BYTE), 
	"TX_AGENCIA" VARCHAR2(20 BYTE), 
	"TX_CONTA_CORRENTE" VARCHAR2(20 BYTE), 
	"TX_CONTATO" VARCHAR2(180 BYTE), 
	"TX_EMAIL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
 

   COMMENT ON COLUMN "SEMAD"."ESTAGIARIO"."ID_PESSOA_ESTAGIARIO" IS 'É o identificador único das pessoa físicas.';
 
   COMMENT ON COLUMN "SEMAD"."ESTAGIARIO"."ID_PESSOA_FUNCIONARIO" IS 'É o identificador único das pessoa físicas.';
--------------------------------------------------------
--  DDL for Table INSTITUICAO_ENSINO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."INSTITUICAO_ENSINO" 
   (	"ID_INSTITUICAO_ENSINO" NUMBER(*,0), 
	"TX_INSTITUICAO_ENSINO" VARCHAR2(255 BYTE), 
	"TX_SIGLA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Table ORGAO_ESTAGIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."ORGAO_ESTAGIO" 
   (	"ID_ORGAO_ESTAGIO" NUMBER(*,0), 
	"TX_ORGAO_ESTAGIO" VARCHAR2(255 BYTE), 
	"DT_CADASTRO" DATE, 
	"DT_ATUALIZACAO" DATE, 
	"ID_UNIDADE_ORG" NUMBER(*,0), 
	"ID_USUARIO_CADASTRO" NUMBER, 
	"ID_USUARIO_ATUALIZACAO" NUMBER, 
	"CS_STATUS" NUMBER, 
	"TX_CNPJ" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
 

   COMMENT ON COLUMN "SEMAD"."ORGAO_ESTAGIO"."ID_UNIDADE_ORG" IS 'Identificador único de uma unidade organizacional.';
 
   COMMENT ON COLUMN "SEMAD"."ORGAO_ESTAGIO"."ID_USUARIO_CADASTRO" IS 'Código do usuário do BD.';
 
   COMMENT ON COLUMN "SEMAD"."ORGAO_ESTAGIO"."ID_USUARIO_ATUALIZACAO" IS 'Código do usuário do BD.';
 
   COMMENT ON COLUMN "SEMAD"."ORGAO_ESTAGIO"."CS_STATUS" IS '1 - Ativado
2 - Desativado';
--------------------------------------------------------
--  DDL for Table SELECAO_ESTAGIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."SELECAO_ESTAGIO" 
   (	"ID_SELECAO_ESTAGIO" NUMBER(*,0), 
	"DT_CADASTRO" DATE, 
	"DT_ATUALIZACAO" DATE, 
	"ID_ORGAO_ESTAGIO" NUMBER(*,0), 
	"ID_USUARIO_CADASTRO" NUMBER, 
	"TX_COD_SELECAO" VARCHAR2(20 BYTE), 
	"ID_ORGAO_GESTOR_ESTAGIO" NUMBER(*,0), 
	"ID_USUARIO_ATUALIZACAO" NUMBER, 
	"CS_SITUACAO" NUMBER(*,0), 
	"CS_SELECAO" NUMBER, 
	"ID_OFERTA_VAGA" NUMBER, 
	"ID_AGENCIA_ESTAGIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
 

   COMMENT ON COLUMN "SEMAD"."SELECAO_ESTAGIO"."ID_USUARIO_CADASTRO" IS 'Código do usuário do BD.';
 
   COMMENT ON COLUMN "SEMAD"."SELECAO_ESTAGIO"."ID_USUARIO_ATUALIZACAO" IS 'Código do usuário do BD.';
 
   COMMENT ON COLUMN "SEMAD"."SELECAO_ESTAGIO"."CS_SITUACAO" IS '1-Aberta; 
2-Efetivada; 
3-Seleção Encaminhada; 
4-Cancelada.';
 
   COMMENT ON COLUMN "SEMAD"."SELECAO_ESTAGIO"."CS_SELECAO" IS '1 - com oferta, 2 - sem oferta';
--------------------------------------------------------
--  DDL for Table SUPERVISOR_ESTAGIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."SUPERVISOR_ESTAGIO" 
   (	"ID_PESSOA_SUPERVISOR" NUMBER(*,0), 
	"ID_PESSOA_FUNCIONARIO" NUMBER(*,0), 
	"NB_FUNCIONARIO" NUMBER(*,0), 
	"TX_CURRICULO" VARCHAR2(2000 BYTE), 
	"ID_CONSELHO" NUMBER, 
	"NB_INSCRICAO_CONSELHO" VARCHAR2(80 BYTE), 
	"TX_FORMACAO" VARCHAR2(255 BYTE), 
	"TX_CARGO" VARCHAR2(255 BYTE), 
	"TX_TEMPO_EXPERIENCIA" VARCHAR2(20 BYTE), 
	"TX_EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
 

   COMMENT ON COLUMN "SEMAD"."SUPERVISOR_ESTAGIO"."ID_PESSOA_SUPERVISOR" IS 'É o identificador único das pessoa físicas.';
 
   COMMENT ON COLUMN "SEMAD"."SUPERVISOR_ESTAGIO"."ID_PESSOA_FUNCIONARIO" IS 'É o identificador único das pessoa físicas.';
--------------------------------------------------------
--  DDL for Table TIPO_VAGA_ESTAGIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."TIPO_VAGA_ESTAGIO" 
   (	"CS_TIPO_VAGA_ESTAGIO" NUMBER(*,0), 
	"TX_TIPO_VAGA_ESTAGIO" VARCHAR2(255 BYTE), 
	"ID_BOLSA_ESTAGIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."USUARIO" 
   (	"ID_USUARIO" NUMBER(5,0), 
	"TX_LOGIN" VARCHAR2(20 BYTE), 
	"CS_SITUACAO" NUMBER DEFAULT 0, 
	"TX_CONFIGURACAO" LONG, 
	"ID_PESSOA_FUNCIONARIO" NUMBER, 
	"TX_MOTIVO_SITUACAO" VARCHAR2(200 BYTE), 
	"ID_UNIDADE_GESTORA" NUMBER, 
	"DT_ULTIMO_ACESSO" DATE, 
	"TX_IP_ULTIMO_ACESSO" VARCHAR2(15 BYTE), 
	"TX_EMAIL_PMM" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCA_DATA" ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "BANCOPRECO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "BP_FINALIZADORES";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "AUDITORIA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "XPTO_CONNECT";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ADMINISTRADORES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "LICITAC?O";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ESTOQUE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "Q_BANCO_PRECOS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "BP_CADASTRO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_SEMSA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_LICITACAO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "BP_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "APLICAR_PESSOAS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CONSULTORES";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_TRAMITE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "CONTAS_PUBLICAS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "BP_MATERIAL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "WORKFLOW";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CONS_EXT";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "PATRIMONIO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "COLETORDEPONTO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_TRAM_SEMSA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PONTO_ELETRONICO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_IMPLURB";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CONS_IMPL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_TRAM_IMPL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "WOKF_EXTERNO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "ESTOQUE_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CML";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PRE_CADASTRO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PONTO_SEMEF";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ESTOQUE_KITS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "REGISTROPRECOS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "USUARIO_ADMIN";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ESTOQUE_ADMIN";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GESTAOESCOLAR";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_OPERADOR";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_ATENDENTE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_AUTORIZACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "EST_GESTOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GE_OPERADOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "R_BANCOPRECOS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_RECEBIMENTO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GE_GESTOR";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "SEMAD_LNK";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "THIAGO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "VALERIA";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "ROSANA";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "TACIANA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "MAYCON";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "JUSSARA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "VALDERI";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "SARYTA_GARCEZ";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "IWAMOTO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "BERNARDO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "ANDRE_PINHEIRO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "IVY_SA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_SOLICITANTE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_GESTOR";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "EST_RM";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_GESTOR_PASSAGEM";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "ROBSON";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "NEILA_SEMAD";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "JURIDICO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PGM";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "KEYCE_MARQUES";
 
  GRANT ALTER, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_CONSULTA";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_OPERACIONAL";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_GESTORAUXILIAR";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_GESTOR";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_OPERACIONALTCE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_ALMOXPEQUENOS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "HABITACAO_CADASTRO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_IMOVEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_IMOVEL_REL";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_CAD";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_REL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_CEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOESCOLAR_CONSULTA";
 
  GRANT ALTER, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JUR_DISTRIBUICAO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "EMANUELLE_ALVES";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JAMILE_BREVAL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_MOV_IND";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PATRIMONIO_CONS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_CONS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "TESTES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PONTOELETRONICOV2_RH";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_CONTABIL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_GESTOR_RP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_GESTOR_BP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_GESTOR_CATALOGACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_SOLICITANTE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_INVENTARIO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "HABITACAO";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_MOVI";
--------------------------------------------------------
--  DDL for Table CAMPO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."CAMPO" 
   (	"NB_CAMPO" NUMBER, 
	"ID_TABELA" NUMBER, 
	"TX_CAMPO" VARCHAR2(80 BYTE), 
	"CS_TIPO_CAMPO" NUMBER, 
	"TX_TITULO" VARCHAR2(80 BYTE), 
	"TX_DESCRICAO" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
  GRANT SELECT ON "SEMAD"."CAMPO" TO "AUDITORIA";
 
  GRANT SELECT ON "SEMAD"."CAMPO" TO "USUARIO_ADMIN";
 
  GRANT SELECT ON "SEMAD"."CAMPO" TO "SEMAD_LNK";
--------------------------------------------------------
--  DDL for Table TABELA
--------------------------------------------------------

  CREATE TABLE "SEMAD"."TABELA" 
   (	"TX_NOME" VARCHAR2(80 BYTE), 
	"ID_TABELA" NUMBER, 
	"ID_SERVIDOR" NUMBER, 
	"CS_ATUALIZACAO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
  GRANT SELECT ON "SEMAD"."TABELA" TO "AUDITORIA";
 
  GRANT SELECT ON "SEMAD"."TABELA" TO "USUARIO_ADMIN";
 
  GRANT SELECT ON "SEMAD"."TABELA" TO "SEMAD_LNK";
-- Não é possível renderizar a DLL TABLE para o objeto SEMAD.VALOR_HISTORICO com o DBMS_METADATA tentando um gerador interno.
ALTER TABLE SEMAD.VALOR_HISTORICO
ADD CONSTRAINT IDX_FK1_VALOR_HISTORICO FOREIGN KEY
(
  ID_USUARIO 
, NB_TRANSACAO_HISTORICO 
, ID_TABELA 
)
REFERENCES SEMAD.TRANSACAO_HISTORICO
(
  ID_USUARIO 
, NB_TRANSACAO_HISTORICO 
, ID_TABELA 
)
ENABLE
ALTER TABLE SEMAD.VALOR_HISTORICO
ADD CONSTRAINT IDX_FK2_VALOR_HISTORICO FOREIGN KEY
(
  ID_TABELA 
, NB_CAMPO 
)
REFERENCES SEMAD.CAMPO
(
  ID_TABELA 
, NB_CAMPO 
)
ENABLECREATE TABLE SEMAD.VALOR_HISTORICO 
(
  ID_TABELA NUMBER NOT NULL 
, NB_TRANSACAO_HISTORICO NUMBER NOT NULL 
, NB_CAMPO NUMBER NOT NULL 
, ID_USUARIO NUMBER NOT NULL 
, NB_VALOR_HISTORICO NUMBER NOT NULL 
, NB_VALOR_VARCHAR2000 VARCHAR2(4000 BYTE) 
, NB_OLD_VARCHAR2000 VARCHAR2(4000 BYTE) 
, NB_OLD_LONG_RAW BLOB 
, CONSTRAINT IDX_PK_VALOR_HISTORICO PRIMARY KEY 
  (
    NB_CAMPO 
  , ID_TABELA 
  , ID_USUARIO 
  , NB_TRANSACAO_HISTORICO 
  , NB_VALOR_HISTORICO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "PMM_DATA" 
PCTFREE 10 
INITRANS 10 
STORAGE 
( 
  INITIAL 1109393408 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
) 
LOB (NB_OLD_LONG_RAW) STORE AS SYS_LOB0000098230C00008$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  PCTVERSION 10 
  NOCACHE 
  LOGGING  
)CREATE INDEX SEMAD.IDX_FK3_VALOR_HISTORICO ON SEMAD.VALOR_HISTORICO (ID_TABELA ASC) 
LOGGING 
TABLESPACE "PMM_INDEX" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 570425344 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SEMAD.IDX_FK5_VALOR_HISTORICO ON SEMAD.VALOR_HISTORICO (ID_TABELA ASC, NB_TRANSACAO_HISTORICO ASC, NB_CAMPO ASC, ID_USUARIO ASC) 
LOGGING 
TABLESPACE "PMM_INDEX" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 995098624 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."VALOR_HISTORICO" TO "AUDITORIA";
 
  GRANT SELECT ON "SEMAD"."VALOR_HISTORICO" TO "USUARIO_ADMIN";
 
  GRANT SELECT ON "SEMAD"."VALOR_HISTORICO" TO "SEMAD_LNK";
REM INSERTING into SEMAD.ESTAGIARIO_SELECAO
SET DEFINE OFF;
Insert into SEMAD.ESTAGIARIO_SELECAO (ID_SELECAO_ESTAGIO,CS_SITUACAO,TX_MOTIVO_SITUACAO,ID_USUARIO_CADASTRO,ID_PESSOA_ESTAGIARIO,CS_ESCOLARIDADE,ID_CURSO_ESTAGIO,NB_PERIODO_ANO,CS_TURNO,ID_INSTITUICAO_ENSINO,ID_ORGAO_ESTAGIO,CS_TIPO_VAGA_ESTAGIO,TX_HORA_INICIO,TX_HORA_FINAL,ID_BOLSA_ESTAGIO,ID_PESSOA_SUPERVISOR,ID_USUARIO_ATUALIZACAO,DT_CADASTRO,DT_ATUALIZACAO,CS_CARGA_HORARIA,TX_ATIVIDADES,NB_VALOR_TRANSPORTE,TX_LOCAL_ESTAGIO,DT_INICIO,DT_FINAL) values ('77','4',null,'143','157067',null,null,null,null,null,null,null,null,null,null,null,'143',to_date('22/01/14','DD/MM/RR'),to_date('22/01/14','DD/MM/RR'),null,null,null,null,null,null);
Insert into SEMAD.ESTAGIARIO_SELECAO (ID_SELECAO_ESTAGIO,CS_SITUACAO,TX_MOTIVO_SITUACAO,ID_USUARIO_CADASTRO,ID_PESSOA_ESTAGIARIO,CS_ESCOLARIDADE,ID_CURSO_ESTAGIO,NB_PERIODO_ANO,CS_TURNO,ID_INSTITUICAO_ENSINO,ID_ORGAO_ESTAGIO,CS_TIPO_VAGA_ESTAGIO,TX_HORA_INICIO,TX_HORA_FINAL,ID_BOLSA_ESTAGIO,ID_PESSOA_SUPERVISOR,ID_USUARIO_ATUALIZACAO,DT_CADASTRO,DT_ATUALIZACAO,CS_CARGA_HORARIA,TX_ATIVIDADES,NB_VALOR_TRANSPORTE,TX_LOCAL_ESTAGIO,DT_INICIO,DT_FINAL) values ('77','5',null,'143','144120','3','121','4','3','29','1','4','10:00','17:00','41','161541','143',to_date('22/01/14','DD/MM/RR'),to_date('20/02/14','DD/MM/RR'),'3',null,null,null,null,null);
Insert into SEMAD.ESTAGIARIO_SELECAO (ID_SELECAO_ESTAGIO,CS_SITUACAO,TX_MOTIVO_SITUACAO,ID_USUARIO_CADASTRO,ID_PESSOA_ESTAGIARIO,CS_ESCOLARIDADE,ID_CURSO_ESTAGIO,NB_PERIODO_ANO,CS_TURNO,ID_INSTITUICAO_ENSINO,ID_ORGAO_ESTAGIO,CS_TIPO_VAGA_ESTAGIO,TX_HORA_INICIO,TX_HORA_FINAL,ID_BOLSA_ESTAGIO,ID_PESSOA_SUPERVISOR,ID_USUARIO_ATUALIZACAO,DT_CADASTRO,DT_ATUALIZACAO,CS_CARGA_HORARIA,TX_ATIVIDADES,NB_VALOR_TRANSPORTE,TX_LOCAL_ESTAGIO,DT_INICIO,DT_FINAL) values ('77','5',null,'143','169166','1','241','4','3','29','1','4','10:00:00','17:00:00','41','27130','143',to_date('21/01/14','DD/MM/RR'),to_date('20/02/14','DD/MM/RR'),'3',null,null,null,null,null);
Insert into SEMAD.ESTAGIARIO_SELECAO (ID_SELECAO_ESTAGIO,CS_SITUACAO,TX_MOTIVO_SITUACAO,ID_USUARIO_CADASTRO,ID_PESSOA_ESTAGIARIO,CS_ESCOLARIDADE,ID_CURSO_ESTAGIO,NB_PERIODO_ANO,CS_TURNO,ID_INSTITUICAO_ENSINO,ID_ORGAO_ESTAGIO,CS_TIPO_VAGA_ESTAGIO,TX_HORA_INICIO,TX_HORA_FINAL,ID_BOLSA_ESTAGIO,ID_PESSOA_SUPERVISOR,ID_USUARIO_ATUALIZACAO,DT_CADASTRO,DT_ATUALIZACAO,CS_CARGA_HORARIA,TX_ATIVIDADES,NB_VALOR_TRANSPORTE,TX_LOCAL_ESTAGIO,DT_INICIO,DT_FINAL) values ('83','1',null,'3265','27130',null,null,null,null,null,null,null,null,null,null,null,'3265',to_date('05/02/14','DD/MM/RR'),to_date('05/02/14','DD/MM/RR'),null,null,null,null,null,null);
Insert into SEMAD.ESTAGIARIO_SELECAO (ID_SELECAO_ESTAGIO,CS_SITUACAO,TX_MOTIVO_SITUACAO,ID_USUARIO_CADASTRO,ID_PESSOA_ESTAGIARIO,CS_ESCOLARIDADE,ID_CURSO_ESTAGIO,NB_PERIODO_ANO,CS_TURNO,ID_INSTITUICAO_ENSINO,ID_ORGAO_ESTAGIO,CS_TIPO_VAGA_ESTAGIO,TX_HORA_INICIO,TX_HORA_FINAL,ID_BOLSA_ESTAGIO,ID_PESSOA_SUPERVISOR,ID_USUARIO_ATUALIZACAO,DT_CADASTRO,DT_ATUALIZACAO,CS_CARGA_HORARIA,TX_ATIVIDADES,NB_VALOR_TRANSPORTE,TX_LOCAL_ESTAGIO,DT_INICIO,DT_FINAL) values ('77','3','asdvpbapvibe apvfvbpaeirbg pavfbpib pib piygpibçg','143','166454',null,null,null,null,null,null,null,null,null,null,null,'143',to_date('21/01/14','DD/MM/RR'),to_date('23/01/14','DD/MM/RR'),null,null,null,null,null,null);
Insert into SEMAD.ESTAGIARIO_SELECAO (ID_SELECAO_ESTAGIO,CS_SITUACAO,TX_MOTIVO_SITUACAO,ID_USUARIO_CADASTRO,ID_PESSOA_ESTAGIARIO,CS_ESCOLARIDADE,ID_CURSO_ESTAGIO,NB_PERIODO_ANO,CS_TURNO,ID_INSTITUICAO_ENSINO,ID_ORGAO_ESTAGIO,CS_TIPO_VAGA_ESTAGIO,TX_HORA_INICIO,TX_HORA_FINAL,ID_BOLSA_ESTAGIO,ID_PESSOA_SUPERVISOR,ID_USUARIO_ATUALIZACAO,DT_CADASTRO,DT_ATUALIZACAO,CS_CARGA_HORARIA,TX_ATIVIDADES,NB_VALOR_TRANSPORTE,TX_LOCAL_ESTAGIO,DT_INICIO,DT_FINAL) values ('85','1',null,'143','27130',null,null,null,null,null,null,null,null,null,null,null,'143',to_date('21/02/14','DD/MM/RR'),to_date('21/02/14','DD/MM/RR'),null,null,null,null,null,null);
Insert into SEMAD.ESTAGIARIO_SELECAO (ID_SELECAO_ESTAGIO,CS_SITUACAO,TX_MOTIVO_SITUACAO,ID_USUARIO_CADASTRO,ID_PESSOA_ESTAGIARIO,CS_ESCOLARIDADE,ID_CURSO_ESTAGIO,NB_PERIODO_ANO,CS_TURNO,ID_INSTITUICAO_ENSINO,ID_ORGAO_ESTAGIO,CS_TIPO_VAGA_ESTAGIO,TX_HORA_INICIO,TX_HORA_FINAL,ID_BOLSA_ESTAGIO,ID_PESSOA_SUPERVISOR,ID_USUARIO_ATUALIZACAO,DT_CADASTRO,DT_ATUALIZACAO,CS_CARGA_HORARIA,TX_ATIVIDADES,NB_VALOR_TRANSPORTE,TX_LOCAL_ESTAGIO,DT_INICIO,DT_FINAL) values ('77','5',null,'143','27130','3','221','4','3','29','1','4','10:00','16:00','41','157067','143',to_date('21/01/14','DD/MM/RR'),to_date('20/02/14','DD/MM/RR'),'3','A) ATENDIMENTO AO PÚBLICO 
B) AUXÍLIO / SUPORTE NO PROCESSO DE ATENDIMENTO 
C) AUXILIAR / COOPERAR / NO ATENDIMENTO TELEFÔNICO PRESTANDO INFORMAÇÕES SOBRE OS SERVIÇOS DA EMPRESA 
D) LEVANTAMENTO','1234,56','LKNJHBHHÍH',to_date('28/01/14','DD/MM/RR'),to_date('29/06/15','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index ESTAGIARIO_SELECAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."ESTAGIARIO_SELECAO_PK" ON "SEMAD"."ESTAGIARIO_SELECAO" ("ID_SELECAO_ESTAGIO", "ID_PESSOA_ESTAGIARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index ESTAGIARIO_SELECAO_INDEX1
--------------------------------------------------------

  CREATE INDEX "SEMAD"."ESTAGIARIO_SELECAO_INDEX1" ON "SEMAD"."ESTAGIARIO_SELECAO" ("ID_SELECAO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF4ESTAGIARIO_SELECAO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF4ESTAGIARIO_SELECAO" ON "SEMAD"."ESTAGIARIO_SELECAO" ("ID_USUARIO_CADASTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  Constraints for Table ESTAGIARIO_SELECAO
--------------------------------------------------------

  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" ADD CONSTRAINT "ESTAGIARIO_SELECAO_PK" PRIMARY KEY ("ID_SELECAO_ESTAGIO", "ID_PESSOA_ESTAGIARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA"  ENABLE;
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" MODIFY ("ID_SELECAO_ESTAGIO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" MODIFY ("CS_SITUACAO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" MODIFY ("ID_USUARIO_CADASTRO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" MODIFY ("ID_PESSOA_ESTAGIARIO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" MODIFY ("ID_USUARIO_ATUALIZACAO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" MODIFY ("DT_CADASTRO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" MODIFY ("DT_ATUALIZACAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ESTAGIARIO_SELECAO
--------------------------------------------------------

  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" ADD CONSTRAINT "ESTAGIARIO_SELECAO_BOLSA__FK1" FOREIGN KEY ("ID_BOLSA_ESTAGIO")
	  REFERENCES "SEMAD"."BOLSA_ESTAGIO" ("ID_BOLSA_ESTAGIO") ENABLE;
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" ADD CONSTRAINT "ESTAGIARIO_SELECAO_CURSO__FK1" FOREIGN KEY ("ID_CURSO_ESTAGIO")
	  REFERENCES "SEMAD"."CURSO_ESTAGIO" ("ID_CURSO_ESTAGIO") ENABLE;
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" ADD CONSTRAINT "ESTAGIARIO_SELECAO_INSTIT_FK1" FOREIGN KEY ("ID_INSTITUICAO_ENSINO")
	  REFERENCES "SEMAD"."INSTITUICAO_ENSINO" ("ID_INSTITUICAO_ENSINO") ENABLE;
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" ADD CONSTRAINT "ESTAGIARIO_SELECAO_ORGAO__FK1" FOREIGN KEY ("ID_ORGAO_ESTAGIO")
	  REFERENCES "SEMAD"."ORGAO_ESTAGIO" ("ID_ORGAO_ESTAGIO") ENABLE;
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" ADD CONSTRAINT "ESTAGIARIO_SELECAO_SUPERV_FK1" FOREIGN KEY ("ID_PESSOA_SUPERVISOR")
	  REFERENCES "SEMAD"."SUPERVISOR_ESTAGIO" ("ID_PESSOA_SUPERVISOR") ENABLE;
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" ADD CONSTRAINT "ESTAGIARIO_SELECAO_TIPO_V_FK1" FOREIGN KEY ("CS_TIPO_VAGA_ESTAGIO")
	  REFERENCES "SEMAD"."TIPO_VAGA_ESTAGIO" ("CS_TIPO_VAGA_ESTAGIO") ENABLE;
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" ADD CONSTRAINT "ESTAGIARIO_SELECAO_USUARI_FK1" FOREIGN KEY ("ID_USUARIO_ATUALIZACAO")
	  REFERENCES "SEMAD"."USUARIO" ("ID_USUARIO") ENABLE;
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" ADD CONSTRAINT "PESSOA_ESTAGIARIO_SELECAO_FK1" FOREIGN KEY ("ID_PESSOA_ESTAGIARIO")
	  REFERENCES "SEMAD"."ESTAGIARIO" ("ID_PESSOA_ESTAGIARIO") ENABLE;
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" ADD FOREIGN KEY ("ID_USUARIO_CADASTRO")
	  REFERENCES "SEMAD"."USUARIO" ("ID_USUARIO") ENABLE;
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_SELECAO" ADD FOREIGN KEY ("ID_SELECAO_ESTAGIO")
	  REFERENCES "SEMAD"."SELECAO_ESTAGIO" ("ID_SELECAO_ESTAGIO") ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_AVS_IUD_ESTAGIARIO_SELECAO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SEMAD"."T_AVS_IUD_ESTAGIARIO_SELECAO" 
  AFTER
  INSERT OR DELETE OR UPDATE
  on SEMAD.Estagiario_Selecao
  REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW

declare
  pnb_Valor_Historico number;
  pID_Tabela number;
  pnb_Campo number;
  pnb_Transacao number;
  pID_Usuario number;
  pcs_evento number;
begin
  select id_usuario into pid_usuario
  from usuario
  where tx_login = user;
  if inserting then
     pcs_evento := 1;
  else
     if updating then
        pcs_evento := 2;
     else
        pcs_evento := 3;
     end if;
  end if;
  pID_Tabela := F_AVS_Busca_Tabela('ESTAGIARIO_SELECAO');
  pnb_Transacao := F_AVS_Cadastra_Transacao(pID_Tabela,pID_usuario,pcs_evento );
  -- insere valor do campo ID_Selecao_Estagio --
  pnb_Campo := F_AVS_Busca_Campo('ID_SELECAO_ESTAGIO',pID_Tabela,'INTEGER');
  pnb_Valor_Historico := F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Selecao_Estagio,
          :old.ID_Selecao_Estagio);

-- insere valor do campo ID_Recrutamento_Estagio --
  pnb_Campo := F_AVS_Busca_Campo('ID_RECRUTAMENTO_ESTAGIO',pID_Tabela,'INTEGER');
  pnb_Valor_Historico := F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Recrutamento_Estagio,
          :old.ID_Recrutamento_Estagio);

-- insere valor do campo nb_Vagas_Recrutamento --
  pnb_Campo := F_AVS_Busca_Campo('NB_VAGAS_RECRUTAMENTO',pID_Tabela,'INTEGER');
  pnb_Valor_Historico := F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.nb_Vagas_Recrutamento,
          :old.nb_Vagas_Recrutamento);

-- insere valor do campo nb_Candidato --
  pnb_Campo := F_AVS_Busca_Campo('NB_CANDIDATO',pID_Tabela,'INTEGER');
  pnb_Valor_Historico := F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.nb_Candidato,
          :old.nb_Candidato);

-- insere valor do campo ID_Usuario_Selecionador --
  pnb_Campo := F_AVS_Busca_Campo('ID_USUARIO_SELECIONADOR',pID_Tabela,'NUMBER');
  pnb_Valor_Historico := F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Usuario_Selecionador,
          :old.ID_Usuario_Selecionador);

-- insere valor do campo cs_Situacao --
  pnb_Campo := F_AVS_Busca_Campo('CS_SITUACAO',pID_Tabela,'INTEGER');
  pnb_Valor_Historico := F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.cs_Situacao,
          :old.cs_Situacao);

-- insere valor do campo tx_Motivo_Situacao --
  pnb_Campo := F_AVS_Busca_Campo('TX_MOTIVO_SITUACAO',pID_Tabela,'VARCHAR2(255)');
  pnb_Valor_Historico := F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.tx_Motivo_Situacao,
          :old.tx_Motivo_Situacao);

-- insere valor do campo ID_Usuario --
  pnb_Campo := F_AVS_Busca_Campo('ID_USUARIO',pID_Tabela,'NUMBER');
  pnb_Valor_Historico := F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Usuario,
          :old.ID_Usuario);

-- insere valor do campo dt_Agendamento --
  pnb_Campo := F_AVS_Busca_Campo('DT_AGENDAMENTO',pID_Tabela,'DATE');
  pnb_Valor_Historico := F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.dt_Agendamento,
          :old.dt_Agendamento);

-- insere valor do campo dt_Realizacao --
  pnb_Campo := F_AVS_Busca_Campo('DT_REALIZACAO',pID_Tabela,'DATE');
  pnb_Valor_Historico := F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.dt_Realizacao,
          :old.dt_Realizacao);


end; --

/
ALTER TRIGGER "SEMAD"."T_AVS_IUD_ESTAGIARIO_SELECAO" DISABLE;
--------------------------------------------------------
--  DDL for Function F_AVS_BUSCA_CAMPO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SEMAD"."F_AVS_BUSCA_CAMPO" 
  (ptx_campo IN campo.tx_campo%type,
   pid_tabela IN tabela.id_tabela%type,
   ptx_tipo_campo IN tipo_campo.tx_tipo_campo%type)
RETURN  campo.nb_campo%type IS pnb_campo campo.nb_campo%type;

   pid_servidor   number;
   numregs        number;
   pcs_tipo_campo number;
BEGIN
    pnb_campo := 0;
    numregs := 0;
    
    select max(nb_campo) into numregs
    from campo
    where tx_campo = ptx_campo and
          id_tabela = pid_tabela;
     
    if numregs > 0 then
      select nb_campo into pnb_campo
      from campo
      where tx_campo = ptx_campo and
            id_tabela = pid_tabela;
    else
      select max(id_servidor) into pid_servidor
      from parametros_default;
      pcs_tipo_campo := F_Busca_Tipo_Campo(ptx_tipo_campo,pid_servidor);
      pnb_campo := F_G_PK_campo(pid_tabela);
      insert into campo (id_tabela, nb_campo, tx_campo,cs_tipo_campo)
             values (pid_tabela, pnb_campo, ptx_campo,pcs_tipo_campo);
    end if;

    RETURN pnb_campo;
END;


-- End of DDL script for F_AVS_BUSCA_CAMPO

/
--------------------------------------------------------
--  DDL for Function F_AVS_BUSCA_TABELA
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SEMAD"."F_AVS_BUSCA_TABELA" 
  (ptx_tabela IN Tabela.tx_nome%type)
RETURN  Tabela.ID_Tabela%type IS Pid_Tabela Tabela.ID_Tabela%type;
   pid_servidor number;
   numregs number;
BEGIN
    numregs := 0;
    select count(id_tabela) into numregs
    from tabela
    where tx_nome = ptx_tabela;
    if numregs <> 0 then
       select id_tabela into Pid_Tabela
       from tabela
       where tx_nome = ptx_tabela;
    else
      pid_tabela := F_G_PK_Tabela();
      select max(id_servidor) into pid_servidor
           from parametros_default;
      insert into tabela (id_tabela, tx_nome, id_servidor, cs_atualizacao)
             values (pid_tabela, ptx_tabela, pid_servidor,2);
    end if;
    RETURN Pid_Tabela;
END;


-- End of DDL script for F_AVS_BUSCA_TABELA

/
--------------------------------------------------------
--  DDL for Function F_AVS_CADASTRA_TRANSACAO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SEMAD"."F_AVS_CADASTRA_TRANSACAO" 
  ( pID_Tabela IN Tabela.ID_Tabela%type,
    pID_Usuario IN Usuario.ID_Usuario%type,
    pcs_evento IN number)
  RETURN  number IS pnb_Transacao number;
BEGIN
  pnb_transacao := F_G_PK_transacao_historico(pid_usuario,pid_tabela);
  insert into transacao_historico (id_tabela, id_usuario, nb_transacao_historico, dt_transacao_historico, cs_evento)
  values (pid_tabela, pid_usuario, pnb_transacao, sysdate, pcs_evento);
  RETURN pnb_transacao;
END; -- F_AVS_CADASTRA_TRANSACAO

-- End of DDL script for F_AVS_CADASTRA_TRANSACAO

/
--------------------------------------------------------
--  DDL for Function F_G_PK_VALOR_HISTORICO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SEMAD"."F_G_PK_VALOR_HISTORICO" 
(PID_TABELA NUMBER,PNB_TRANSACAO_HISTORICO NUMBER,PNB_CAMPO NUMBER,PID_USUARIO NUMBER)
RETURN NUMBER IS V_N_VALOR_HISTORICO NUMBER;
BEGIN
   SELECT COUNT (*) INTO  V_N_VALOR_HISTORICO
   FROM VALOR_HISTORICO
   WHERE(ID_TABELA = PID_TABELA AND NB_TRANSACAO_HISTORICO = PNB_TRANSACAO_HISTORICO AND NB_CAMPO = PNB_CAMPO AND ID_USUARIO = PID_USUARIO );
    IF V_N_VALOR_HISTORICO = 0 THEN
        V_N_VALOR_HISTORICO := 1;
    ELSE
        SELECT MAX(NB_VALOR_HISTORICO) + 1
        INTO V_N_VALOR_HISTORICO
        FROM VALOR_HISTORICO
        WHERE (ID_TABELA = PID_TABELA AND NB_TRANSACAO_HISTORICO = PNB_TRANSACAO_HISTORICO AND NB_CAMPO = PNB_CAMPO AND ID_USUARIO = PID_USUARIO );
     END IF;
     RETURN V_N_VALOR_HISTORICO;
END; -- F_G_PK_VALOR_HISTORICO

/
