--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Março-21-2014   
--------------------------------------------------------
DROP TABLE "SEMAD"."ESTAGIARIO_CONTRATO" cascade constraints;
--------------------------------------------------------
--  DDL for Table ESTAGIARIO_CONTRATO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."ESTAGIARIO_CONTRATO" 
   (	"ID_CONTRATO" NUMBER, 
	"NB_ESTAGIARIO_CONTRATO" NUMBER, 
	"DT_CADASTRO" DATE, 
	"DT_ATUALIZACAO" DATE, 
	"ID_USUARIO_CADASTRO" NUMBER, 
	"ID_USUARIO_ATUALIZACAO" NUMBER, 
	"NB_VIGENCIA" NUMBER, 
	"DT_INICIO_PRORROGACAO" DATE, 
	"DT_FIM_PRORROGACAO" DATE, 
	"DT_INICIO_RECESSO" DATE, 
	"DT_FIM_RECESSO" DATE, 
	"NB_JORNADA" NUMBER, 
	"DT_INICIO_JORNADA" DATE, 
	"TX_INICIO_HORARIO" VARCHAR2(20 BYTE), 
	"TX_FIM_HORARIO" VARCHAR2(20 BYTE), 
	"NB_BOLSA" NUMBER, 
	"DT_INICIO_PAG_BOLSA" DATE, 
	"NB_VALOR_BOLSA" NUMBER, 
	"NB_SUPERVISOR" NUMBER, 
	"ID_PESSOA_SUPERVISOR" VARCHAR2(20 BYTE), 
	"NB_ALTERACOES" NUMBER, 
	"TX_OUTRAS_ALTERACOES" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
REM INSERTING into SEMAD.ESTAGIARIO_CONTRATO
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table ESTAGIARIO_CONTRATO
--------------------------------------------------------

  ALTER TABLE "SEMAD"."ESTAGIARIO_CONTRATO" ADD CONSTRAINT "ESTAGIARIO_CONTRATO_PK" PRIMARY KEY ("ID_CONTRATO", "NB_ESTAGIARIO_CONTRATO") DISABLE;
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_CONTRATO" MODIFY ("ID_CONTRATO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_CONTRATO" MODIFY ("NB_ESTAGIARIO_CONTRATO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_CONTRATO" MODIFY ("DT_CADASTRO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_CONTRATO" MODIFY ("DT_ATUALIZACAO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_CONTRATO" MODIFY ("ID_USUARIO_CADASTRO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ESTAGIARIO_CONTRATO" MODIFY ("ID_USUARIO_ATUALIZACAO" NOT NULL ENABLE);
