--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Março-21-2014   
--------------------------------------------------------
DROP TABLE "SEMAD"."ESTAGIARIO" cascade constraints;
DROP TABLE "SEMAD"."FUNCIONARIO_PE" cascade constraints;
DROP TABLE "SEMAD"."PESSOA_FISICA" cascade constraints;
DROP TABLE "SEMAD"."CAMPO" cascade constraints;
DROP TABLE "SEMAD"."TABELA" cascade constraints;
DROP TABLE "SEMAD"."USUARIO" cascade constraints;
DROP TABLE "SEMAD"."VALOR_HISTORICO" cascade constraints;
--------------------------------------------------------
--  DDL for Table ESTAGIARIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."ESTAGIARIO" 
   (	"ID_PESSOA_ESTAGIARIO" NUMBER(*,0), 
	"ID_PESSOA_FUNCIONARIO" NUMBER(*,0), 
	"NB_FUNCIONARIO" NUMBER(*,0), 
	"TX_CEP" VARCHAR2(20 BYTE), 
	"TX_ENDERECO" VARCHAR2(255 BYTE), 
	"NB_NUMERO" NUMBER, 
	"TX_COMPLEMENTO" VARCHAR2(255 BYTE), 
	"TX_BAIRRO" VARCHAR2(100 BYTE), 
	"TX_AGENCIA" VARCHAR2(20 BYTE), 
	"TX_CONTA_CORRENTE" VARCHAR2(20 BYTE), 
	"TX_CONTATO" VARCHAR2(180 BYTE), 
	"TX_EMAIL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
 

   COMMENT ON COLUMN "SEMAD"."ESTAGIARIO"."ID_PESSOA_ESTAGIARIO" IS 'É o identificador único das pessoa físicas.';
 
   COMMENT ON COLUMN "SEMAD"."ESTAGIARIO"."ID_PESSOA_FUNCIONARIO" IS 'É o identificador único das pessoa físicas.';
-- Não é possível renderizar a DLL TABLE para o objeto SEMAD.FUNCIONARIO_PE com o DBMS_METADATA tentando um gerador interno.
ALTER TABLE SEMAD.FUNCIONARIO_PE
ADD CONSTRAINT SYS_C0030522 FOREIGN KEY
(
  CS_TIPO_FUNCIONARIO_PE 
)
REFERENCES SEMAD.TIPO_FUNCIONARIO_PE
(
  CS_TIPO_FUNCIONARIO_PE 
)
ENABLE
ALTER TABLE SEMAD.FUNCIONARIO_PE
ADD CONSTRAINT SYS_C0030523 FOREIGN KEY
(
  CS_SITUACAO_FUNCIONARIO 
)
REFERENCES SEMAD.SITUACAO_FUNCIONARIO
(
  CS_SITUACAO_FUNCIONARIO 
)
ENABLE
ALTER TABLE SEMAD.FUNCIONARIO_PE
ADD CONSTRAINT SYS_C0030524 FOREIGN KEY
(
  ID_PESSOA_FUNCIONARIO 
)
REFERENCES SEMAD.PESSOA_FISICA
(
  ID_PESSOA 
)
ENABLE
ALTER TABLE SEMAD.FUNCIONARIO_PE
ADD CONSTRAINT SYS_C0030525 FOREIGN KEY
(
  ID_UNIDADE_GESTORA 
)
REFERENCES SEMAD.UNID_GESTORA_PESSOA_PE
(
  ID_UNIDADE_GESTORA 
)
ENABLECREATE TABLE SEMAD.FUNCIONARIO_PE 
(
  ID_UNIDADE_GESTORA NUMBER(*, 0) NOT NULL 
, ID_PESSOA_FUNCIONARIO NUMBER(*, 0) NOT NULL 
, DT_CADASTRO DATE NOT NULL 
, TX_NOME_GUERRA VARCHAR2(80 BYTE) NOT NULL 
, NB_FUNCIONARIO NUMBER(*, 0) NOT NULL 
, BL_FOTO BLOB 
, BL_DIGITAL BLOB 
, CS_SITUACAO_FUNCIONARIO NUMBER(*, 0) NOT NULL 
, CS_TIPO_FUNCIONARIO_PE NUMBER(*, 0) NOT NULL 
, DT_ATUALIZACAO DATE NOT NULL 
, TX_FIR VARCHAR2(2000 BYTE) 
, CS_TIPO_REG_PONTO NUMBER(*, 0) 
, CONSTRAINT SYS_C0030521 PRIMARY KEY 
  (
    ID_PESSOA_FUNCIONARIO 
  , NB_FUNCIONARIO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "PMM_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
) 
LOB (BL_FOTO) STORE AS SYS_LOB0000105545C00006$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING  
) 	
LOB (BL_DIGITAL) STORE AS SYS_LOB0000105545C00007$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING  
)CREATE INDEX SEMAD.XIF1FUNCIONARIO_PE ON SEMAD.FUNCIONARIO_PE (ID_UNIDADE_GESTORA ASC) 
LOGGING 
TABLESPACE "PMM_DATA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SEMAD.XIF2FUNCIONARIO_PE ON SEMAD.FUNCIONARIO_PE (ID_PESSOA_FUNCIONARIO ASC) 
LOGGING 
TABLESPACE "PMM_DATA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SEMAD.XIF3FUNCIONARIO_PE ON SEMAD.FUNCIONARIO_PE (CS_SITUACAO_FUNCIONARIO ASC) 
LOGGING 
TABLESPACE "PMM_DATA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SEMAD.XIF4FUNCIONARIO_PE ON SEMAD.FUNCIONARIO_PE (CS_TIPO_FUNCIONARIO_PE ASC) 
LOGGING 
TABLESPACE "PMM_DATA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE UNIQUE INDEX SEMAD.XPKFUNCIONARIO_PE ON SEMAD.FUNCIONARIO_PE (ID_PESSOA_FUNCIONARIO ASC, NB_FUNCIONARIO ASC) 
LOGGING 
TABLESPACE "PMM_DATA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)COMMENT ON COLUMN SEMAD.FUNCIONARIO_PE.ID_PESSOA_FUNCIONARIO IS 'É o identificador único das pessoa físicas.';
COMMENT ON COLUMN SEMAD.FUNCIONARIO_PE.DT_CADASTRO IS 'Data de cadastro do funcionário.';
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_PE" TO "PONTOELETRONICOV2";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_PE" TO "PONTO2";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."FUNCIONARIO_PE" TO "WILMA_SILVA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."FUNCIONARIO_PE" TO "PONTOELETRONICOV2_CONS";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."FUNCIONARIO_PE" TO "LILIANE_FIGUEIREDO";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."FUNCIONARIO_PE" TO "JURIDICO_CONSULTA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."FUNCIONARIO_PE" TO "JURIDICO_OPERACIONAL";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."FUNCIONARIO_PE" TO "JURIDICO_GESTORAUXILIAR";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."FUNCIONARIO_PE" TO "JURIDICO_GESTOR";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."FUNCIONARIO_PE" TO "JURIDICO_OPERACIONALTCE";
 
  GRANT SELECT ON "SEMAD"."FUNCIONARIO_PE" TO "GUEST_RHUNIVERSAL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_PE" TO "IRP";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."FUNCIONARIO_PE" TO "PONTOELETRONICOV2_FISCALIZAC";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_PE" TO "PONTOELETRONICOV2_RH";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."FUNCIONARIO_PE" TO "IRP_GESTOR_BP";
-- Não é possível renderizar a DLL TABLE para o objeto SEMAD.PESSOA_FISICA com o DBMS_METADATA tentando um gerador interno.
ALTER TABLE SEMAD.PESSOA_FISICA
ADD CONSTRAINT IDX_FK1_PESSOA_FISICA FOREIGN KEY
(
  ID_LOCALIDADE_NATAL 
)
REFERENCES SEMAD.LOCALIDADE
(
  ID_LOCALIDADE 
)
ENABLE
ALTER TABLE SEMAD.PESSOA_FISICA
ADD CONSTRAINT IDX_FK2_PESSOA_FISICA FOREIGN KEY
(
  ID_UF_REG_NASCIMENTO 
)
REFERENCES SEMAD.UF
(
  ID_UF 
)
DISABLE
ALTER TABLE SEMAD.PESSOA_FISICA
ADD CONSTRAINT IDX_FK3_PESSOA_FISICA FOREIGN KEY
(
  ID_UF_RG 
)
REFERENCES SEMAD.UF
(
  ID_UF 
)
ENABLECREATE TABLE SEMAD.PESSOA_FISICA 
(
  ID_PESSOA NUMBER NOT NULL 
, NB_CPF VARCHAR2(80 BYTE) DEFAULT 00000000000000 
, NB_RG VARCHAR2(80 BYTE) 
, CS_SEXO NUMBER 
, DT_ATUALIZACAO DATE 
, CS_TIPO NUMBER 
, TX_ORGAO_EMISSOR VARCHAR2(80 BYTE) 
, ID_UF_RG VARCHAR2(80 BYTE) 
, DT_NASCIMENTO DATE 
, NB_REG_NASCIMENTO VARCHAR2(80 BYTE) 
, TX_CARTORIO_REG_NASC VARCHAR2(80 BYTE) 
, TX_LIVRO_CARTORIO VARCHAR2(20 BYTE) 
, TX_FOLHA_LIV_CART VARCHAR2(20 BYTE) 
, ID_UF_REG_NASCIMENTO VARCHAR2(80 BYTE) 
, ID_LOCALIDADE_NATAL NUMBER 
, NB_COD_CERT_MILITAR VARCHAR2(80 BYTE) 
, NB_CERT_MILITAR VARCHAR2(80 BYTE) 
, NB_PISPASEP VARCHAR2(80 BYTE) 
, NB_TITULO_ELEITOR VARCHAR2(80 BYTE) 
, NB_ZONA_TITULO VARCHAR2(80 BYTE) 
, NB_SECAO_TITULO VARCHAR2(80 BYTE) 
, LR_FOTO LONG RAW 
, ID_LOCALIDADE_CARTORIO NUMBER 
, DT_EMISSAO_CERTIDAO DATE 
, CS_TIPO_CERTIDAO NUMBER 
, DT_EMISSAO DATE 
, CS_ETNIA NUMBER 
, ID_MAE NUMBER 
, ID_PAI NUMBER 
, NB_CODIGO_INEP NUMBER 
, NB_CODIGO_CENTRAL NUMBER 
, LR_FOTO_PNG BLOB 
, CONSTRAINT IDX_PK_PESSOA_FISICA PRIMARY KEY 
  (
    ID_PESSOA 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "PMM_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
) 
PARALLEL 
LOB (LR_FOTO_PNG) STORE AS SYS_LOB0000097424C00032$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  NOLOGGING  
)CREATE INDEX SEMAD.IDX_FK2_PESSOA_FISICA ON SEMAD.PESSOA_FISICA (ID_UF_REG_NASCIMENTO) 
LOGGING 
TABLESPACE "PMM_INDEX" 
PCTFREE 30 
INITRANS 10 
STORAGE 
( 
  INITIAL 131072 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "BANCOPRECO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "BP_FINALIZADORES";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "ADMINISTRADORES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "LICITAC?O";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "FORNECEDORES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "ZOPE_ROLE";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_SEMSA";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_LICITACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "BP_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "APLICAR_PESSOAS";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_CONSULTORES";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_TRAMITE";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_CONS_EXT";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "COLETORDEPONTO";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_TRAM_SEMSA";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "FORNEC_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PONTO_ELETRONICO";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_IMPLURB";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_CONS_IMPL";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_TRAM_IMPL";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_CML";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "LICITACAO_CONS";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PONTO_SEMEF";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "USUARIO_ADMIN";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "PONTOELETRONICOV2";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PONTO_SEMASC";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "GESTAOCONTASPUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "GESTAOESCOLAR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "GE_OPERADOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "R_BANCOPRECOS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "GE_GESTOR";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "SEMAD_LNK";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "ZOPEPROD";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PEDRO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA_FISICA" TO "ANTONIO_SOUSA";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PONTO2";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "VOYAGE_SOLICITANTE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "VOYAGE_GESTOR";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA_FISICA" TO "VANESSA_MACIEL";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA_FISICA" TO "IONNE_PEREIRA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA_FISICA" TO "PONTOELETRONICOV2_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "PONTO_SMTU";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "GESTAOESCOLAR_CONSULTA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "VOYAGE_CONS";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "GESTAOCONTASPUBLICAS_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "IRP";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "TESTES";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA_FISICA" TO "PONTOELETRONICOV2_FISCALIZAC";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "PONTOELETRONICOV2_RH";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "GESTAOESPM";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "IRP_GESTOR_RP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "IRP_GESTOR_CATALOGACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "IRP_SOLICITANTE";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "HABITACAO";
--------------------------------------------------------
--  DDL for Table CAMPO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."CAMPO" 
   (	"NB_CAMPO" NUMBER, 
	"ID_TABELA" NUMBER, 
	"TX_CAMPO" VARCHAR2(80 BYTE), 
	"CS_TIPO_CAMPO" NUMBER, 
	"TX_TITULO" VARCHAR2(80 BYTE), 
	"TX_DESCRICAO" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
  GRANT SELECT ON "SEMAD"."CAMPO" TO "AUDITORIA";
 
  GRANT SELECT ON "SEMAD"."CAMPO" TO "USUARIO_ADMIN";
 
  GRANT SELECT ON "SEMAD"."CAMPO" TO "SEMAD_LNK";
--------------------------------------------------------
--  DDL for Table TABELA
--------------------------------------------------------

  CREATE TABLE "SEMAD"."TABELA" 
   (	"TX_NOME" VARCHAR2(80 BYTE), 
	"ID_TABELA" NUMBER, 
	"ID_SERVIDOR" NUMBER, 
	"CS_ATUALIZACAO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
  GRANT SELECT ON "SEMAD"."TABELA" TO "AUDITORIA";
 
  GRANT SELECT ON "SEMAD"."TABELA" TO "USUARIO_ADMIN";
 
  GRANT SELECT ON "SEMAD"."TABELA" TO "SEMAD_LNK";
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."USUARIO" 
   (	"ID_USUARIO" NUMBER(5,0), 
	"TX_LOGIN" VARCHAR2(20 BYTE), 
	"CS_SITUACAO" NUMBER DEFAULT 0, 
	"TX_CONFIGURACAO" LONG, 
	"ID_PESSOA_FUNCIONARIO" NUMBER, 
	"TX_MOTIVO_SITUACAO" VARCHAR2(200 BYTE), 
	"ID_UNIDADE_GESTORA" NUMBER, 
	"DT_ULTIMO_ACESSO" DATE, 
	"TX_IP_ULTIMO_ACESSO" VARCHAR2(15 BYTE), 
	"TX_EMAIL_PMM" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCA_DATA" ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "BANCOPRECO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "BP_FINALIZADORES";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "AUDITORIA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "XPTO_CONNECT";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ADMINISTRADORES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "LICITAC?O";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ESTOQUE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "Q_BANCO_PRECOS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "BP_CADASTRO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_SEMSA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_LICITACAO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "BP_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "APLICAR_PESSOAS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CONSULTORES";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_TRAMITE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "CONTAS_PUBLICAS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "BP_MATERIAL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "WORKFLOW";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CONS_EXT";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "PATRIMONIO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "COLETORDEPONTO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_TRAM_SEMSA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PONTO_ELETRONICO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_IMPLURB";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CONS_IMPL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_TRAM_IMPL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "WOKF_EXTERNO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "ESTOQUE_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CML";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PRE_CADASTRO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PONTO_SEMEF";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ESTOQUE_KITS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "REGISTROPRECOS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "USUARIO_ADMIN";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ESTOQUE_ADMIN";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GESTAOESCOLAR";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_OPERADOR";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_ATENDENTE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_AUTORIZACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "EST_GESTOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GE_OPERADOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "R_BANCOPRECOS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_RECEBIMENTO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GE_GESTOR";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "SEMAD_LNK";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "THIAGO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "VALERIA";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "ROSANA";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "TACIANA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "MAYCON";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "JUSSARA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "VALDERI";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "SARYTA_GARCEZ";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "IWAMOTO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "BERNARDO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "ANDRE_PINHEIRO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "IVY_SA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_SOLICITANTE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_GESTOR";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "EST_RM";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_GESTOR_PASSAGEM";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "ROBSON";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "NEILA_SEMAD";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "JURIDICO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PGM";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "KEYCE_MARQUES";
 
  GRANT ALTER, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_CONSULTA";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_OPERACIONAL";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_GESTORAUXILIAR";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_GESTOR";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_OPERACIONALTCE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_ALMOXPEQUENOS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "HABITACAO_CADASTRO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_IMOVEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_IMOVEL_REL";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_CAD";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_REL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_CEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOESCOLAR_CONSULTA";
 
  GRANT ALTER, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JUR_DISTRIBUICAO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "EMANUELLE_ALVES";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JAMILE_BREVAL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_MOV_IND";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PATRIMONIO_CONS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_CONS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "TESTES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PONTOELETRONICOV2_RH";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_CONTABIL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_GESTOR_RP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_GESTOR_BP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_GESTOR_CATALOGACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_SOLICITANTE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_INVENTARIO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "HABITACAO";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_MOVI";
-- Não é possível renderizar a DLL TABLE para o objeto SEMAD.VALOR_HISTORICO com o DBMS_METADATA tentando um gerador interno.
ALTER TABLE SEMAD.VALOR_HISTORICO
ADD CONSTRAINT IDX_FK1_VALOR_HISTORICO FOREIGN KEY
(
  ID_USUARIO 
, NB_TRANSACAO_HISTORICO 
, ID_TABELA 
)
REFERENCES SEMAD.TRANSACAO_HISTORICO
(
  ID_USUARIO 
, NB_TRANSACAO_HISTORICO 
, ID_TABELA 
)
ENABLE
ALTER TABLE SEMAD.VALOR_HISTORICO
ADD CONSTRAINT IDX_FK2_VALOR_HISTORICO FOREIGN KEY
(
  ID_TABELA 
, NB_CAMPO 
)
REFERENCES SEMAD.CAMPO
(
  ID_TABELA 
, NB_CAMPO 
)
ENABLECREATE TABLE SEMAD.VALOR_HISTORICO 
(
  ID_TABELA NUMBER NOT NULL 
, NB_TRANSACAO_HISTORICO NUMBER NOT NULL 
, NB_CAMPO NUMBER NOT NULL 
, ID_USUARIO NUMBER NOT NULL 
, NB_VALOR_HISTORICO NUMBER NOT NULL 
, NB_VALOR_VARCHAR2000 VARCHAR2(4000 BYTE) 
, NB_OLD_VARCHAR2000 VARCHAR2(4000 BYTE) 
, NB_OLD_LONG_RAW BLOB 
, CONSTRAINT IDX_PK_VALOR_HISTORICO PRIMARY KEY 
  (
    NB_CAMPO 
  , ID_TABELA 
  , ID_USUARIO 
  , NB_TRANSACAO_HISTORICO 
  , NB_VALOR_HISTORICO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "PMM_DATA" 
PCTFREE 10 
INITRANS 10 
STORAGE 
( 
  INITIAL 1109393408 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
) 
LOB (NB_OLD_LONG_RAW) STORE AS SYS_LOB0000098230C00008$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  PCTVERSION 10 
  NOCACHE 
  LOGGING  
)CREATE INDEX SEMAD.IDX_FK3_VALOR_HISTORICO ON SEMAD.VALOR_HISTORICO (ID_TABELA ASC) 
LOGGING 
TABLESPACE "PMM_INDEX" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 570425344 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SEMAD.IDX_FK5_VALOR_HISTORICO ON SEMAD.VALOR_HISTORICO (ID_TABELA ASC, NB_TRANSACAO_HISTORICO ASC, NB_CAMPO ASC, ID_USUARIO ASC) 
LOGGING 
TABLESPACE "PMM_INDEX" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 995098624 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."VALOR_HISTORICO" TO "AUDITORIA";
 
  GRANT SELECT ON "SEMAD"."VALOR_HISTORICO" TO "USUARIO_ADMIN";
 
  GRANT SELECT ON "SEMAD"."VALOR_HISTORICO" TO "SEMAD_LNK";
REM INSERTING into SEMAD.ESTAGIARIO
SET DEFINE OFF;
Insert into SEMAD.ESTAGIARIO (ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('168293',null,null,'69000000','uyfyl',null,null,null,null,null,null,null);
Insert into SEMAD.ESTAGIARIO (ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('144120',null,null,'69000000','LIYFLYF',null,null,null,'123456','123456',null,null);
Insert into SEMAD.ESTAGIARIO (ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('157067',null,null,'69095090','RUA BURITI','47',null,'CIDADE NOVA','14545','Q545',null,null);
Insert into SEMAD.ESTAGIARIO (ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('166454',null,null,'69000000','LIYVLIV',null,null,null,null,null,null,null);
Insert into SEMAD.ESTAGIARIO (ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('167788',null,null,'69078480','Travessa S 6',null,null,'Japiim',null,null,null,null);
Insert into SEMAD.ESTAGIARIO (ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('168314',null,null,'69000000','livlvlv',null,null,null,null,null,null,null);
Insert into SEMAD.ESTAGIARIO (ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('166329',null,null,'69000000','LVLVLVL',null,null,null,null,null,null,null);
Insert into SEMAD.ESTAGIARIO (ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('27130',null,null,'69010170','AVENIDA LEONARDO MALCHER','21','BL 10-A, APT 02, CONJ. ELDORADO','CENTRO','3711','00206792','9983-8492, 9336-2319','rodrigo.cabral@pmm.am.gov.br');
Insert into SEMAD.ESTAGIARIO (ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('168290',null,null,'69000000','vlvlvlivl',null,null,null,null,null,null,null);
Insert into SEMAD.ESTAGIARIO (ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('169166',null,null,'69010170','AVENIDA LEONARDO MALCHER','834','CASA 01','CENTRO','0320','06584993','9467-9435','KAKAUSAREL@HOTMAIL.COM');
--------------------------------------------------------
--  DDL for Index XPKESTAGIARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKESTAGIARIO" ON "SEMAD"."ESTAGIARIO" ("ID_PESSOA_ESTAGIARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2ESTAGIARIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2ESTAGIARIO" ON "SEMAD"."ESTAGIARIO" ("ID_PESSOA_FUNCIONARIO", "NB_FUNCIONARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  Constraints for Table ESTAGIARIO
--------------------------------------------------------

  ALTER TABLE "SEMAD"."ESTAGIARIO" MODIFY ("ID_PESSOA_ESTAGIARIO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."ESTAGIARIO" ADD PRIMARY KEY ("ID_PESSOA_ESTAGIARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTAGIARIO
--------------------------------------------------------

  ALTER TABLE "SEMAD"."ESTAGIARIO" ADD FOREIGN KEY ("ID_PESSOA_FUNCIONARIO", "NB_FUNCIONARIO")
	  REFERENCES "SEMAD"."FUNCIONARIO_PE" ("ID_PESSOA_FUNCIONARIO", "NB_FUNCIONARIO") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "SEMAD"."ESTAGIARIO" ADD FOREIGN KEY ("ID_PESSOA_ESTAGIARIO")
	  REFERENCES "SEMAD"."PESSOA_FISICA" ("ID_PESSOA") ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_AVS_IUD_ESTAGIARIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SEMAD"."T_AVS_IUD_ESTAGIARIO" 
  AFTER
  INSERT OR DELETE OR UPDATE
  on semad.Estagiario
  REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW

declare
  pnb_Valor_Historico number;
  pID_Tabela number;
  pnb_Campo number;
  pnb_Transacao number;
  pID_Usuario number;
  pcs_evento number;
begin
  select id_usuario into pid_usuario
  from usuario
  where tx_login = user;
  if inserting then
     pcs_evento := 1;
  else
     if updating then
        pcs_evento := 2;
     else
        pcs_evento := 3;
     end if;
  end if;
  pID_Tabela := F_AVS_Busca_Tabela('ESTAGIARIO');
  pnb_Transacao := F_AVS_Cadastra_Transacao(pID_Tabela,pID_usuario,pcs_evento );
  -- insere valor do campo ID_Pessoa_Estagiario --
  pnb_Campo := F_AVS_Busca_Campo('ID_PESSOA_ESTAGIARIO',pID_Tabela,'INTEGER');
  pnb_Valor_Historico := F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Pessoa_Estagiario,
          :old.ID_Pessoa_Estagiario);

-- insere valor do campo ID_Pessoa_Funcionario --
  pnb_Campo := F_AVS_Busca_Campo('ID_PESSOA_FUNCIONARIO',pID_Tabela,'INTEGER');
  pnb_Valor_Historico := F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.ID_Pessoa_Funcionario,
          :old.ID_Pessoa_Funcionario);

-- insere valor do campo nb_Funcionario --
  pnb_Campo := F_AVS_Busca_Campo('NB_FUNCIONARIO',pID_Tabela,'INTEGER');
  pnb_Valor_Historico := F_G_PK_Valor_Historico(pID_Tabela,pnb_Transacao,pnb_Campo,pID_usuario);
  insert into semad.Valor_Historico
         (nb_Valor_Historico,
          ID_Tabela,
          nb_Transacao_Historico,
          nb_Campo,
          ID_Usuario,
          nb_Valor_Varchar2000,
          nb_Old_Varchar2000)
  Values (pnb_Valor_Historico,
          pID_Tabela,
          pnb_Transacao,
          pnb_Campo,
          pID_Usuario,
          :new.nb_Funcionario,
          :old.nb_Funcionario);


end; --

/
ALTER TRIGGER "SEMAD"."T_AVS_IUD_ESTAGIARIO" DISABLE;
--------------------------------------------------------
--  DDL for Function F_AVS_BUSCA_CAMPO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SEMAD"."F_AVS_BUSCA_CAMPO" 
  (ptx_campo IN campo.tx_campo%type,
   pid_tabela IN tabela.id_tabela%type,
   ptx_tipo_campo IN tipo_campo.tx_tipo_campo%type)
RETURN  campo.nb_campo%type IS pnb_campo campo.nb_campo%type;

   pid_servidor   number;
   numregs        number;
   pcs_tipo_campo number;
BEGIN
    pnb_campo := 0;
    numregs := 0;
    
    select max(nb_campo) into numregs
    from campo
    where tx_campo = ptx_campo and
          id_tabela = pid_tabela;
     
    if numregs > 0 then
      select nb_campo into pnb_campo
      from campo
      where tx_campo = ptx_campo and
            id_tabela = pid_tabela;
    else
      select max(id_servidor) into pid_servidor
      from parametros_default;
      pcs_tipo_campo := F_Busca_Tipo_Campo(ptx_tipo_campo,pid_servidor);
      pnb_campo := F_G_PK_campo(pid_tabela);
      insert into campo (id_tabela, nb_campo, tx_campo,cs_tipo_campo)
             values (pid_tabela, pnb_campo, ptx_campo,pcs_tipo_campo);
    end if;

    RETURN pnb_campo;
END;


-- End of DDL script for F_AVS_BUSCA_CAMPO

/
--------------------------------------------------------
--  DDL for Function F_AVS_BUSCA_TABELA
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SEMAD"."F_AVS_BUSCA_TABELA" 
  (ptx_tabela IN Tabela.tx_nome%type)
RETURN  Tabela.ID_Tabela%type IS Pid_Tabela Tabela.ID_Tabela%type;
   pid_servidor number;
   numregs number;
BEGIN
    numregs := 0;
    select count(id_tabela) into numregs
    from tabela
    where tx_nome = ptx_tabela;
    if numregs <> 0 then
       select id_tabela into Pid_Tabela
       from tabela
       where tx_nome = ptx_tabela;
    else
      pid_tabela := F_G_PK_Tabela();
      select max(id_servidor) into pid_servidor
           from parametros_default;
      insert into tabela (id_tabela, tx_nome, id_servidor, cs_atualizacao)
             values (pid_tabela, ptx_tabela, pid_servidor,2);
    end if;
    RETURN Pid_Tabela;
END;


-- End of DDL script for F_AVS_BUSCA_TABELA

/
--------------------------------------------------------
--  DDL for Function F_AVS_CADASTRA_TRANSACAO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SEMAD"."F_AVS_CADASTRA_TRANSACAO" 
  ( pID_Tabela IN Tabela.ID_Tabela%type,
    pID_Usuario IN Usuario.ID_Usuario%type,
    pcs_evento IN number)
  RETURN  number IS pnb_Transacao number;
BEGIN
  pnb_transacao := F_G_PK_transacao_historico(pid_usuario,pid_tabela);
  insert into transacao_historico (id_tabela, id_usuario, nb_transacao_historico, dt_transacao_historico, cs_evento)
  values (pid_tabela, pid_usuario, pnb_transacao, sysdate, pcs_evento);
  RETURN pnb_transacao;
END; -- F_AVS_CADASTRA_TRANSACAO

-- End of DDL script for F_AVS_CADASTRA_TRANSACAO

/
--------------------------------------------------------
--  DDL for Function F_G_PK_VALOR_HISTORICO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SEMAD"."F_G_PK_VALOR_HISTORICO" 
(PID_TABELA NUMBER,PNB_TRANSACAO_HISTORICO NUMBER,PNB_CAMPO NUMBER,PID_USUARIO NUMBER)
RETURN NUMBER IS V_N_VALOR_HISTORICO NUMBER;
BEGIN
   SELECT COUNT (*) INTO  V_N_VALOR_HISTORICO
   FROM VALOR_HISTORICO
   WHERE(ID_TABELA = PID_TABELA AND NB_TRANSACAO_HISTORICO = PNB_TRANSACAO_HISTORICO AND NB_CAMPO = PNB_CAMPO AND ID_USUARIO = PID_USUARIO );
    IF V_N_VALOR_HISTORICO = 0 THEN
        V_N_VALOR_HISTORICO := 1;
    ELSE
        SELECT MAX(NB_VALOR_HISTORICO) + 1
        INTO V_N_VALOR_HISTORICO
        FROM VALOR_HISTORICO
        WHERE (ID_TABELA = PID_TABELA AND NB_TRANSACAO_HISTORICO = PNB_TRANSACAO_HISTORICO AND NB_CAMPO = PNB_CAMPO AND ID_USUARIO = PID_USUARIO );
     END IF;
     RETURN V_N_VALOR_HISTORICO;
END; -- F_G_PK_VALOR_HISTORICO

/
