DROP
  TABLE "SEMAD"."GESTOR_ESTAGIO" CASCADE CONSTRAINTS;
CREATE
  TABLE "SEMAD"."GESTOR_ESTAGIO"
  (
    "NB_GESTOR_ESTAGIO"       NUMBER NOT NULL ENABLE,
    "ID_ORGAO_GESTOR_ESTAGIO" NUMBER NOT NULL ENABLE,
    "ID_USUARIO"              NUMBER NOT NULL ENABLE,
    "DT_CADASTRO"             DATE NOT NULL ENABLE,
    "DT_ATUALIZACAO"          DATE NOT NULL ENABLE,
    "ID_USUARIO_CADASTRO"     NUMBER NOT NULL ENABLE,
    "ID_USUARIO_ATUALIZACAO"  NUMBER NOT NULL ENABLE,
    "TX_EMAIL"                VARCHAR2(100 BYTE)
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
    CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "PMM_DATA" ;
ALTER TABLE "SEMAD"."GESTOR_ESTAGIO" ADD CONSTRAINT "GESTOR_ESTAGIO_PK" PRIMARY
KEY
(
  "NB_GESTOR_ESTAGIO", "ID_ORGAO_GESTOR_ESTAGIO"
)
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0
  FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
  CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "PMM_DATA" ENABLE;
ALTER TABLE "SEMAD"."GESTOR_ESTAGIO" ADD CONSTRAINT
"GESTOR_ESTAGIO_ORGAO_GEST_FK1" FOREIGN KEY
(
  "ID_ORGAO_GESTOR_ESTAGIO"
)
REFERENCES "SEMAD"."ORGAO_GESTOR_ESTAGIO"
(
  "ID_ORGAO_GESTOR_ESTAGIO"
)
ENABLE;
CREATE
  INDEX "SEMAD"."GESTOR_ESTAGIO_INDEX1" ON "SEMAD"."GESTOR_ESTAGIO"
  (
    "NB_GESTOR_ESTAGIO"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
    CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "PMM_DATA";
CREATE OR REPLACE PUBLIC SYNONYM GESTOR_ESTAGIO FOR SEMAD.GESTOR_ESTAGIO;

CREATE OR REPLACE
FUNCTION       SEMAD.F_G_PK_GESTOR_ESTAGIO
(PID_ORGAO_GESTOR_ESTAGIO INTEGER)
RETURN NUMBER IS V_N_GESTOR_ESTAGIO NUMBER;
BEGIN
   SELECT COUNT (*) INTO  V_N_GESTOR_ESTAGIO
   FROM GESTOR_ESTAGIO
   WHERE(ID_ORGAO_GESTOR_ESTAGIO = PID_ORGAO_GESTOR_ESTAGIO);
    IF V_N_GESTOR_ESTAGIO = 0 THEN
        V_N_GESTOR_ESTAGIO := 1;
    ELSE
        SELECT MAX(NB_GESTOR_ESTAGIO) + 1
        INTO V_N_GESTOR_ESTAGIO
        FROM GESTOR_ESTAGIO
        WHERE (ID_ORGAO_GESTOR_ESTAGIO = PID_ORGAO_GESTOR_ESTAGIO);
     END IF;
     RETURN V_N_GESTOR_ESTAGIO;
END;

CREATE OR REPLACE PUBLIC SYNONYM F_G_PK_GESTOR_ESTAGIO FOR SEMAD.F_G_PK_GESTOR_ESTAGIO;