--------------------------------------------------------
--  Arquivo criado - Quinta-feira-Março-10-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Index AGENCIA_ESTAGIO_EMAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."AGENCIA_ESTAGIO_EMAIL_PK" ON "SEMAD"."AGENCIA_ESTAGIO_EMAIL" ("ID_AGENCIA_ESTAGIO", "NB_AGENCIA_ESTAGIO_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index ESTAGIARIO_SELECAO_INDEX1
--------------------------------------------------------

  CREATE INDEX "SEMAD"."ESTAGIARIO_SELECAO_INDEX1" ON "SEMAD"."ESTAGIARIO_SELECAO" ("ID_SELECAO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index ESTAGIARIO_SELECAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."ESTAGIARIO_SELECAO_PK" ON "SEMAD"."ESTAGIARIO_SELECAO" ("ID_SELECAO_ESTAGIO", "ID_PESSOA_ESTAGIARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index GESTOR_ESTAGIO_INDEX1
--------------------------------------------------------

  CREATE INDEX "SEMAD"."GESTOR_ESTAGIO_INDEX1" ON "SEMAD"."GESTOR_ESTAGIO" ("NB_GESTOR_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index GESTOR_ESTAGIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."GESTOR_ESTAGIO_PK" ON "SEMAD"."GESTOR_ESTAGIO" ("NB_GESTOR_ESTAGIO", "ID_ORGAO_GESTOR_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF10CONTRATO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF10CONTRATO_ESTAGIO" ON "SEMAD"."CONTRATO_ESTAGIO" ("ID_UNIDADE_ORG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF11CONTRATO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF11CONTRATO_ESTAGIO" ON "SEMAD"."CONTRATO_ESTAGIO" ("ID_SELECAO_ESTAGIO", "ID_RECRUTAMENTO_ESTAGIO", "NB_VAGAS_RECRUTAMENTO", "NB_CANDIDATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF12CONTRATO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF12CONTRATO_ESTAGIO" ON "SEMAD"."CONTRATO_ESTAGIO" ("ID_AGENCIA_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1AGENCIA_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1AGENCIA_ESTAGIO" ON "SEMAD"."AGENCIA_ESTAGIO" ("ID_USUARIO_CADASTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1AGENTE_SETORIAL_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1AGENTE_SETORIAL_ESTAGIO" ON "SEMAD"."AGENTE_SETORIAL_ESTAGIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1CONTRATO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1CONTRATO_ESTAGIO" ON "SEMAD"."CONTRATO_ESTAGIO" ("ID_PESSOA_ESTAGIARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1CURSO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1CURSO_ESTAGIO" ON "SEMAD"."CURSO_ESTAGIO" ("CS_AREA_CONHECIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1ESTAGIARIO_VAGA
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1ESTAGIARIO_VAGA" ON "SEMAD"."ESTAGIARIO_VAGA" ("ID_RECRUTAMENTO_ESTAGIO", "NB_VAGAS_RECRUTAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1ITEM_PAG_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1ITEM_PAG_ESTAGIO" ON "SEMAD"."ITEM_PAG_ESTAGIO" ("ID_PAGAMENTO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1ORGAO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1ORGAO_ESTAGIO" ON "SEMAD"."ORGAO_ESTAGIO" ("ID_UNIDADE_ORG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1ORGAO_GESTOR_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1ORGAO_GESTOR_ESTAGIO" ON "SEMAD"."ORGAO_GESTOR_ESTAGIO" ("ID_UNIDADE_ORG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1PAGAMENTO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1PAGAMENTO_ESTAGIO" ON "SEMAD"."PAGAMENTO_ESTAGIO" ("ID_ORGAO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1RECESSO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1RECESSO_ESTAGIO" ON "SEMAD"."RECESSO_ESTAGIO" ("ID_CONTRATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1RECRUTAMENTO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1RECRUTAMENTO_ESTAGIO" ON "SEMAD"."RECRUTAMENTO_ESTAGIO" ("ID_QUADRO_VAGAS_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1SELECAO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1SELECAO_ESTAGIO" ON "SEMAD"."SELECAO_ESTAGIO" ("ID_USUARIO_CADASTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1SOLICITACAO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1SOLICITACAO_ESTAGIO" ON "SEMAD"."SOLICITACAO_ESTAGIO" ("ID_USUARIO_CADASTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF1VAGAS_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF1VAGAS_ESTAGIO" ON "SEMAD"."VAGAS_ESTAGIO" ("ID_QUADRO_VAGAS_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2AGENCIA_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2AGENCIA_ESTAGIO" ON "SEMAD"."AGENCIA_ESTAGIO" ("ID_USUARIO_ATUALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2CONTRATO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2CONTRATO_ESTAGIO" ON "SEMAD"."CONTRATO_ESTAGIO" ("ID_ORGAO_GESTOR_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2ESTAGIARIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2ESTAGIARIO" ON "SEMAD"."ESTAGIARIO" ("ID_PESSOA_FUNCIONARIO", "NB_FUNCIONARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2ESTAGIARIO_VAGA
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2ESTAGIARIO_VAGA" ON "SEMAD"."ESTAGIARIO_VAGA" ("ID_PESSOA_ESTAGIARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2ITEM_PAG_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2ITEM_PAG_ESTAGIO" ON "SEMAD"."ITEM_PAG_ESTAGIO" ("ID_ITEM_PAGAMENTO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2ORGAO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2ORGAO_ESTAGIO" ON "SEMAD"."ORGAO_ESTAGIO" ("ID_USUARIO_CADASTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2PAGAMENTO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2PAGAMENTO_ESTAGIO" ON "SEMAD"."PAGAMENTO_ESTAGIO" ("ID_ORGAO_GESTOR_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2QUADRO_VAGAS_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2QUADRO_VAGAS_ESTAGIO" ON "SEMAD"."QUADRO_VAGAS_ESTAGIO" ("ID_ORGAO_GESTOR_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2RECESSO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2RECESSO_ESTAGIO" ON "SEMAD"."RECESSO_ESTAGIO" ("ID_ORGAO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2RECRUTAMENTO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2RECRUTAMENTO_ESTAGIO" ON "SEMAD"."RECRUTAMENTO_ESTAGIO" ("ID_ORGAO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2SOLICITACAO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2SOLICITACAO_ESTAGIO" ON "SEMAD"."SOLICITACAO_ESTAGIO" ("ID_USUARIO_ATUALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2SUPERVISOR_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2SUPERVISOR_ESTAGIO" ON "SEMAD"."SUPERVISOR_ESTAGIO" ("ID_PESSOA_FUNCIONARIO", "NB_FUNCIONARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF2VAGAS_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF2VAGAS_ESTAGIO" ON "SEMAD"."VAGAS_ESTAGIO" ("ID_ORGAO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF3CONTRATO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF3CONTRATO_ESTAGIO" ON "SEMAD"."CONTRATO_ESTAGIO" ("ID_ORGAO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF3ITEM_PAG_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF3ITEM_PAG_ESTAGIO" ON "SEMAD"."ITEM_PAG_ESTAGIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF3ORGAO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF3ORGAO_ESTAGIO" ON "SEMAD"."ORGAO_ESTAGIO" ("ID_USUARIO_ATUALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF3PAGAMENTO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF3PAGAMENTO_ESTAGIO" ON "SEMAD"."PAGAMENTO_ESTAGIO" ("ID_AGENCIA_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF3QUADRO_VAGAS_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF3QUADRO_VAGAS_ESTAGIO" ON "SEMAD"."QUADRO_VAGAS_ESTAGIO" ("ID_USUARIO_CADASTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF3RECESSO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF3RECESSO_ESTAGIO" ON "SEMAD"."RECESSO_ESTAGIO" ("ID_AGENCIA_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF3RECRUTAMENTO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF3RECRUTAMENTO_ESTAGIO" ON "SEMAD"."RECRUTAMENTO_ESTAGIO" ("ID_USUARIO_CADASTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF3SELECAO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF3SELECAO_ESTAGIO" ON "SEMAD"."SELECAO_ESTAGIO" ("ID_ORGAO_GESTOR_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF3SOLICITACAO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF3SOLICITACAO_ESTAGIO" ON "SEMAD"."SOLICITACAO_ESTAGIO" ("ID_ORGAO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF3SUPERVISOR_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF3SUPERVISOR_ESTAGIO" ON "SEMAD"."SUPERVISOR_ESTAGIO" ("ID_CONSELHO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF3VAGAS_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF3VAGAS_ESTAGIO" ON "SEMAD"."VAGAS_ESTAGIO" ("CS_TIPO_VAGA_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF4CONTRATO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF4CONTRATO_ESTAGIO" ON "SEMAD"."CONTRATO_ESTAGIO" ("ID_QUADRO_VAGAS_ESTAGIO", "ID_ORGAO_ESTAGIO", "CS_TIPO_VAGA_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF4ESTAGIARIO_SELECAO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF4ESTAGIARIO_SELECAO" ON "SEMAD"."ESTAGIARIO_SELECAO" ("ID_USUARIO_CADASTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF4ITEM_PAG_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF4ITEM_PAG_ESTAGIO" ON "SEMAD"."ITEM_PAG_ESTAGIO" ("ID_CONTRATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF4PAGAMENTO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF4PAGAMENTO_ESTAGIO" ON "SEMAD"."PAGAMENTO_ESTAGIO" ("ID_USUARIO_CADASTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF4QUADRO_VAGAS_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF4QUADRO_VAGAS_ESTAGIO" ON "SEMAD"."QUADRO_VAGAS_ESTAGIO" ("ID_USUARIO_ATUALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF4RECRUTAMENTO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF4RECRUTAMENTO_ESTAGIO" ON "SEMAD"."RECRUTAMENTO_ESTAGIO" ("ID_USUARIO_ATUALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF4SELECAO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF4SELECAO_ESTAGIO" ON "SEMAD"."SELECAO_ESTAGIO" ("ID_ORGAO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF4SOLICITACAO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF4SOLICITACAO_ESTAGIO" ON "SEMAD"."SOLICITACAO_ESTAGIO" ("ID_ORGAO_GESTOR_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF4VAGAS_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF4VAGAS_ESTAGIO" ON "SEMAD"."VAGAS_ESTAGIO" ("ID_USUARIO_CADASTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF5CONTRATO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF5CONTRATO_ESTAGIO" ON "SEMAD"."CONTRATO_ESTAGIO" ("ID_CURSO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF5PAGAMENTO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF5PAGAMENTO_ESTAGIO" ON "SEMAD"."PAGAMENTO_ESTAGIO" ("ID_USUARIO_ATUALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF5SELECAO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF5SELECAO_ESTAGIO" ON "SEMAD"."SELECAO_ESTAGIO" ("ID_USUARIO_ATUALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF5SEMADSOLICITACAO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF5SEMADSOLICITACAO_ESTAGIO" ON "SEMAD"."SOLICITACAO_ESTAGIO" ("ID_QUADRO_VAGAS_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF5VAGAS_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF5VAGAS_ESTAGIO" ON "SEMAD"."VAGAS_ESTAGIO" ("ID_USUARIO_ATUALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF6CONTRATO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF6CONTRATO_ESTAGIO" ON "SEMAD"."CONTRATO_ESTAGIO" ("ID_PESSOA_SUPERVISOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF6PAGAMENTO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF6PAGAMENTO_ESTAGIO" ON "SEMAD"."PAGAMENTO_ESTAGIO" ("CS_TIPO_PAG_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF6RECESSO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF6RECESSO_ESTAGIO" ON "SEMAD"."RECESSO_ESTAGIO" ("ID_SETORIAL_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF6VAGAS_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF6VAGAS_ESTAGIO" ON "SEMAD"."VAGAS_ESTAGIO" ("ID_CURSO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF7CONTRATO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF7CONTRATO_ESTAGIO" ON "SEMAD"."CONTRATO_ESTAGIO" ("ID_INSTITUICAO_ENSINO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF7RECESSO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF7RECESSO_ESTAGIO" ON "SEMAD"."RECESSO_ESTAGIO" ("ID_USUARIO_CADASTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF8CONTRATO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF8CONTRATO_ESTAGIO" ON "SEMAD"."CONTRATO_ESTAGIO" ("ID_BOLSA_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XIF8RECESSO_ESTAGIO
--------------------------------------------------------

  CREATE INDEX "SEMAD"."XIF8RECESSO_ESTAGIO" ON "SEMAD"."RECESSO_ESTAGIO" ("ID_USUARIO_ATUALIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKAGENCIA_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKAGENCIA_ESTAGIO" ON "SEMAD"."AGENCIA_ESTAGIO" ("ID_AGENCIA_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKAGENTE_SETORIAL_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKAGENTE_SETORIAL_ESTAGIO" ON "SEMAD"."AGENTE_SETORIAL_ESTAGIO" ("ID_SETORIAL_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKBOLSA_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKBOLSA_ESTAGIO" ON "SEMAD"."BOLSA_ESTAGIO" ("NB_BOLSA_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKCONTRATO_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKCONTRATO_ESTAGIO" ON "SEMAD"."CONTRATO_ESTAGIO" ("ID_CONTRATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKCURSO_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKCURSO_ESTAGIO" ON "SEMAD"."CURSO_ESTAGIO" ("ID_CURSO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKESTAGIARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKESTAGIARIO" ON "SEMAD"."ESTAGIARIO" ("ID_PESSOA_ESTAGIARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKESTAGIARIO_VAGA
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKESTAGIARIO_VAGA" ON "SEMAD"."ESTAGIARIO_VAGA" ("ID_RECRUTAMENTO_ESTAGIO", "NB_VAGAS_RECRUTAMENTO", "NB_CANDIDATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKITEM_PAG_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKITEM_PAG_ESTAGIO" ON "SEMAD"."ITEM_PAG_ESTAGIO" ("ID_PAGAMENTO_ESTAGIO", "ID_ITEM_PAGAMENTO_ESTAGIO", "ID_CONTRATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKITEM_PAGAMENTO_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKITEM_PAGAMENTO_ESTAGIO" ON "SEMAD"."ITEM_PAGAMENTO_ESTAGIO" ("ID_ITEM_PAGAMENTO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKORGAO_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKORGAO_ESTAGIO" ON "SEMAD"."ORGAO_ESTAGIO" ("ID_ORGAO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKORGAO_GESTOR_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKORGAO_GESTOR_ESTAGIO" ON "SEMAD"."ORGAO_GESTOR_ESTAGIO" ("ID_ORGAO_GESTOR_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKPAGAMENTO_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKPAGAMENTO_ESTAGIO" ON "SEMAD"."PAGAMENTO_ESTAGIO" ("ID_PAGAMENTO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKQUADRO_VAGAS_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKQUADRO_VAGAS_ESTAGIO" ON "SEMAD"."QUADRO_VAGAS_ESTAGIO" ("ID_QUADRO_VAGAS_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKRECESSO_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKRECESSO_ESTAGIO" ON "SEMAD"."RECESSO_ESTAGIO" ("ID_RECESSO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKRECRUTAMENTO_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKRECRUTAMENTO_ESTAGIO" ON "SEMAD"."RECRUTAMENTO_ESTAGIO" ("ID_RECRUTAMENTO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKSELECAO_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKSELECAO_ESTAGIO" ON "SEMAD"."SELECAO_ESTAGIO" ("ID_SELECAO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKSOLICITACAO_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKSOLICITACAO_ESTAGIO" ON "SEMAD"."SOLICITACAO_ESTAGIO" ("ID_SOLICITACAO_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKSUPERVISOR_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKSUPERVISOR_ESTAGIO" ON "SEMAD"."SUPERVISOR_ESTAGIO" ("ID_PESSOA_SUPERVISOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKTIPO_PAG_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKTIPO_PAG_ESTAGIO" ON "SEMAD"."TIPO_PAG_ESTAGIO" ("CS_TIPO_PAG_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Index XPKTIPO_VAGA_ESTAGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."XPKTIPO_VAGA_ESTAGIO" ON "SEMAD"."TIPO_VAGA_ESTAGIO" ("CS_TIPO_VAGA_ESTAGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
