--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Março-21-2014   
--------------------------------------------------------
DROP TABLE "SEMAD"."OFERTA_VAGA" cascade constraints;
DROP TABLE "SEMAD"."BOLSA_ESTAGIO" cascade constraints;
DROP TABLE "SEMAD"."CURSO_ESTAGIO" cascade constraints;
DROP TABLE "SEMAD"."USUARIO" cascade constraints;
DROP TABLE "SEMAD"."VAGAS_ESTAGIO" cascade constraints;
--------------------------------------------------------
--  DDL for Table OFERTA_VAGA
--------------------------------------------------------

  CREATE TABLE "SEMAD"."OFERTA_VAGA" 
   (	"ID_OFERTA_VAGA" NUMBER, 
	"TX_CODIGO_OFERTA_VAGA" VARCHAR2(20 BYTE), 
	"ID_ORGAO_GESTOR_ESTAGIO" NUMBER, 
	"ID_ORGAO_ESTAGIO" NUMBER, 
	"ID_QUADRO_VAGAS_ESTAGIO" NUMBER, 
	"ID_AGENCIA_ESTAGIO" NUMBER, 
	"CS_TIPO_VAGA_ESTAGIO" NUMBER, 
	"TX_PESSOA_CONTATO" VARCHAR2(100 BYTE), 
	"TX_TELEFONE" VARCHAR2(20 BYTE), 
	"TX_CARGO_FUNCAO" VARCHAR2(100 BYTE), 
	"TX_EMAIL" VARCHAR2(100 BYTE), 
	"TX_ENDERECO" VARCHAR2(200 BYTE), 
	"TX_PONTO_REFERENCIA" VARCHAR2(100 BYTE), 
	"TX_NUM_ONIBUS" VARCHAR2(20 BYTE), 
	"NB_QUANTIDADE" NUMBER, 
	"NB_QTDE_EMCAMINHADO" NUMBER, 
	"DT_ENTREVISTA" DATE, 
	"TX_HORARIO" VARCHAR2(20 BYTE), 
	"NB_DURACAO_ESTAGIO" NUMBER, 
	"ID_BOLSA_ESTAGIO" NUMBER, 
	"NB_VALOR_TRANSPORTE" NUMBER, 
	"CS_ESCOLARIDADE" NUMBER, 
	"ID_CURSO_ESTAGIO" NUMBER, 
	"NB_SEMESTRE" NUMBER, 
	"TX_HORA_INICIO" VARCHAR2(20 BYTE), 
	"TX_HORA_FINAL" VARCHAR2(20 BYTE), 
	"TX_OUTROS_HORARIOS" VARCHAR2(100 BYTE), 
	"CS_WINDOWS" NUMBER, 
	"CS_WORD" NUMBER, 
	"CS_EXCEL" NUMBER, 
	"CS_POWERPOINT" NUMBER, 
	"CS_INTERNET" NUMBER, 
	"CS_CORELDRAW" NUMBER, 
	"CS_PHOTOSHOP" NUMBER, 
	"CS_WEBDESIGN" NUMBER, 
	"CS_AUTOCAD" NUMBER, 
	"CS_INGLES" NUMBER, 
	"CS_ESPANHOL" NUMBER, 
	"CS_FRANCES" NUMBER, 
	"CS_ALEMAO" NUMBER, 
	"TX_OUTRAS_LINGUAS" VARCHAR2(100 BYTE), 
	"TX_OUTROS_REQUISITOS" VARCHAR2(100 BYTE), 
	"CS_SEXO" NUMBER, 
	"TX_ATIVIDADES" VARCHAR2(400 BYTE), 
	"TX_OBSERVACAO" VARCHAR2(200 BYTE), 
	"CS_SITUACAO" NUMBER, 
	"ID_USUARIO_CADASTRO" NUMBER, 
	"ID_USUARIO_ATUALIZACAO" NUMBER, 
	"DT_CADASTRO" DATE, 
	"DT_ATUALIZACAO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
 

   COMMENT ON COLUMN "SEMAD"."OFERTA_VAGA"."CS_SITUACAO" IS '1-Aberta
2-Efetivada
3-Oferta Encaminhada
4-Cancelada';
--------------------------------------------------------
--  DDL for Table BOLSA_ESTAGIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."BOLSA_ESTAGIO" 
   (	"ID_BOLSA_ESTAGIO" NUMBER(*,0), 
	"TX_BOLSA_ESTAGIO" VARCHAR2(255 BYTE), 
	"NB_VALOR" NUMBER(12,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Table CURSO_ESTAGIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."CURSO_ESTAGIO" 
   (	"ID_CURSO_ESTAGIO" NUMBER(*,0), 
	"TX_CURSO_ESTAGIO" VARCHAR2(255 BYTE), 
	"CS_AREA_CONHECIMENTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."USUARIO" 
   (	"ID_USUARIO" NUMBER(5,0), 
	"TX_LOGIN" VARCHAR2(20 BYTE), 
	"CS_SITUACAO" NUMBER DEFAULT 0, 
	"TX_CONFIGURACAO" LONG, 
	"ID_PESSOA_FUNCIONARIO" NUMBER, 
	"TX_MOTIVO_SITUACAO" VARCHAR2(200 BYTE), 
	"ID_UNIDADE_GESTORA" NUMBER, 
	"DT_ULTIMO_ACESSO" DATE, 
	"TX_IP_ULTIMO_ACESSO" VARCHAR2(15 BYTE), 
	"TX_EMAIL_PMM" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCA_DATA" ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "BANCOPRECO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "BP_FINALIZADORES";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "AUDITORIA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "XPTO_CONNECT";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ADMINISTRADORES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "LICITAC?O";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ESTOQUE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "Q_BANCO_PRECOS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "BP_CADASTRO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_SEMSA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_LICITACAO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "BP_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "APLICAR_PESSOAS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CONSULTORES";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_TRAMITE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "CONTAS_PUBLICAS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "BP_MATERIAL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "WORKFLOW";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CONS_EXT";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "PATRIMONIO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "COLETORDEPONTO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_TRAM_SEMSA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PONTO_ELETRONICO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_IMPLURB";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CONS_IMPL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_TRAM_IMPL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "WOKF_EXTERNO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "ESTOQUE_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PROT_CML";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PRE_CADASTRO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PONTO_SEMEF";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ESTOQUE_KITS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "REGISTROPRECOS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "USUARIO_ADMIN";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "ESTOQUE_ADMIN";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GESTAOESCOLAR";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_OPERADOR";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_ATENDENTE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_AUTORIZACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "EST_GESTOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GE_OPERADOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "R_BANCOPRECOS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_RECEBIMENTO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GE_GESTOR";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "SEMAD_LNK";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "THIAGO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "VALERIA";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "ROSANA";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "TACIANA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "MAYCON";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "JUSSARA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "VALDERI";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "SARYTA_GARCEZ";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "IWAMOTO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "BERNARDO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "ANDRE_PINHEIRO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "IVY_SA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_SOLICITANTE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_GESTOR";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "EST_RM";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_GESTOR_PASSAGEM";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "ROBSON";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "NEILA_SEMAD";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "JURIDICO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PGM";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "KEYCE_MARQUES";
 
  GRANT ALTER, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_CONSULTA";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_OPERACIONAL";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_GESTORAUXILIAR";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_GESTOR";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JURIDICO_OPERACIONALTCE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_ALMOXPEQUENOS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "HABITACAO_CADASTRO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_IMOVEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_IMOVEL_REL";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_CAD";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_REL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_CEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOESCOLAR_CONSULTA";
 
  GRANT ALTER, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JUR_DISTRIBUICAO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "EMANUELLE_ALVES";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "JAMILE_BREVAL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_MOV_IND";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "PATRIMONIO_CONS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "VOYAGE_CONS";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "GESTAOCONTASPUBLICAS_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "TESTES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "PONTOELETRONICOV2_RH";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_CONTABIL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_GESTOR_RP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_GESTOR_BP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_GESTOR_CATALOGACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."USUARIO" TO "IRP_SOLICITANTE";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "EST_INVENTARIO";
 
  GRANT SELECT ON "SEMAD"."USUARIO" TO "HABITACAO";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."USUARIO" TO "PATRIMONIO_MOVEL_MOVI";
--------------------------------------------------------
--  DDL for Table VAGAS_ESTAGIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."VAGAS_ESTAGIO" 
   (	"ID_QUADRO_VAGAS_ESTAGIO" NUMBER(*,0), 
	"ID_ORGAO_ESTAGIO" NUMBER(*,0), 
	"NB_QUANTIDADE" NUMBER(*,0), 
	"CS_TIPO_VAGA_ESTAGIO" NUMBER(*,0), 
	"DT_CADASTRO" DATE, 
	"DT_ATUALIZACAO" DATE, 
	"ID_USUARIO_CADASTRO" NUMBER, 
	"ID_USUARIO_ATUALIZACAO" NUMBER, 
	"ID_CURSO_ESTAGIO" NUMBER(*,0), 
	"ID_AGENCIA_ESTAGIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
 

   COMMENT ON COLUMN "SEMAD"."VAGAS_ESTAGIO"."ID_USUARIO_CADASTRO" IS 'Código do usuário do BD.';
 
   COMMENT ON COLUMN "SEMAD"."VAGAS_ESTAGIO"."ID_USUARIO_ATUALIZACAO" IS 'Código do usuário do BD.';
REM INSERTING into SEMAD.OFERTA_VAGA
SET DEFINE OFF;
Insert into SEMAD.OFERTA_VAGA (ID_OFERTA_VAGA,TX_CODIGO_OFERTA_VAGA,ID_ORGAO_GESTOR_ESTAGIO,ID_ORGAO_ESTAGIO,ID_QUADRO_VAGAS_ESTAGIO,ID_AGENCIA_ESTAGIO,CS_TIPO_VAGA_ESTAGIO,TX_PESSOA_CONTATO,TX_TELEFONE,TX_CARGO_FUNCAO,TX_EMAIL,TX_ENDERECO,TX_PONTO_REFERENCIA,TX_NUM_ONIBUS,NB_QUANTIDADE,NB_QTDE_EMCAMINHADO,DT_ENTREVISTA,TX_HORARIO,NB_DURACAO_ESTAGIO,ID_BOLSA_ESTAGIO,NB_VALOR_TRANSPORTE,CS_ESCOLARIDADE,ID_CURSO_ESTAGIO,NB_SEMESTRE,TX_HORA_INICIO,TX_HORA_FINAL,TX_OUTROS_HORARIOS,CS_WINDOWS,CS_WORD,CS_EXCEL,CS_POWERPOINT,CS_INTERNET,CS_CORELDRAW,CS_PHOTOSHOP,CS_WEBDESIGN,CS_AUTOCAD,CS_INGLES,CS_ESPANHOL,CS_FRANCES,CS_ALEMAO,TX_OUTRAS_LINGUAS,TX_OUTROS_REQUISITOS,CS_SEXO,TX_ATIVIDADES,TX_OBSERVACAO,CS_SITUACAO,ID_USUARIO_CADASTRO,ID_USUARIO_ATUALIZACAO,DT_CADASTRO,DT_ATUALIZACAO) values ('1','00001/2013','2','1','402','62','4','pessoa contato2','telefone2','cargo2','teste@gmail.com','endereco2','ponto2','onibus2','3','222',to_date('03/10/13','DD/MM/RR'),'horario2','9','43','99,22','1','121','4','10:00','16:00','outros horario2','1','1',null,null,'1','1',null,'1',null,null,'1',null,'1','asdsad2','outros pre requisitos2','2','a) Atendimento ao público 
b) Auxílio / suporte no processo de atendimento 
c) Auxiliar / Cooperar / no atendimento telefônico prestando informações sobre os serviços da empresa 
d) Levantamento','observacoes2','2','143','143',to_date('02/10/13','DD/MM/RR'),to_date('03/10/13','DD/MM/RR'));
Insert into SEMAD.OFERTA_VAGA (ID_OFERTA_VAGA,TX_CODIGO_OFERTA_VAGA,ID_ORGAO_GESTOR_ESTAGIO,ID_ORGAO_ESTAGIO,ID_QUADRO_VAGAS_ESTAGIO,ID_AGENCIA_ESTAGIO,CS_TIPO_VAGA_ESTAGIO,TX_PESSOA_CONTATO,TX_TELEFONE,TX_CARGO_FUNCAO,TX_EMAIL,TX_ENDERECO,TX_PONTO_REFERENCIA,TX_NUM_ONIBUS,NB_QUANTIDADE,NB_QTDE_EMCAMINHADO,DT_ENTREVISTA,TX_HORARIO,NB_DURACAO_ESTAGIO,ID_BOLSA_ESTAGIO,NB_VALOR_TRANSPORTE,CS_ESCOLARIDADE,ID_CURSO_ESTAGIO,NB_SEMESTRE,TX_HORA_INICIO,TX_HORA_FINAL,TX_OUTROS_HORARIOS,CS_WINDOWS,CS_WORD,CS_EXCEL,CS_POWERPOINT,CS_INTERNET,CS_CORELDRAW,CS_PHOTOSHOP,CS_WEBDESIGN,CS_AUTOCAD,CS_INGLES,CS_ESPANHOL,CS_FRANCES,CS_ALEMAO,TX_OUTRAS_LINGUAS,TX_OUTROS_REQUISITOS,CS_SEXO,TX_ATIVIDADES,TX_OBSERVACAO,CS_SITUACAO,ID_USUARIO_CADASTRO,ID_USUARIO_ATUALIZACAO,DT_CADASTRO,DT_ATUALIZACAO) values ('2','00002/2013','2','223','402','62','2','Andre Teixeira de Sousa','9136-9454','Assessor Técnico II','andre.sousa@pmm.am.gov.br','Rua Buriti Nº 47 Cidade Nova I','Proximo ao Bradesco','408, 300','5','15',to_date('07/10/13','DD/MM/RR'),'8H AS 15H','6','43','99,58','1','61','5','08:00','14:00',null,null,'1','1','1','1','1',null,null,'1','1',null,null,null,null,null,null,'a) Pegar água para os servidores;
b) Buscar impressões;
c) Tirar Xerox;
d) Buscar Café',null,'3','3087','143',to_date('03/10/13','DD/MM/RR'),to_date('03/10/13','DD/MM/RR'));
Insert into SEMAD.OFERTA_VAGA (ID_OFERTA_VAGA,TX_CODIGO_OFERTA_VAGA,ID_ORGAO_GESTOR_ESTAGIO,ID_ORGAO_ESTAGIO,ID_QUADRO_VAGAS_ESTAGIO,ID_AGENCIA_ESTAGIO,CS_TIPO_VAGA_ESTAGIO,TX_PESSOA_CONTATO,TX_TELEFONE,TX_CARGO_FUNCAO,TX_EMAIL,TX_ENDERECO,TX_PONTO_REFERENCIA,TX_NUM_ONIBUS,NB_QUANTIDADE,NB_QTDE_EMCAMINHADO,DT_ENTREVISTA,TX_HORARIO,NB_DURACAO_ESTAGIO,ID_BOLSA_ESTAGIO,NB_VALOR_TRANSPORTE,CS_ESCOLARIDADE,ID_CURSO_ESTAGIO,NB_SEMESTRE,TX_HORA_INICIO,TX_HORA_FINAL,TX_OUTROS_HORARIOS,CS_WINDOWS,CS_WORD,CS_EXCEL,CS_POWERPOINT,CS_INTERNET,CS_CORELDRAW,CS_PHOTOSHOP,CS_WEBDESIGN,CS_AUTOCAD,CS_INGLES,CS_ESPANHOL,CS_FRANCES,CS_ALEMAO,TX_OUTRAS_LINGUAS,TX_OUTROS_REQUISITOS,CS_SEXO,TX_ATIVIDADES,TX_OBSERVACAO,CS_SITUACAO,ID_USUARIO_CADASTRO,ID_USUARIO_ATUALIZACAO,DT_CADASTRO,DT_ATUALIZACAO) values ('3','00003/2013','2','223','402','62','2','PESSOA TESTE','92 91369454','ASSESSOR II','andre.sousa@pmm.am.gov.br','Rua Buriti','ponto2','408','2','6',to_date('10/10/13','DD/MM/RR'),'8 AS 17','6','43','99,4','2','61','5','08:00','14:00',null,'1','1','1',null,null,null,'1','1',null,'1','1','1',null,null,null,'2','a) Atendimento ao publico',null,'3','143','143',to_date('07/10/13','DD/MM/RR'),to_date('07/10/13','DD/MM/RR'));
Insert into SEMAD.OFERTA_VAGA (ID_OFERTA_VAGA,TX_CODIGO_OFERTA_VAGA,ID_ORGAO_GESTOR_ESTAGIO,ID_ORGAO_ESTAGIO,ID_QUADRO_VAGAS_ESTAGIO,ID_AGENCIA_ESTAGIO,CS_TIPO_VAGA_ESTAGIO,TX_PESSOA_CONTATO,TX_TELEFONE,TX_CARGO_FUNCAO,TX_EMAIL,TX_ENDERECO,TX_PONTO_REFERENCIA,TX_NUM_ONIBUS,NB_QUANTIDADE,NB_QTDE_EMCAMINHADO,DT_ENTREVISTA,TX_HORARIO,NB_DURACAO_ESTAGIO,ID_BOLSA_ESTAGIO,NB_VALOR_TRANSPORTE,CS_ESCOLARIDADE,ID_CURSO_ESTAGIO,NB_SEMESTRE,TX_HORA_INICIO,TX_HORA_FINAL,TX_OUTROS_HORARIOS,CS_WINDOWS,CS_WORD,CS_EXCEL,CS_POWERPOINT,CS_INTERNET,CS_CORELDRAW,CS_PHOTOSHOP,CS_WEBDESIGN,CS_AUTOCAD,CS_INGLES,CS_ESPANHOL,CS_FRANCES,CS_ALEMAO,TX_OUTRAS_LINGUAS,TX_OUTROS_REQUISITOS,CS_SEXO,TX_ATIVIDADES,TX_OBSERVACAO,CS_SITUACAO,ID_USUARIO_CADASTRO,ID_USUARIO_ATUALIZACAO,DT_CADASTRO,DT_ATUALIZACAO) values ('4','00001/2014','2','1','402','62','4','rodrigo','876786','programador','rodrigo.cabral@pmm.am.gov.br','av',null,null,'5','10',to_date('19/02/14','DD/MM/RR'),'8h','6','41','50','3','121',null,'08:00:00','13:00:00',null,'1','1','1','1','1','1','1','1',null,'1',null,null,'1',null,null,null,'programa ...',null,'2','3265','143',to_date('19/02/14','DD/MM/RR'),to_date('20/02/14','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index OFERTA_VAGA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."OFERTA_VAGA_PK" ON "SEMAD"."OFERTA_VAGA" ("ID_OFERTA_VAGA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  Constraints for Table OFERTA_VAGA
--------------------------------------------------------

  ALTER TABLE "SEMAD"."OFERTA_VAGA" ADD CONSTRAINT "OFERTA_VAGA_PK" PRIMARY KEY ("ID_OFERTA_VAGA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA"  ENABLE;
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("ID_OFERTA_VAGA" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("TX_CODIGO_OFERTA_VAGA" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("ID_ORGAO_GESTOR_ESTAGIO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("ID_ORGAO_ESTAGIO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("ID_QUADRO_VAGAS_ESTAGIO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("ID_AGENCIA_ESTAGIO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("CS_TIPO_VAGA_ESTAGIO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("TX_PESSOA_CONTATO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("TX_TELEFONE" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("TX_EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("TX_ENDERECO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("NB_QUANTIDADE" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("NB_QTDE_EMCAMINHADO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("DT_ENTREVISTA" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("TX_HORARIO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("ID_BOLSA_ESTAGIO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("NB_VALOR_TRANSPORTE" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("CS_ESCOLARIDADE" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("TX_HORA_INICIO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("TX_HORA_FINAL" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("TX_ATIVIDADES" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("ID_USUARIO_CADASTRO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("ID_USUARIO_ATUALIZACAO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("DT_CADASTRO" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" MODIFY ("DT_ATUALIZACAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table OFERTA_VAGA
--------------------------------------------------------

  ALTER TABLE "SEMAD"."OFERTA_VAGA" ADD CONSTRAINT "OFERTA_VAGA_BOLSA_ESTAGIO_FK1" FOREIGN KEY ("ID_BOLSA_ESTAGIO")
	  REFERENCES "SEMAD"."BOLSA_ESTAGIO" ("ID_BOLSA_ESTAGIO") ENABLE;
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" ADD CONSTRAINT "OFERTA_VAGA_CURSO_ESTAGIO_FK1" FOREIGN KEY ("ID_CURSO_ESTAGIO")
	  REFERENCES "SEMAD"."CURSO_ESTAGIO" ("ID_CURSO_ESTAGIO") ENABLE;
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" ADD CONSTRAINT "OFERTA_VAGA_USUARIO_FK1" FOREIGN KEY ("ID_USUARIO_CADASTRO")
	  REFERENCES "SEMAD"."USUARIO" ("ID_USUARIO") ENABLE;
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" ADD CONSTRAINT "OFERTA_VAGA_USUARIO_FK2" FOREIGN KEY ("ID_USUARIO_ATUALIZACAO")
	  REFERENCES "SEMAD"."USUARIO" ("ID_USUARIO") ENABLE;
 
  ALTER TABLE "SEMAD"."OFERTA_VAGA" ADD CONSTRAINT "OFERTA_VAGA_VAGAS_ESTAGIO_FK1" FOREIGN KEY ("ID_QUADRO_VAGAS_ESTAGIO", "ID_ORGAO_ESTAGIO", "CS_TIPO_VAGA_ESTAGIO", "ID_AGENCIA_ESTAGIO")
	  REFERENCES "SEMAD"."VAGAS_ESTAGIO" ("ID_QUADRO_VAGAS_ESTAGIO", "ID_ORGAO_ESTAGIO", "CS_TIPO_VAGA_ESTAGIO", "ID_AGENCIA_ESTAGIO") ENABLE;
