-- Órgão Gestor, Utilizada no index.php no lookup de Órgão Gestor 

SELECT ID_ORGAO_GESTOR_ESTAGIO,
ID_ORGAO_GESTOR_ESTAGIO CODIGO,
TX_ORGAO_GESTOR_ESTAGIO 
FROM ORGAO_GESTOR_ESTAGIO;

--
SELECT OGE.ID_ORGAO_GESTOR_ESTAGIO,
  OGE.ID_ORGAO_GESTOR_ESTAGIO CODIGO,
  OGE.TX_ORGAO_GESTOR_ESTAGIO,
  UO.TX_UNIDADE_ORG,
  UO.TX_SIGLA_UNIDADE,
  OGE.ID_UNIDADE_ORG,
  UO.ID_UNIDADE_ORG AS ID_UNIDADE_ORG1
FROM ORGAO_GESTOR_ESTAGIO OGE,
  UNIDADE_ORG UO
WHERE OGE.ID_UNIDADE_ORG = UO.ID_UNIDADE_ORG
ORDER BY OGE.TX_ORGAO_GESTOR_ESTAGIO


-- Órgão Solicitante, utilizada no index.php no lookup de Órgão Solicitante

SELECT DISTINCT 
C.ID_ORGAO_ESTAGIO CODIGO,
C.TX_ORGAO_ESTAGIO,
C.ID_ORGAO_ESTAGIO 
FROM AGENTE_SETORIAL_ESTAGIO A ,
ORGAO_AGENTE_SETORIAL B,
ORGAO_ESTAGIO C
WHERE  A.ID_SETORIAL_ESTAGIO = B.ID_SETORIAL_ESTAGIO
AND C.ID_ORGAO_ESTAGIO = B.ID_ORGAO_ESTAGIO
AND A.ID_USUARIO=;
