SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `SEMAD_ESTAGIO`.`VAGAS_ESTAGIO` 
DROP FOREIGN KEY `FK_TIPO_VAGA_ESTAGIO`;

ALTER TABLE `SEMAD_ESTAGIO`.`ORGAO_ESTAGIO` 
DROP INDEX `TX_ORGAO_ESTAGIO_INDEX` ,
DROP INDEX `TX_ORGAO_ESTAGIO_UNIQUE` ;

ALTER TABLE `SEMAD_ESTAGIO`.`VAGAS_ESTAGIO` 
DROP COLUMN `CS_TIPO_VAGA_ESTAGIO`,
ADD COLUMN `CS_TIPO_VAGA_ESTAGIO` INT(11) NOT NULL AFTER `ID_AGENCIA_ESTAGIO`,
ADD INDEX `fk_VAGAS_ESTAGIO_TIPO_VAGA_ESTAGIO1_idx` (`CS_TIPO_VAGA_ESTAGIO` ASC),
DROP INDEX `fk_VAGAS_ESTAGIO_QUADRO_VAGAS_ESTAGIO1` ,
DROP INDEX `FK_TIPO_VAGA_ESTAGIO` ;

ALTER TABLE `SEMAD_ESTAGIO`.`SUPERVISOR_ESTAGIO` 
CHANGE COLUMN `ID_PESSOA_SUPERVISOR` `ID_PESSOA_SUPERVISOR` INT(11) NULL DEFAULT NULL ;

ALTER TABLE `SEMAD_ESTAGIO`.`VAGAS_ESTAGIO` 
ADD CONSTRAINT `fk_VAGAS_ESTAGIO_TIPO_VAGA_ESTAGIO1`
  FOREIGN KEY (`CS_TIPO_VAGA_ESTAGIO`)
  REFERENCES `SEMAD_ESTAGIO`.`TIPO_VAGA_ESTAGIO` (`CS_TIPO_VAGA_ESTAGIO`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
