SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `SEMAD_ESTAGIO` ;
CREATE SCHEMA IF NOT EXISTS `SEMAD_ESTAGIO` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `SEMAD_ESTAGIO` ;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`ORGAO_GESTOR_ESTAGIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`ORGAO_GESTOR_ESTAGIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`ORGAO_GESTOR_ESTAGIO` (
  `ID_ORGAO_GESTOR_ESTAGIO` INT NOT NULL AUTO_INCREMENT,
  `TX_ORGAO_GESTOR_ESTAGIO` VARCHAR(254) NOT NULL,
  `ID_UNIDADE_ORG` INT NULL,
  `TX_CNPJ` VARCHAR(14) NOT NULL,
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  PRIMARY KEY (`ID_ORGAO_GESTOR_ESTAGIO`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`ORGAO_GESTOR_EMAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`ORGAO_GESTOR_EMAIL` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`ORGAO_GESTOR_EMAIL` (
  `ID_ORGAO_GESTOR_ESTAGIO` INT NOT NULL,
  `NB_ORGAO_GESTOR_EMAIL` INT NOT NULL AUTO_INCREMENT,
  `TX_EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`NB_ORGAO_GESTOR_EMAIL`),
  CONSTRAINT `fk_ORGAO_GESTOR_EMAIL_ORGAO_GESTOR_ESTAGIO1`
    FOREIGN KEY (`ID_ORGAO_GESTOR_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`ORGAO_GESTOR_ESTAGIO` (`ID_ORGAO_GESTOR_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`ORGAO_ESTAGIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`ORGAO_ESTAGIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`ORGAO_ESTAGIO` (
  `ID_ORGAO_ESTAGIO` INT NOT NULL AUTO_INCREMENT,
  `TX_ORGAO_ESTAGIO` VARCHAR(254) NOT NULL,
  `TX_CNPJ` VARCHAR(14) NOT NULL,
  `CS_STATUS` INT NOT NULL,
  `ID_UNIDADE_ORG` INT NULL,
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `ID_USUARIO_CADASTRO` INT NOT NULL,
  `ID_USUARIO_ATUALIZACAO` INT NOT NULL,
  PRIMARY KEY (`ID_ORGAO_ESTAGIO`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`AGENTE_SETORIAL_ESTAGIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`AGENTE_SETORIAL_ESTAGIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`AGENTE_SETORIAL_ESTAGIO` (
  `ID_AGENTE_SETORIAL_ESTAGIO` INT NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT NOT NULL,
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `ID_USUARIO_CADASTRO` INT NOT NULL,
  `ID_USUARIO_ATUALIZACAO` INT NOT NULL,
  `TX_EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_AGENTE_SETORIAL_ESTAGIO`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`AGENTE_SETORIAL_EMAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`AGENTE_SETORIAL_EMAIL` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`AGENTE_SETORIAL_EMAIL` (
  `ID_AGENTE_SETORIAL_ESTAGIO` INT NOT NULL,
  `NB_AGENTE_SETORIAL_EMAIL` INT NOT NULL AUTO_INCREMENT,
  `TX_EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`NB_AGENTE_SETORIAL_EMAIL`),
  CONSTRAINT `fk_AGENTE_SETORIAL_EMAIL_AGENTE_SETORIAL_ESTAGIO1`
    FOREIGN KEY (`ID_AGENTE_SETORIAL_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`AGENTE_SETORIAL_ESTAGIO` (`ID_AGENTE_SETORIAL_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`ORGAO_AGENTE_SETORIAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`ORGAO_AGENTE_SETORIAL` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`ORGAO_AGENTE_SETORIAL` (
  `DT_ATUALIZACAO` DATE NOT NULL,
  `ID_AGENTE_SETORIAL_ESTAGIO` INT NOT NULL,
  `ID_ORGAO_ESTAGIO` INT NOT NULL,
  PRIMARY KEY (`ID_ORGAO_ESTAGIO`, `ID_AGENTE_SETORIAL_ESTAGIO`),
  CONSTRAINT `fk_ORGAO_AGENTE_SETORIAL_AGENTE_SETORIAL_ESTAGIO1`
    FOREIGN KEY (`ID_AGENTE_SETORIAL_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`AGENTE_SETORIAL_ESTAGIO` (`ID_AGENTE_SETORIAL_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORGAO_AGENTE_SETORIAL_ORGAO_ESTAGIO1`
    FOREIGN KEY (`ID_ORGAO_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`ORGAO_ESTAGIO` (`ID_ORGAO_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`AGENCIA_ESTAGIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`AGENCIA_ESTAGIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`AGENCIA_ESTAGIO` (
  `ID_AGENCIA_ESTAGIO` INT NOT NULL AUTO_INCREMENT,
  `TX_AGENCIA_ESTAGIO` VARCHAR(254) NOT NULL,
  `TX_CNPJ` VARCHAR(14) NOT NULL,
  `TX_SIGLA` VARCHAR(20) NOT NULL,
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `ID_USUARIO_CADASTRO` INT NOT NULL,
  `ID_USUARIO_ATUALIZACAO` INT NOT NULL,
  `TX_EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_AGENCIA_ESTAGIO`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`AGENCIA_ESTAGIO_EMAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`AGENCIA_ESTAGIO_EMAIL` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`AGENCIA_ESTAGIO_EMAIL` (
  `ID_AGENCIA_ESTAGIO` INT NOT NULL,
  `NB_AGENCIA_ESTAGIO_EMAIL` INT NOT NULL AUTO_INCREMENT,
  `TX_EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`NB_AGENCIA_ESTAGIO_EMAIL`),
  CONSTRAINT `fk_AGENCIA_ESTAGIO_EMAIL_AGENCIA_ESTAGIO1`
    FOREIGN KEY (`ID_AGENCIA_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`AGENCIA_ESTAGIO` (`ID_AGENCIA_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'AGENTE DE INTEGRAÇÃO';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`INSTITUICAO_ENSINO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`INSTITUICAO_ENSINO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`INSTITUICAO_ENSINO` (
  `CS_INSTITUICAO_ENSINO` INT NOT NULL,
  `TX_INSTITUICAO_ENSINO` VARCHAR(254) NOT NULL,
  `TX_SIGLA` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`CS_INSTITUICAO_ENSINO`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`AREA_CONHECIMENTO_GE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`AREA_CONHECIMENTO_GE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`AREA_CONHECIMENTO_GE` (
  `CS_AREA_CONHECIMENTO` INT NOT NULL,
  `TX_AREA_CONHECIMENTO` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`CS_AREA_CONHECIMENTO`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`CURSO_ESTAGIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`CURSO_ESTAGIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`CURSO_ESTAGIO` (
  `ID_CURSO_ESTAGIO` INT NOT NULL AUTO_INCREMENT,
  `TX_CURSO_ESTAGIO` VARCHAR(254) NOT NULL,
  `CS_AREA_CONHECIMENTO` INT NOT NULL,
  PRIMARY KEY (`ID_CURSO_ESTAGIO`),
  CONSTRAINT `fk_CURSO_ESTAGIO_AREA_CONHECIMENTO_GE1`
    FOREIGN KEY (`CS_AREA_CONHECIMENTO`)
    REFERENCES `SEMAD_ESTAGIO`.`AREA_CONHECIMENTO_GE` (`CS_AREA_CONHECIMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`QUADRO_VAGAS_ESTAGIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`QUADRO_VAGAS_ESTAGIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`QUADRO_VAGAS_ESTAGIO` (
  `ID_QUADRO_VAGAS_ESTAGIO` INT NOT NULL AUTO_INCREMENT,
  `CS_SITUACAO` INT NOT NULL,
  `TX_CODIGO` VARCHAR(20) NOT NULL,
  `ID_CONTRATO_CP` VARCHAR(45) NULL,
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `ID_USUARIO_CADASTRO` INT NOT NULL,
  `ID_USUARIO_ATUALIZACAO` INT NOT NULL,
  `ID_ORGAO_GESTOR_ESTAGIO` INT NOT NULL,
  PRIMARY KEY (`ID_QUADRO_VAGAS_ESTAGIO`),
  CONSTRAINT `fk_QUADRO_VAGAS_ESTAGIO_ORGAO_GESTOR_ESTAGIO1`
    FOREIGN KEY (`ID_ORGAO_GESTOR_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`ORGAO_GESTOR_ESTAGIO` (`ID_ORGAO_GESTOR_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`TIPO_VAGA_ESTAGIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`TIPO_VAGA_ESTAGIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`TIPO_VAGA_ESTAGIO` (
  `CS_TIPO_VAGA_ESTAGIO` INT NOT NULL,
  `TX_TIPO_VAGA_ESTAGIO` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`CS_TIPO_VAGA_ESTAGIO`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`VAGAS_ESTAGIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`VAGAS_ESTAGIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`VAGAS_ESTAGIO` (
  `NB_VAGAS_ESTAGIO` INT NOT NULL AUTO_INCREMENT,
  `ID_QUADRO_VAGAS_ESTAGIO` INT NOT NULL,
  `ID_ORGAO_ESTAGIO` INT NOT NULL,
  `ID_AGENCIA_ESTAGIO` INT NOT NULL,
  `CS_TIPO_VAGA_ESTAGIO` INT NOT NULL,
  `NB_QUANTIDADE` INT NOT NULL,
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `ID_USUARIO_CADASTRO` INT NOT NULL,
  `ID_USUARIO_ATUALIZACAO` INT NOT NULL,
  PRIMARY KEY (`NB_VAGAS_ESTAGIO`),
  CONSTRAINT `fk_VAGAS_ESTAGIO_AGENCIA_ESTAGIO1`
    FOREIGN KEY (`ID_AGENCIA_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`AGENCIA_ESTAGIO` (`ID_AGENCIA_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VAGAS_ESTAGIO_QUADRO_VAGAS_ESTAGIO1`
    FOREIGN KEY (`ID_QUADRO_VAGAS_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`QUADRO_VAGAS_ESTAGIO` (`ID_QUADRO_VAGAS_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VAGAS_ESTAGIO_ORGAO_ESTAGIO1`
    FOREIGN KEY (`ID_ORGAO_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`ORGAO_ESTAGIO` (`ID_ORGAO_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VAGAS_ESTAGIO_TIPO_VAGA_ESTAGIO1`
    FOREIGN KEY (`CS_TIPO_VAGA_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`TIPO_VAGA_ESTAGIO` (`CS_TIPO_VAGA_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`CONSELHO_PROFISSIONAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`CONSELHO_PROFISSIONAL` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`CONSELHO_PROFISSIONAL` (
  `ID_CONSELHO_PROFISSIONAL` INT NOT NULL AUTO_INCREMENT,
  `TX_CONSELHO_PROFISSIONAL` VARCHAR(80) NOT NULL,
  `TX_SIGLA` VARCHAR(20) NOT NULL,
  `CONSELHO_PROFISSIONALcol` VARCHAR(20) NOT NULL,
  `ID_UF` INT NULL,
  PRIMARY KEY (`ID_CONSELHO_PROFISSIONAL`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`PESSOA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`PESSOA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`PESSOA` (
  `ID_PESSOA` INT NOT NULL AUTO_INCREMENT,
  `TX_NOME` VARCHAR(80) NOT NULL,
  `CS_TIPO_PESSOA` INT NOT NULL,
  PRIMARY KEY (`ID_PESSOA`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`PESSOA_FISICA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`PESSOA_FISICA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`PESSOA_FISICA` (
  `ID_PESSOA` INT NOT NULL,
  `DT_NASCIMENTO` DATE NOT NULL,
  `NB_CPF` VARCHAR(11) NOT NULL,
  `NB_RG` VARCHAR(20) NULL,
  `CS_SEXO` INT NULL,
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  PRIMARY KEY (`ID_PESSOA`),
  CONSTRAINT `fk_PESSOA_FISICA_PESSOA1`
    FOREIGN KEY (`ID_PESSOA`)
    REFERENCES `SEMAD_ESTAGIO`.`PESSOA` (`ID_PESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`FUNCIONARIO_PE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`FUNCIONARIO_PE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`FUNCIONARIO_PE` (
  `ID_PESSOA_FUNCIONARIO` INT NOT NULL,
  `NB_FUNCIONARIO` INT NOT NULL AUTO_INCREMENT,
  `ID_UNIDADE_GESTORA` INT NULL,
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `TX_NOME_GUERRA` VARCHAR(80) NOT NULL,
  `BL_FOTO` BLOB NULL,
  `CS_TIPO_FUNCIONARIO_PE` INT NOT NULL,
  `CS_SITUACAO_FUNCIONARIO` INT NULL,
  PRIMARY KEY (`NB_FUNCIONARIO`, `ID_PESSOA_FUNCIONARIO`),
  CONSTRAINT `fk_FUNCIONARIO_PE_PESSOA_FISICA1`
    FOREIGN KEY (`ID_PESSOA_FUNCIONARIO`)
    REFERENCES `SEMAD_ESTAGIO`.`PESSOA_FISICA` (`ID_PESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`SUPERVISOR_ESTAGIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`SUPERVISOR_ESTAGIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`SUPERVISOR_ESTAGIO` (
  `ID_PESSOA_SUPERVISOR` INT NULL,
  `TX_FORMACAO` VARCHAR(254) NOT NULL,
  `TX_CARGO` VARCHAR(254) NOT NULL,
  `TX_TEMPO_EXPERIENCIA` VARCHAR(45) NOT NULL,
  `TX_EMAIL` VARCHAR(20) NOT NULL,
  `TX_CURRICULO` VARCHAR(2000) NOT NULL,
  `NB_INSCRICAO_CONSELHO` VARCHAR(80) NOT NULL,
  `ID_CONSELHO_PROFISSIONAL` INT NOT NULL,
  `ID_PESSOA_FUNCIONARIO` INT NOT NULL,
  `NB_FUNCIONARIO` INT NOT NULL,
  PRIMARY KEY (`ID_PESSOA_SUPERVISOR`),
  CONSTRAINT `FK_CONSELHO_PROFISSIONAL`
    FOREIGN KEY (`ID_CONSELHO_PROFISSIONAL`)
    REFERENCES `SEMAD_ESTAGIO`.`CONSELHO_PROFISSIONAL` (`ID_CONSELHO_PROFISSIONAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUPERVISOR_ESTAGIO_FUNCIONARIO_PE1`
    FOREIGN KEY (`NB_FUNCIONARIO` , `ID_PESSOA_FUNCIONARIO`)
    REFERENCES `SEMAD_ESTAGIO`.`FUNCIONARIO_PE` (`NB_FUNCIONARIO` , `ID_PESSOA_FUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`VAGAS_CURSO_ESTAGIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`VAGAS_CURSO_ESTAGIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`VAGAS_CURSO_ESTAGIO` (
  `NB_VAGAS_ESTAGIO` INT NOT NULL,
  `ID_CURSO_ESTAGIO` INT NOT NULL,
  `NB_QUANTIDADE` INT NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  PRIMARY KEY (`NB_VAGAS_ESTAGIO`, `ID_CURSO_ESTAGIO`),
  CONSTRAINT `fk_VAGAS_CURSO_ESTAGIO_VAGAS_ESTAGIO1`
    FOREIGN KEY (`NB_VAGAS_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`VAGAS_ESTAGIO` (`NB_VAGAS_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VAGAS_CURSO_ESTAGIO_CURSO_ESTAGIO1`
    FOREIGN KEY (`ID_CURSO_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`CURSO_ESTAGIO` (`ID_CURSO_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`OFERTA_VAGA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`OFERTA_VAGA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`OFERTA_VAGA` (
  `ID_OFERTA_VAGA` INT NOT NULL AUTO_INCREMENT,
  `TX_CODIGO_OFERTA_VAGA` VARCHAR(20) NOT NULL,
  `TX_PESSOA_CONTATO` VARCHAR(100) NOT NULL,
  `TX_TELEFONE` VARCHAR(20) NOT NULL,
  `TX_CARGO_FUNCAO` VARCHAR(100) NULL,
  `TX_EMAIL` VARCHAR(100) NOT NULL,
  `TX_ENDERECO` VARCHAR(200) NOT NULL,
  `TX_PONTO_REFERENCIA` VARCHAR(100) NULL,
  `TX_NUM_ONIBUS` VARCHAR(20) NULL,
  `NB_QUANTIDADE` INT NOT NULL,
  `NB_QTDE_EMCAMINHADO` INT NOT NULL,
  `DT_ENTREVISTA` DATE NOT NULL,
  `TX_HORARIO` VARCHAR(20) NOT NULL,
  `NB_DURACAO_ESTAGIO` INT NULL,
  `NB_VALOR_TRANSPORTE` INT NOT NULL,
  `CS_ESCOLARIDADE` INT NOT NULL COMMENT '1-MEDIO, 2-TECNICO, 3-SUPERIOR',
  `NB_SEMESTRE` INT NULL,
  `TX_HORA_INICIO` VARCHAR(20) NOT NULL,
  `TX_HORA_FINAL` VARCHAR(20) NOT NULL,
  `TX_OUTROS_HORARIOS` VARCHAR(100) NULL,
  `CS_WINDOWS` INT NULL,
  `CS_WORD` INT NULL,
  `CS_EXCEL` INT NULL,
  `CS_POWERPOINT` INT NULL,
  `CS_INTERNET` INT NULL,
  `CS_CORELDRAW` INT NULL,
  `CS_PHOTOSHOP` INT NULL,
  `CS_AUTOCAD` INT NULL,
  `CS_WEBDESIGN` INT NULL,
  `CS_INGLES` INT NULL,
  `CS_ESPANHOL` INT NULL,
  `CS_FRANCES` INT NULL,
  `CS_ALEMAO` INT NULL,
  `TX_OUTRAS_LINGUAS` VARCHAR(100) NULL,
  `TX_OUTROS_REQUISITOS` VARCHAR(100) NULL,
  `CS_SEXO` INT NULL COMMENT '1-MASCULINO, 2-FEMININO',
  `TX_ATIVIDADES` VARCHAR(400) NOT NULL,
  `CS_SITUACAO` VARCHAR(45) NOT NULL COMMENT '1-Aberta, 2-Efetivada, 3-Oferta Encaminhada, 4-Cancelada',
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `ID_USUARIO_CADASTRO` INT NOT NULL,
  `ID_USUARIO_ATUALIZACAO` INT NOT NULL,
  `NB_VAGAS_ESTAGIO` INT NOT NULL,
  `ID_CURSO_ESTAGIO` INT NULL,
  PRIMARY KEY (`ID_OFERTA_VAGA`),
  CONSTRAINT `fk_OFERTA_VAGA_VAGAS_CURSO_ESTAGIO1`
    FOREIGN KEY (`NB_VAGAS_ESTAGIO` , `ID_CURSO_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`VAGAS_CURSO_ESTAGIO` (`NB_VAGAS_ESTAGIO` , `ID_CURSO_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`BOLSA_ESTAGIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`BOLSA_ESTAGIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`BOLSA_ESTAGIO` (
  `CS_TIPO_VAGA_ESTAGIO` INT NOT NULL,
  `NB_BOLSA_ESTAGIO` INT NOT NULL AUTO_INCREMENT,
  `NB_VALOR` INT NOT NULL,
  PRIMARY KEY (`NB_BOLSA_ESTAGIO`, `CS_TIPO_VAGA_ESTAGIO`),
  CONSTRAINT `fk_BOLSA_ESTAGIO_TIPO_VAGA_ESTAGIO1`
    FOREIGN KEY (`CS_TIPO_VAGA_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`TIPO_VAGA_ESTAGIO` (`CS_TIPO_VAGA_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`SELECAO_ESTAGIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`SELECAO_ESTAGIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`SELECAO_ESTAGIO` (
  `ID_SELECAO_ESTAGIO` INT NOT NULL AUTO_INCREMENT,
  `TX_COD_SELECAO` VARCHAR(20) NOT NULL,
  `ID_OFERTA_VAGA` INT NOT NULL,
  `CS_SITUACAO` INT NOT NULL COMMENT '1-Aberta, 2-Efetivada, 3-Seleção Encaminhada, 4-Cancelada',
  `CS_SELECAO` INT NOT NULL COMMENT '1-com oferta, 2-sem oferta',
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `ID_USUARIO_CADASTRO` INT NOT NULL,
  `ID_USUARIO_ATUALIZACAO` INT NOT NULL,
  PRIMARY KEY (`ID_SELECAO_ESTAGIO`),
  CONSTRAINT `fk_SELECAO_ESTAGIO_OFERTA_VAGA1`
    FOREIGN KEY (`ID_OFERTA_VAGA`)
    REFERENCES `SEMAD_ESTAGIO`.`OFERTA_VAGA` (`ID_OFERTA_VAGA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`ESTAGIARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`ESTAGIARIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`ESTAGIARIO` (
  `NB_ESTAGIARIO` INT NOT NULL AUTO_INCREMENT,
  `ID_PESSOA_ESTAGIARIO` INT NOT NULL,
  `ID_PESSOA_FUNCIONARIO` INT NULL,
  `NB_FUNCIONARIO` INT NULL,
  `TX_CEP` VARCHAR(10) NULL,
  `TX_ENDERECO` VARCHAR(254) NULL,
  `NB_NUMERO` INT NULL,
  `TX_COMPLEMENTO` VARCHAR(254) NULL,
  `TX_BAIRRO` VARCHAR(100) NULL,
  `NB_ZONA` INT NULL,
  `TX_CONTATO` VARCHAR(200) NULL,
  `TX_EMAIL` VARCHAR(100) NULL,
  `TX_AGENCIA_BANCO` VARCHAR(20) NULL,
  `TX_CONTA_CORRENTE` VARCHAR(20) NULL,
  `CS_SITUACAO` INT NULL,
  PRIMARY KEY (`NB_ESTAGIARIO`, `ID_PESSOA_ESTAGIARIO`),
  CONSTRAINT `fk_ESTAGIARIO_PESSOA1`
    FOREIGN KEY (`ID_PESSOA_ESTAGIARIO`)
    REFERENCES `SEMAD_ESTAGIO`.`PESSOA` (`ID_PESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`ESTAGIARIO_SELECAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`ESTAGIARIO_SELECAO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`ESTAGIARIO_SELECAO` (
  `ID_SELECAO_ESTAGIO` INT NOT NULL,
  `CS_SITUACAO` INT NOT NULL,
  `TX_MOTIVO_SITUACAO` VARCHAR(254) NULL,
  `CS_ESCOLARIDADE` INT NULL,
  `ID_CURSO_ESTAGIO` INT NULL,
  `NB_PERIODO_ANO` INT NULL,
  `CS_TURNO` INT NULL,
  `TX_HORA_INICIO` VARCHAR(20) NULL,
  `TX_HORA_FINAL` VARCHAR(20) NULL,
  `CS_CARGA_HORARIA` INT NULL,
  `TX_ATIVIDADES` VARCHAR(400) NULL,
  `NB_VALOR_TRANSPORTE` INT NULL,
  `TX_LOCAL_ESTAGIO` VARCHAR(254) NULL,
  `DT_INICIO` DATE NULL,
  `DT_FINAL` DATE NULL,
  `NB_ESTAGIARIO` INT NOT NULL,
  `ID_PESSOA_ESTAGIARIO` INT NULL,
  PRIMARY KEY (`ID_SELECAO_ESTAGIO`),
  CONSTRAINT `fk_ESTAGIARIO_SELECAO_SELECAO_ESTAGIO1`
    FOREIGN KEY (`ID_SELECAO_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`SELECAO_ESTAGIO` (`ID_SELECAO_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTAGIARIO_SELECAO_ESTAGIARIO1`
    FOREIGN KEY (`NB_ESTAGIARIO` , `ID_PESSOA_ESTAGIARIO`)
    REFERENCES `SEMAD_ESTAGIO`.`ESTAGIARIO` (`NB_ESTAGIARIO` , `ID_PESSOA_ESTAGIARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`ESTAGIARIO2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`ESTAGIARIO2` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`ESTAGIARIO2` (
  `ID_PESSOA_ESTAGIARIO` INT NOT NULL,
  `ID_PESSOA_FUNCIONARIO` INT NULL,
  `NB_FUNCIONARIO` INT NULL,
  `TX_CEP` VARCHAR(10) NULL,
  `TX_ENDERECO` VARCHAR(254) NULL,
  `NB_NUMERO` INT NULL,
  `TX_COMPLEMENTO` VARCHAR(254) NULL,
  `TX_BAIRRO` VARCHAR(100) NULL,
  `TX_CONTATO` VARCHAR(200) NULL,
  `TX_EMAIL` VARCHAR(100) NULL,
  `TX_AGENCIA_BANCO` VARCHAR(20) NULL,
  `TX_CONTA_CORRENTE` VARCHAR(20) NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SEMAD_ESTAGIO`.`ESTAGIARIO_ESCOLARIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SEMAD_ESTAGIO`.`ESTAGIARIO_ESCOLARIDADE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`ESTAGIARIO_ESCOLARIDADE` (
  `ESTAGIARIO_NB_ESTAGIARIO` INT NOT NULL,
  `ESTAGIARIO_ID_PESSOA_ESTAGIARIO` INT NULL,
  `CS_ESCOLARIDADE` INT NULL,
  `ID_CURSO_ESTAGIO` INT NULL,
  `NB_PERIODO_ANO` INT NULL,
  `CS_TURNO` INT NULL,
  CONSTRAINT `fk_ESTAGIARIO_ESCOLARIDADE_ESTAGIARIO1`
    FOREIGN KEY (`ESTAGIARIO_NB_ESTAGIARIO` , `ESTAGIARIO_ID_PESSOA_ESTAGIARIO`)
    REFERENCES `SEMAD_ESTAGIO`.`ESTAGIARIO` (`NB_ESTAGIARIO` , `ID_PESSOA_ESTAGIARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
