SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `SEMAD_ESTAGIO`.`ORGAO_GESTOR_EMAIL` 
ADD INDEX `fk_ORGAO_GESTOR_EMAIL_ORGAO_GESTOR_ESTAGIO1_idx` (`ID_ORGAO_GESTOR_ESTAGIO` ASC),
DROP INDEX `fk_ORGAO_GESTOR_EMAIL_ORGAO_GESTOR_ESTAGIO1` ;

ALTER TABLE `SEMAD_ESTAGIO`.`AGENTE_SETORIAL_EMAIL` 
ADD INDEX `fk_AGENTE_SETORIAL_EMAIL_AGENTE_SETORIAL_ESTAGIO1_idx` (`ID_AGENTE_SETORIAL_ESTAGIO` ASC),
DROP INDEX `fk_AGENTE_SETORIAL_EMAIL_AGENTE_SETORIAL_ESTAGIO1` ;

ALTER TABLE `SEMAD_ESTAGIO`.`ORGAO_AGENTE_SETORIAL` 
ADD INDEX `fk_ORGAO_AGENTE_SETORIAL_AGENTE_SETORIAL_ESTAGIO1_idx` (`ID_AGENTE_SETORIAL_ESTAGIO` ASC),
ADD INDEX `fk_ORGAO_AGENTE_SETORIAL_ORGAO_ESTAGIO1_idx` (`ID_ORGAO_ESTAGIO` ASC),
DROP INDEX `fk_ORGAO_AGENTE_SETORIAL_AGENTE_SETORIAL_ESTAGIO1` ;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`AGENCIA_ESTAGIO_EMAIL` (
  `ID_AGENCIA_ESTAGIO` INT(11) NOT NULL,
  `NB_AGENCIA_ESTAGIO_EMAIL` INT(11) NOT NULL AUTO_INCREMENT,
  `TX_EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`NB_AGENCIA_ESTAGIO_EMAIL`),
  INDEX `fk_AGENCIA_ESTAGIO_EMAIL_AGENCIA_ESTAGIO1_idx` (`ID_AGENCIA_ESTAGIO` ASC),
  CONSTRAINT `fk_AGENCIA_ESTAGIO_EMAIL_AGENCIA_ESTAGIO1`
    FOREIGN KEY (`ID_AGENCIA_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`AGENCIA_ESTAGIO` (`ID_AGENCIA_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'AGENTE DE INTEGRAÇÃO';

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`INSTITUICAO_ENSINO` (
  `CS_INSTITUICAO_ENSINO` INT(11) NOT NULL,
  `TX_INSTITUICAO_ENSINO` VARCHAR(254) NOT NULL,
  `TX_SIGLA` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`CS_INSTITUICAO_ENSINO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`AREA_CONHECIMENTO_GE` (
  `CS_AREA_CONHECIMENTO` INT(11) NOT NULL,
  `TX_AREA_CONHECIMENTO` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`CS_AREA_CONHECIMENTO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`CURSO_ESTAGIO` (
  `ID_CURSO_ESTAGIO` INT(11) NOT NULL AUTO_INCREMENT,
  `TX_CURSO_ESTAGIO` VARCHAR(254) NOT NULL,
  `CS_AREA_CONHECIMENTO` INT(11) NOT NULL,
  PRIMARY KEY (`ID_CURSO_ESTAGIO`),
  INDEX `fk_CURSO_ESTAGIO_AREA_CONHECIMENTO_GE1_idx` (`CS_AREA_CONHECIMENTO` ASC),
  CONSTRAINT `fk_CURSO_ESTAGIO_AREA_CONHECIMENTO_GE1`
    FOREIGN KEY (`CS_AREA_CONHECIMENTO`)
    REFERENCES `SEMAD_ESTAGIO`.`AREA_CONHECIMENTO_GE` (`CS_AREA_CONHECIMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`QUADRO_VAGAS_ESTAGIO` (
  `ID_QUADRO_VAGAS_ESTAGIO` INT(11) NOT NULL AUTO_INCREMENT,
  `CS_SITUACAO` INT(11) NOT NULL,
  `TX_CODIGO` VARCHAR(20) NOT NULL,
  `ID_CONTRATO_CP` VARCHAR(45) NULL DEFAULT NULL,
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `ID_USUARIO_CADASTRO` INT(11) NOT NULL,
  `ID_USUARIO_ATUALIZACAO` INT(11) NOT NULL,
  `ID_ORGAO_GESTOR_ESTAGIO` INT(11) NOT NULL,
  PRIMARY KEY (`ID_QUADRO_VAGAS_ESTAGIO`),
  INDEX `fk_QUADRO_VAGAS_ESTAGIO_ORGAO_GESTOR_ESTAGIO1_idx` (`ID_ORGAO_GESTOR_ESTAGIO` ASC),
  CONSTRAINT `fk_QUADRO_VAGAS_ESTAGIO_ORGAO_GESTOR_ESTAGIO1`
    FOREIGN KEY (`ID_ORGAO_GESTOR_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`ORGAO_GESTOR_ESTAGIO` (`ID_ORGAO_GESTOR_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`VAGAS_ESTAGIO` (
  `NB_VAGAS_ESTAGIO` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_QUADRO_VAGAS_ESTAGIO` INT(11) NOT NULL,
  `ID_ORGAO_ESTAGIO` INT(11) NOT NULL,
  `ID_AGENCIA_ESTAGIO` INT(11) NOT NULL,
  `CS_TIPO_VAGA_ESTAGIO` INT(11) NOT NULL,
  `NB_QUANTIDADE` INT(11) NOT NULL,
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `ID_USUARIO_CADASTRO` INT(11) NOT NULL,
  `ID_USUARIO_ATUALIZACAO` INT(11) NOT NULL,
  INDEX `FK_TIPO_VAGA_ESTAGIO` (`CS_TIPO_VAGA_ESTAGIO` ASC),
  INDEX `fk_VAGAS_ESTAGIO_AGENCIA_ESTAGIO1_idx` (`ID_AGENCIA_ESTAGIO` ASC),
  INDEX `fk_VAGAS_ESTAGIO_ORGAO_ESTAGIO1_idx` (`ID_ORGAO_ESTAGIO` ASC),
  PRIMARY KEY (`NB_VAGAS_ESTAGIO`),
  CONSTRAINT `FK_TIPO_VAGA_ESTAGIO`
    FOREIGN KEY (`CS_TIPO_VAGA_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`TIPO_VAGA_ESTAGIO` (`CS_TIPO_VAGA_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VAGAS_ESTAGIO_AGENCIA_ESTAGIO1`
    FOREIGN KEY (`ID_AGENCIA_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`AGENCIA_ESTAGIO` (`ID_AGENCIA_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VAGAS_ESTAGIO_QUADRO_VAGAS_ESTAGIO1`
    FOREIGN KEY (`ID_QUADRO_VAGAS_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`QUADRO_VAGAS_ESTAGIO` (`ID_QUADRO_VAGAS_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VAGAS_ESTAGIO_ORGAO_ESTAGIO1`
    FOREIGN KEY (`ID_ORGAO_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`ORGAO_ESTAGIO` (`ID_ORGAO_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`TIPO_VAGA_ESTAGIO` (
  `CS_TIPO_VAGA_ESTAGIO` INT(11) NOT NULL,
  `TX_TIPO_VAGA_ESTAGIO` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`CS_TIPO_VAGA_ESTAGIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`SUPERVISOR_ESTAGIO` (
  `ID_PESSOA_SUPERVISOR` INT(11) NULL DEFAULT NULL,
  `TX_FORMACAO` VARCHAR(254) NOT NULL,
  `TX_CARGO` VARCHAR(254) NOT NULL,
  `TX_TEMPO_EXPERIENCIA` VARCHAR(45) NOT NULL,
  `TX_EMAIL` VARCHAR(20) NOT NULL,
  `TX_CURRICULO` VARCHAR(2000) NOT NULL,
  `NB_INSCRICAO_CONSELHO` VARCHAR(80) NOT NULL,
  `ID_CONSELHO_PROFISSIONAL` INT(11) NOT NULL,
  `ID_PESSOA_FUNCIONARIO` INT(11) NOT NULL,
  `NB_FUNCIONARIO` INT(11) NOT NULL,
  INDEX `FK_CONSELHO_PROFISSIONAL` (`ID_CONSELHO_PROFISSIONAL` ASC),
  PRIMARY KEY (`ID_PESSOA_SUPERVISOR`),
  INDEX `fk_SUPERVISOR_ESTAGIO_FUNCIONARIO_PE1_idx` (`NB_FUNCIONARIO` ASC, `ID_PESSOA_FUNCIONARIO` ASC),
  CONSTRAINT `FK_CONSELHO_PROFISSIONAL`
    FOREIGN KEY (`ID_CONSELHO_PROFISSIONAL`)
    REFERENCES `SEMAD_ESTAGIO`.`CONSELHO_PROFISSIONAL` (`ID_CONSELHO_PROFISSIONAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUPERVISOR_ESTAGIO_FUNCIONARIO_PE1`
    FOREIGN KEY (`NB_FUNCIONARIO` , `ID_PESSOA_FUNCIONARIO`)
    REFERENCES `SEMAD_ESTAGIO`.`FUNCIONARIO_PE` (`NB_FUNCIONARIO` , `ID_PESSOA_FUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`CONSELHO_PROFISSIONAL` (
  `ID_CONSELHO_PROFISSIONAL` INT(11) NOT NULL AUTO_INCREMENT,
  `TX_CONSELHO_PROFISSIONAL` VARCHAR(80) NOT NULL,
  `TX_SIGLA` VARCHAR(20) NOT NULL,
  `CONSELHO_PROFISSIONALcol` VARCHAR(20) NOT NULL,
  `ID_UF` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CONSELHO_PROFISSIONAL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`OFERTA_VAGA` (
  `ID_OFERTA_VAGA` INT(11) NOT NULL AUTO_INCREMENT,
  `TX_CODIGO_OFERTA_VAGA` VARCHAR(20) NOT NULL,
  `TX_PESSOA_CONTATO` VARCHAR(100) NOT NULL,
  `TX_TELEFONE` VARCHAR(20) NOT NULL,
  `TX_CARGO_FUNCAO` VARCHAR(100) NULL DEFAULT NULL,
  `TX_EMAIL` VARCHAR(100) NOT NULL,
  `TX_ENDERECO` VARCHAR(200) NOT NULL,
  `TX_PONTO_REFERENCIA` VARCHAR(100) NULL DEFAULT NULL,
  `TX_NUM_ONIBUS` VARCHAR(20) NULL DEFAULT NULL,
  `NB_QUANTIDADE` INT(11) NOT NULL,
  `NB_QTDE_EMCAMINHADO` INT(11) NOT NULL,
  `DT_ENTREVISTA` DATE NOT NULL,
  `TX_HORARIO` VARCHAR(20) NOT NULL,
  `NB_DURACAO_ESTAGIO` INT(11) NULL DEFAULT NULL,
  `NB_VALOR_TRANSPORTE` INT(11) NOT NULL,
  `CS_ESCOLARIDADE` INT(11) NOT NULL COMMENT '1-MEDIO, 2-TECNICO, 3-SUPERIOR',
  `NB_SEMESTRE` INT(11) NULL DEFAULT NULL,
  `TX_HORA_INICIO` VARCHAR(20) NOT NULL,
  `TX_HORA_FINAL` VARCHAR(20) NOT NULL,
  `TX_OUTROS_HORARIOS` VARCHAR(100) NULL DEFAULT NULL,
  `CS_WINDOWS` INT(11) NULL DEFAULT NULL,
  `CS_WORD` INT(11) NULL DEFAULT NULL,
  `CS_EXCEL` INT(11) NULL DEFAULT NULL,
  `CS_POWERPOINT` INT(11) NULL DEFAULT NULL,
  `CS_INTERNET` INT(11) NULL DEFAULT NULL,
  `CS_CORELDRAW` INT(11) NULL DEFAULT NULL,
  `CS_PHOTOSHOP` INT(11) NULL DEFAULT NULL,
  `CS_AUTOCAD` INT(11) NULL DEFAULT NULL,
  `CS_WEBDESIGN` INT(11) NULL DEFAULT NULL,
  `CS_INGLES` INT(11) NULL DEFAULT NULL,
  `CS_ESPANHOL` INT(11) NULL DEFAULT NULL,
  `CS_FRANCES` INT(11) NULL DEFAULT NULL,
  `CS_ALEMAO` INT(11) NULL DEFAULT NULL,
  `TX_OUTRAS_LINGUAS` VARCHAR(100) NULL DEFAULT NULL,
  `TX_OUTROS_REQUISITOS` VARCHAR(100) NULL DEFAULT NULL,
  `CS_SEXO` INT(11) NULL DEFAULT NULL COMMENT '1-MASCULINO, 2-FEMININO',
  `TX_ATIVIDADES` VARCHAR(400) NOT NULL,
  `CS_SITUACAO` VARCHAR(45) NOT NULL COMMENT '1-Aberta, 2-Efetivada, 3-Oferta Encaminhada, 4-Cancelada',
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `ID_USUARIO_CADASTRO` INT(11) NOT NULL,
  `ID_USUARIO_ATUALIZACAO` INT(11) NOT NULL,
  PRIMARY KEY (`ID_OFERTA_VAGA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`BOLSA_ESTAGIO` (
  `CS_TIPO_VAGA_ESTAGIO` INT(11) NOT NULL,
  `NB_BOLSA_ESTAGIO` INT(11) NOT NULL AUTO_INCREMENT,
  `NB_VALOR` INT(11) NOT NULL,
  PRIMARY KEY (`NB_BOLSA_ESTAGIO`, `CS_TIPO_VAGA_ESTAGIO`),
  INDEX `fk_BOLSA_ESTAGIO_TIPO_VAGA_ESTAGIO1_idx` (`CS_TIPO_VAGA_ESTAGIO` ASC),
  CONSTRAINT `fk_BOLSA_ESTAGIO_TIPO_VAGA_ESTAGIO1`
    FOREIGN KEY (`CS_TIPO_VAGA_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`TIPO_VAGA_ESTAGIO` (`CS_TIPO_VAGA_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`SELECAO_ESTAGIO` (
  `ID_SELECAO_ESTAGIO` INT(11) NOT NULL AUTO_INCREMENT,
  `TX_COD_SELECAO` VARCHAR(20) NOT NULL,
  `CS_SITUACAO` INT(11) NOT NULL COMMENT '1-Aberta, 2-Efetivada, 3-Seleção Encaminhada, 4-Cancelada',
  `CS_SELECAO` INT(11) NOT NULL COMMENT '1-com oferta, 2-sem oferta',
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `ID_USUARIO_CADASTRO` INT(11) NOT NULL,
  `ID_USUARIO_ATUALIZACAO` INT(11) NOT NULL,
  PRIMARY KEY (`ID_SELECAO_ESTAGIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`ESTAGIARIO_SELECAO` (
  `ID_SELECAO_ESTAGIO` INT(11) NOT NULL,
  `CS_SITUACAO` INT(11) NOT NULL,
  `TX_MOTIVO_SITUACAO` VARCHAR(254) NULL DEFAULT NULL,
  `CS_ESCOLARIDADE` INT(11) NULL DEFAULT NULL,
  `ID_CURSO_ESTAGIO` INT(11) NULL DEFAULT NULL,
  `NB_PERIODO_ANO` INT(11) NULL DEFAULT NULL,
  `CS_TURNO` INT(11) NULL DEFAULT NULL,
  `TX_HORA_INICIO` VARCHAR(20) NULL DEFAULT NULL,
  `TX_HORA_FINAL` VARCHAR(20) NULL DEFAULT NULL,
  `CS_CARGA_HORARIA` INT(11) NULL DEFAULT NULL,
  `TX_ATIVIDADES` VARCHAR(400) NULL DEFAULT NULL,
  `NB_VALOR_TRANSPORTE` INT(11) NULL DEFAULT NULL,
  `TX_LOCAL_ESTAGIO` VARCHAR(254) NULL DEFAULT NULL,
  `DT_INICIO` DATE NULL DEFAULT NULL,
  `DT_FINAL` DATE NULL DEFAULT NULL,
  INDEX `fk_ESTAGIARIO_SELECAO_SELECAO_ESTAGIO1_idx` (`ID_SELECAO_ESTAGIO` ASC),
  PRIMARY KEY (`ID_SELECAO_ESTAGIO`),
  CONSTRAINT `fk_ESTAGIARIO_SELECAO_SELECAO_ESTAGIO1`
    FOREIGN KEY (`ID_SELECAO_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`SELECAO_ESTAGIO` (`ID_SELECAO_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`PESSOA` (
  `ID_PESSOA` INT(11) NOT NULL AUTO_INCREMENT,
  `TX_NOME` VARCHAR(80) NOT NULL,
  `CS_TIPO_PESSOA` INT(11) NOT NULL,
  PRIMARY KEY (`ID_PESSOA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`PESSOA_FISICA` (
  `ID_PESSOA` INT(11) NOT NULL,
  `DT_NASCIMENTO` DATE NOT NULL,
  `NB_CPF` VARCHAR(11) NOT NULL,
  `NB_RG` VARCHAR(20) NULL DEFAULT NULL,
  `CS_SEXO` INT(11) NULL DEFAULT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `DT_CADASTRO` DATE NOT NULL,
  INDEX `fk_PESSOA_FISICA_PESSOA1_idx` (`ID_PESSOA` ASC),
  PRIMARY KEY (`ID_PESSOA`),
  CONSTRAINT `fk_PESSOA_FISICA_PESSOA1`
    FOREIGN KEY (`ID_PESSOA`)
    REFERENCES `SEMAD_ESTAGIO`.`PESSOA` (`ID_PESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`ESTAGIARIO2` (
  `ID_PESSOA_ESTAGIARIO` INT(11) NOT NULL,
  `ID_PESSOA_FUNCIONARIO` INT(11) NULL DEFAULT NULL,
  `NB_FUNCIONARIO` INT(11) NULL DEFAULT NULL,
  `TX_CEP` VARCHAR(10) NULL DEFAULT NULL,
  `TX_ENDERECO` VARCHAR(254) NULL DEFAULT NULL,
  `NB_NUMERO` INT(11) NULL DEFAULT NULL,
  `TX_COMPLEMENTO` VARCHAR(254) NULL DEFAULT NULL,
  `TX_BAIRRO` VARCHAR(100) NULL DEFAULT NULL,
  `TX_CONTATO` VARCHAR(200) NULL DEFAULT NULL,
  `TX_EMAIL` VARCHAR(100) NULL DEFAULT NULL,
  `TX_AGENCIA_BANCO` VARCHAR(20) NULL DEFAULT NULL,
  `TX_CONTA_CORRENTE` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`PESSOA_ESTAGIARIO` (
  `NB_ESTAGIARIO` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_PESSOA_ESTAGIARIO` INT(11) NOT NULL,
  `ID_PESSOA_FUNCIONARIO` INT(11) NULL DEFAULT NULL,
  `NB_FUNCIONARIO` INT(11) NULL DEFAULT NULL,
  `TX_CEP` VARCHAR(10) NULL DEFAULT NULL,
  `TX_ENDERECO` VARCHAR(254) NULL DEFAULT NULL,
  `NB_NUMERO` INT(11) NULL DEFAULT NULL,
  `TX_COMPLEMENTO` VARCHAR(254) NULL DEFAULT NULL,
  `TX_BAIRRO` VARCHAR(100) NULL DEFAULT NULL,
  `NB_ZONA` INT(11) NULL DEFAULT NULL,
  `TX_CONTATO` VARCHAR(200) NULL DEFAULT NULL,
  `TX_EMAIL` VARCHAR(100) NULL DEFAULT NULL,
  `TX_AGENCIA_BANCO` VARCHAR(20) NULL DEFAULT NULL,
  `TX_CONTA_CORRENTE` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`NB_ESTAGIARIO`, `ID_PESSOA_ESTAGIARIO`),
  INDEX `fk_ESTAGIARIO_PESSOA1_idx` (`ID_PESSOA_ESTAGIARIO` ASC),
  CONSTRAINT `fk_ESTAGIARIO_PESSOA1`
    FOREIGN KEY (`ID_PESSOA_ESTAGIARIO`)
    REFERENCES `SEMAD_ESTAGIO`.`PESSOA` (`ID_PESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`VAGAS_CURSO_ESTAGIO` (
  `NB_VAGAS_ESTAGIO` INT(11) NOT NULL,
  `ID_CURSO_ESTAGIO` INT(11) NOT NULL,
  `NB_QUANTIDADE` INT(11) NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  INDEX `fk_VAGAS_CURSO_ESTAGIO_VAGAS_ESTAGIO1_idx` (`NB_VAGAS_ESTAGIO` ASC),
  INDEX `fk_VAGAS_CURSO_ESTAGIO_CURSO_ESTAGIO1_idx` (`ID_CURSO_ESTAGIO` ASC),
  PRIMARY KEY (`NB_VAGAS_ESTAGIO`, `ID_CURSO_ESTAGIO`),
  CONSTRAINT `fk_VAGAS_CURSO_ESTAGIO_VAGAS_ESTAGIO1`
    FOREIGN KEY (`NB_VAGAS_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`VAGAS_ESTAGIO` (`NB_VAGAS_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VAGAS_CURSO_ESTAGIO_CURSO_ESTAGIO1`
    FOREIGN KEY (`ID_CURSO_ESTAGIO`)
    REFERENCES `SEMAD_ESTAGIO`.`CURSO_ESTAGIO` (`ID_CURSO_ESTAGIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `SEMAD_ESTAGIO`.`FUNCIONARIO_PE` (
  `ID_PESSOA_FUNCIONARIO` INT(11) NOT NULL,
  `NB_FUNCIONARIO` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_UNIDADE_GESTORA` INT(11) NULL DEFAULT NULL,
  `DT_CADASTRO` DATE NOT NULL,
  `DT_ATUALIZACAO` DATE NOT NULL,
  `TX_NOME_GUERRA` VARCHAR(80) NOT NULL,
  `BL_FOTO` BLOB NULL DEFAULT NULL,
  `CS_TIPO_FUNCIONARIO_PE` INT(11) NOT NULL,
  `CS_SITUACAO_FUNCIONARIO` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`NB_FUNCIONARIO`, `ID_PESSOA_FUNCIONARIO`),
  INDEX `fk_FUNCIONARIO_PE_PESSOA_FISICA1_idx` (`ID_PESSOA_FUNCIONARIO` ASC),
  CONSTRAINT `fk_FUNCIONARIO_PE_PESSOA_FISICA1`
    FOREIGN KEY (`ID_PESSOA_FUNCIONARIO`)
    REFERENCES `SEMAD_ESTAGIO`.`PESSOA_FISICA` (`ID_PESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
