--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Março-21-2014   
--------------------------------------------------------
DROP TABLE "SEMAD"."TIPO_UC" cascade constraints;
--------------------------------------------------------
--  DDL for Table TIPO_UC
--------------------------------------------------------

  CREATE TABLE "SEMAD"."TIPO_UC" 
   (	"CS_TIPO_UC" NUMBER(*,0), 
	"TX_TIPO_UC" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "CONTAS_PUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."TIPO_UC" TO "NEILA_SEMAD";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_PARAMET";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_CONTRAT";
 
  GRANT SELECT ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_CONS";
REM INSERTING into SEMAD.TIPO_UC
SET DEFINE OFF;
Insert into SEMAD.TIPO_UC (CS_TIPO_UC,TX_TIPO_UC) values ('2','ÁGUA');
Insert into SEMAD.TIPO_UC (CS_TIPO_UC,TX_TIPO_UC) values ('3','ENERGIA');
Insert into SEMAD.TIPO_UC (CS_TIPO_UC,TX_TIPO_UC) values ('1','TELEFONE');
Insert into SEMAD.TIPO_UC (CS_TIPO_UC,TX_TIPO_UC) values ('4','DADOS');
Insert into SEMAD.TIPO_UC (CS_TIPO_UC,TX_TIPO_UC) values ('5','CELULAR');
Insert into SEMAD.TIPO_UC (CS_TIPO_UC,TX_TIPO_UC) values ('10','ESTÁGIO REMUNERADO');
--------------------------------------------------------
--  DDL for Index IDX_PK_TIPO_UC
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMAD"."IDX_PK_TIPO_UC" ON "SEMAD"."TIPO_UC" ("CS_TIPO_UC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
--------------------------------------------------------
--  Constraints for Table TIPO_UC
--------------------------------------------------------

  ALTER TABLE "SEMAD"."TIPO_UC" ADD CONSTRAINT "IDX_PK_TIPO_UC" PRIMARY KEY ("CS_TIPO_UC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA"  ENABLE;
 
  ALTER TABLE "SEMAD"."TIPO_UC" MODIFY ("CS_TIPO_UC" NOT NULL ENABLE);
 
  ALTER TABLE "SEMAD"."TIPO_UC" MODIFY ("TX_TIPO_UC" NOT NULL ENABLE);
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "CONTAS_PUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."TIPO_UC" TO "NEILA_SEMAD";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_PARAMET";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_CONTRAT";
 
  GRANT SELECT ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_CONS";
GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "CONTAS_PUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."TIPO_UC" TO "NEILA_SEMAD";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_PARAMET";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_CONTRAT";
 
  GRANT SELECT ON "SEMAD"."TIPO_UC" TO "GESTAOCONTASPUBLICAS_CONS";
