--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Março-21-2014   
--------------------------------------------------------
DROP VIEW "SEMAD"."V_ESTAGIARIO";
--------------------------------------------------------
--  DDL for Table ESTAGIARIO
--------------------------------------------------------

  CREATE TABLE "SEMAD"."ESTAGIARIO" 
   (	"ID_PESSOA_ESTAGIARIO" NUMBER(*,0), 
	"ID_PESSOA_FUNCIONARIO" NUMBER(*,0), 
	"NB_FUNCIONARIO" NUMBER(*,0), 
	"TX_CEP" VARCHAR2(20 BYTE), 
	"TX_ENDERECO" VARCHAR2(255 BYTE), 
	"NB_NUMERO" NUMBER, 
	"TX_COMPLEMENTO" VARCHAR2(255 BYTE), 
	"TX_BAIRRO" VARCHAR2(100 BYTE), 
	"TX_AGENCIA" VARCHAR2(20 BYTE), 
	"TX_CONTA_CORRENTE" VARCHAR2(20 BYTE), 
	"TX_CONTATO" VARCHAR2(180 BYTE), 
	"TX_EMAIL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" ;
 

   COMMENT ON COLUMN "SEMAD"."ESTAGIARIO"."ID_PESSOA_ESTAGIARIO" IS 'É o identificador único das pessoa físicas.';
 
   COMMENT ON COLUMN "SEMAD"."ESTAGIARIO"."ID_PESSOA_FUNCIONARIO" IS 'É o identificador único das pessoa físicas.';
--------------------------------------------------------
--  DDL for Table PESSOA
--------------------------------------------------------

  CREATE TABLE "SEMAD"."PESSOA" 
   (	"ID_PESSOA" NUMBER, 
	"TX_NOME" VARCHAR2(80 BYTE), 
	"CS_TIPO_PESSOA" NUMBER, 
	"CS_BLOQUEIO_VOYAGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PMM_DATA" 
  PARALLEL ;
  GRANT SELECT ON "SEMAD"."PESSOA" TO "BANCOPRECO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "BP_FINALIZADORES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PONTOELETRONICO_ADMIN";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "XPTO_CONNECT";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "ADMINISTRADORES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "LICITAC?O";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "FORNECEDORES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "ESTOQUE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PARAMETRIZAC?O";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "Q_BANCO_PRECOS";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "ORGANIZACIONAL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "BP_CADASTRO";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PROT_SEMSA";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PROT_LICITACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "BP_CONSULTA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "APLICAR_PESSOAS";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PROT_CONSULTORES";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PROT_TRAMITE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "CONTAS_PUBLICAS";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "BP_MATERIAL";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "WORKFLOW";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PROT_CONS_EXT";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "EXECUCAO_ORCAMENTARIA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PATRIMONIO";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "COLETORDEPONTO";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PROT_TRAM_SEMSA";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "FORNEC_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PROT_IMPLURB";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PROT_CONS_IMPL";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PROT_TRAM_IMPL";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "WOKF_EXTERNO";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "ESTOQUE_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PROT_CML";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "LICITACAO_CONS";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PRE_CADASTRO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PONTO_SEMEF";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PONTO_CONS_SEMEF";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "ESTOQUE_KITS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "REGISTROPRECOS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PONTO_SEMAD";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "USUARIO_ADMIN";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PONTO_CONSULTA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PONTOELETRONICOV2";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PONTO_SEMASC";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "ESTOQUE_ADMIN";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "GESTAOCONTASPUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PONTO_SEMASDH";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "GESTAOESCOLAR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "EST_OPERADOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "EST_ATENDENTE";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "EST_AUTORIZACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "EST_GESTOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "GE_OPERADOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PONTO_SEMINF";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PONTO_MANAUSTRANS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "R_BANCOPRECOS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PONTO_SEMMAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "GE_GESTOR";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "SEMAD_LNK";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "ZOPEPROD";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "ROSANA";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "TACIANA";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "IWAMOTO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "FABIOLA_FACANHA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PONTO_FDT";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PARAMETRIZACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "VOYAGE_SOLICITANTE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "VOYAGE_GESTOR";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "WILMA_SILVA";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "EST_RM";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "PONTOELETRONICOV2_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "VOYAGE_GESTOR_PASSAGEM";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "NEILA_SEMAD";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "JURIDICO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "LILIANE_FIGUEIREDO";
 
  GRANT ALTER, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "JURIDICO_CONSULTA";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "JURIDICO_OPERACIONAL";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "JURIDICO_GESTORAUXILIAR";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "JURIDICO_GESTOR";
 
  GRANT ALTER, SELECT, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "JURIDICO_OPERACIONALTCE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "EST_ALMOXPEQUENOS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PONTO_SMTU";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "ORGANIZACIONAL_ADM";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PATRIMONIO_IMOVEL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PATRIMONIO_IMOVEL_REL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PATRIMONIO_MOVEL_CAD";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PATRIMONIO_MOVEL_REL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "GESTAOCONTASPUBLICAS_TEL";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "GESTAOCONTASPUBLICAS_AGUA";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "GESTAOCONTASPUBLICAS_ENERGIA";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "GESTAOCONTASPUBLICAS_CONTRAT";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "GENILSON_ALVES";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "GESTAOESCOLAR_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "PATRIMONIO_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "VOYAGE_CONS";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "GESTAOCONTASPUBLICAS_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "IRP";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "TESTES";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA" TO "PONTOELETRONICOV2_FISCALIZAC";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "PONTOELETRONICOV2_RH";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "GESTAOESPM";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "EST_CONTABIL";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "IRP_GESTOR_RP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "IRP_GESTOR_BP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "IRP_GESTOR_CATALOGACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA" TO "IRP_SOLICITANTE";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "EST_INVENTARIO";
 
  GRANT SELECT ON "SEMAD"."PESSOA" TO "HABITACAO";
-- Não é possível renderizar a DLL TABLE para o objeto SEMAD.PESSOA_FISICA com o DBMS_METADATA tentando um gerador interno.
ALTER TABLE SEMAD.PESSOA_FISICA
ADD CONSTRAINT IDX_FK1_PESSOA_FISICA FOREIGN KEY
(
  ID_LOCALIDADE_NATAL 
)
REFERENCES SEMAD.LOCALIDADE
(
  ID_LOCALIDADE 
)
ENABLE
ALTER TABLE SEMAD.PESSOA_FISICA
ADD CONSTRAINT IDX_FK2_PESSOA_FISICA FOREIGN KEY
(
  ID_UF_REG_NASCIMENTO 
)
REFERENCES SEMAD.UF
(
  ID_UF 
)
DISABLE
ALTER TABLE SEMAD.PESSOA_FISICA
ADD CONSTRAINT IDX_FK3_PESSOA_FISICA FOREIGN KEY
(
  ID_UF_RG 
)
REFERENCES SEMAD.UF
(
  ID_UF 
)
ENABLECREATE TABLE SEMAD.PESSOA_FISICA 
(
  ID_PESSOA NUMBER NOT NULL 
, NB_CPF VARCHAR2(80 BYTE) DEFAULT 00000000000000 
, NB_RG VARCHAR2(80 BYTE) 
, CS_SEXO NUMBER 
, DT_ATUALIZACAO DATE 
, CS_TIPO NUMBER 
, TX_ORGAO_EMISSOR VARCHAR2(80 BYTE) 
, ID_UF_RG VARCHAR2(80 BYTE) 
, DT_NASCIMENTO DATE 
, NB_REG_NASCIMENTO VARCHAR2(80 BYTE) 
, TX_CARTORIO_REG_NASC VARCHAR2(80 BYTE) 
, TX_LIVRO_CARTORIO VARCHAR2(20 BYTE) 
, TX_FOLHA_LIV_CART VARCHAR2(20 BYTE) 
, ID_UF_REG_NASCIMENTO VARCHAR2(80 BYTE) 
, ID_LOCALIDADE_NATAL NUMBER 
, NB_COD_CERT_MILITAR VARCHAR2(80 BYTE) 
, NB_CERT_MILITAR VARCHAR2(80 BYTE) 
, NB_PISPASEP VARCHAR2(80 BYTE) 
, NB_TITULO_ELEITOR VARCHAR2(80 BYTE) 
, NB_ZONA_TITULO VARCHAR2(80 BYTE) 
, NB_SECAO_TITULO VARCHAR2(80 BYTE) 
, LR_FOTO LONG RAW 
, ID_LOCALIDADE_CARTORIO NUMBER 
, DT_EMISSAO_CERTIDAO DATE 
, CS_TIPO_CERTIDAO NUMBER 
, DT_EMISSAO DATE 
, CS_ETNIA NUMBER 
, ID_MAE NUMBER 
, ID_PAI NUMBER 
, NB_CODIGO_INEP NUMBER 
, NB_CODIGO_CENTRAL NUMBER 
, LR_FOTO_PNG BLOB 
, CONSTRAINT IDX_PK_PESSOA_FISICA PRIMARY KEY 
  (
    ID_PESSOA 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "PMM_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
) 
PARALLEL 
LOB (LR_FOTO_PNG) STORE AS SYS_LOB0000097424C00032$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  NOLOGGING  
)CREATE INDEX SEMAD.IDX_FK2_PESSOA_FISICA ON SEMAD.PESSOA_FISICA (ID_UF_REG_NASCIMENTO) 
LOGGING 
TABLESPACE "PMM_INDEX" 
PCTFREE 30 
INITRANS 10 
STORAGE 
( 
  INITIAL 131072 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "BANCOPRECO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "BP_FINALIZADORES";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "ADMINISTRADORES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "LICITAC?O";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "FORNECEDORES";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "ZOPE_ROLE";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_SEMSA";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_LICITACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "BP_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "APLICAR_PESSOAS";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_CONSULTORES";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_TRAMITE";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_CONS_EXT";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "COLETORDEPONTO";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_TRAM_SEMSA";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "FORNEC_CONSULTA";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PONTO_ELETRONICO";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_IMPLURB";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_CONS_IMPL";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_TRAM_IMPL";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PROT_CML";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "LICITACAO_CONS";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PONTO_SEMEF";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "USUARIO_ADMIN";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "PONTOELETRONICOV2";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PONTO_SEMASC";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "GESTAOCONTASPUBLICAS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "GESTAOESCOLAR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "GE_OPERADOR";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "R_BANCOPRECOS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "GE_GESTOR";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "SEMAD_LNK";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "ZOPEPROD";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PEDRO";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA_FISICA" TO "ANTONIO_SOUSA";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "PONTO2";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "VOYAGE_SOLICITANTE";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "VOYAGE_GESTOR";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA_FISICA" TO "VANESSA_MACIEL";
 
  GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA_FISICA" TO "IONNE_PEREIRA";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA_FISICA" TO "PONTOELETRONICOV2_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "PONTO_SMTU";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "GESTAOESCOLAR_CONSULTA";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "VOYAGE_CONS";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "GESTAOCONTASPUBLICAS_CONS";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "IRP";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "TESTES";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON "SEMAD"."PESSOA_FISICA" TO "PONTOELETRONICOV2_FISCALIZAC";
 
  GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "PONTOELETRONICOV2_RH";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "GESTAOESPM";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "IRP_GESTOR_RP";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "IRP_GESTOR_CATALOGACAO";
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "SEMAD"."PESSOA_FISICA" TO "IRP_SOLICITANTE";
 
  GRANT SELECT ON "SEMAD"."PESSOA_FISICA" TO "HABITACAO";
-- Não é possível renderizar a DLL VIEW para o objeto SEMAD.V_ESTAGIARIO com o DBMS_METADATA tentando um gerador interno.
CREATE VIEW SEMAD.V_ESTAGIARIO AS SELECT
  a.TX_NOME,
  a.CS_TIPO_PESSOA,
  b.CS_SEXO,
  B.DT_ATUALIZACAO,
  --b.CS_TIPO,
  b.NB_RG,
  b.NB_CPF,
  B.DT_NASCIMENTO,
  --b.LR_FOTO,
  b.TX_ORGAO_EMISSOR,
  c.ID_PESSOA_ESTAGIARIO,
  c.ID_PESSOA_FUNCIONARIO,
  c.NB_FUNCIONARIO,
  c.TX_CEP,
  c.TX_ENDERECO,
  c.NB_NUMERO,
  c.TX_COMPLEMENTO,
  c.TX_BAIRRO,
  c.TX_AGENCIA,
  c.TX_CONTA_CORRENTE,
  c.TX_CONTATO,
  c.TX_EMAIL
FROM
  PESSOA a,
  PESSOA_FISICA b,
  semad.ESTAGIARIO c
WHERE
  a.ID_PESSOA   = b.ID_PESSOA
AND B.ID_PESSOA = C.ID_PESSOA_ESTAGIARIO
REM INSERTING into SEMAD.V_ESTAGIARIO
SET DEFINE OFF;
Insert into SEMAD.V_ESTAGIARIO (TX_NOME,CS_TIPO_PESSOA,CS_SEXO,DT_ATUALIZACAO,NB_RG,NB_CPF,DT_NASCIMENTO,TX_ORGAO_EMISSOR,ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('Maria Izabel','0','2',to_date('11/09/13','DD/MM/RR'),'321478965','17534690234',null,'SSP','168293',null,null,'69000000','uyfyl',null,null,null,null,null,null,null);
Insert into SEMAD.V_ESTAGIARIO (TX_NOME,CS_TIPO_PESSOA,CS_SEXO,DT_ATUALIZACAO,NB_RG,NB_CPF,DT_NASCIMENTO,TX_ORGAO_EMISSOR,ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('CARLOS GRIMM MONIZ JUNIOR','0','1',to_date('20/02/14','DD/MM/RR'),'19809786','96138475291',to_date('12/10/88','DD/MM/RR'),'SSP','144120',null,null,'69000000','LIYFLYF',null,null,null,'123456','123456',null,null);
Insert into SEMAD.V_ESTAGIARIO (TX_NOME,CS_TIPO_PESSOA,CS_SEXO,DT_ATUALIZACAO,NB_RG,NB_CPF,DT_NASCIMENTO,TX_ORGAO_EMISSOR,ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('ANDRE TEIXEIRA DE SOUSA','0','1',to_date('19/02/14','DD/MM/RR'),'17364663','86442228215',to_date('12/08/86','DD/MM/RR'),'SSP','157067',null,null,'69095090','RUA BURITI','47',null,'CIDADE NOVA','14545','Q545',null,null);
Insert into SEMAD.V_ESTAGIARIO (TX_NOME,CS_TIPO_PESSOA,CS_SEXO,DT_ATUALIZACAO,NB_RG,NB_CPF,DT_NASCIMENTO,TX_ORGAO_EMISSOR,ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('FRANCIBEL DA SILVA NEVES','0','2',to_date('21/01/14','DD/MM/RR'),'24725790','90381920291',to_date('01/10/89','DD/MM/RR'),'SESEG','166454',null,null,'69000000','LIYVLIV',null,null,null,null,null,null,null);
Insert into SEMAD.V_ESTAGIARIO (TX_NOME,CS_TIPO_PESSOA,CS_SEXO,DT_ATUALIZACAO,NB_RG,NB_CPF,DT_NASCIMENTO,TX_ORGAO_EMISSOR,ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('FRANCIBELL','0','2',to_date('22/01/14','DD/MM/RR'),'28754578','08487449425',to_date('01/07/92','DD/MM/RR'),'SSP-AM','167788',null,null,'69078480','Travessa S 6',null,null,'Japiim',null,null,null,null);
Insert into SEMAD.V_ESTAGIARIO (TX_NOME,CS_TIPO_PESSOA,CS_SEXO,DT_ATUALIZACAO,NB_RG,NB_CPF,DT_NASCIMENTO,TX_ORGAO_EMISSOR,ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('Laura','0','2',to_date('13/09/13','DD/MM/RR'),'255586931','90381947220',null,'ssp','168314',null,null,'69000000','livlvlv',null,null,null,null,null,null,null);
Insert into SEMAD.V_ESTAGIARIO (TX_NOME,CS_TIPO_PESSOA,CS_SEXO,DT_ATUALIZACAO,NB_RG,NB_CPF,DT_NASCIMENTO,TX_ORGAO_EMISSOR,ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('SMITH EDUARDO FERREIRA JUNIOR','0','1',to_date('28/10/13','DD/MM/RR'),'1257715152','88237343808',to_date('10/03/10','DD/MM/RR'),'SSP2','166329',null,null,'69000000','LVLVLVL',null,null,null,null,null,null,null);
Insert into SEMAD.V_ESTAGIARIO (TX_NOME,CS_TIPO_PESSOA,CS_SEXO,DT_ATUALIZACAO,NB_RG,NB_CPF,DT_NASCIMENTO,TX_ORGAO_EMISSOR,ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('RODRIGO OCTÁVIO CABRAL MADURO','0','1',to_date('21/02/14','DD/MM/RR'),'12933040','63813122204',to_date('05/11/78','DD/MM/RR'),'SESEG','27130',null,null,'69010170','AVENIDA LEONARDO MALCHER','21','BL 10-A, APT 02, CONJ. ELDORADO','CENTRO','3711','00206792','9983-8492, 9336-2319','rodrigo.cabral@pmm.am.gov.br');
Insert into SEMAD.V_ESTAGIARIO (TX_NOME,CS_TIPO_PESSOA,CS_SEXO,DT_ATUALIZACAO,NB_RG,NB_CPF,DT_NASCIMENTO,TX_ORGAO_EMISSOR,ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('Antonia Viana','0','2',to_date('11/09/13','DD/MM/RR'),'2545896','90381955249',null,'SSP','168290',null,null,'69000000','vlvlvlivl',null,null,null,null,null,null,null);
Insert into SEMAD.V_ESTAGIARIO (TX_NOME,CS_TIPO_PESSOA,CS_SEXO,DT_ATUALIZACAO,NB_RG,NB_CPF,DT_NASCIMENTO,TX_ORGAO_EMISSOR,ID_PESSOA_ESTAGIARIO,ID_PESSOA_FUNCIONARIO,NB_FUNCIONARIO,TX_CEP,TX_ENDERECO,NB_NUMERO,TX_COMPLEMENTO,TX_BAIRRO,TX_AGENCIA,TX_CONTA_CORRENTE,TX_CONTATO,TX_EMAIL) values ('CLÁUDIA SOUZA CABRAL DA SILVA MADURO','0','2',to_date('20/02/14','DD/MM/RR'),null,'75010755220',to_date('06/12/81','DD/MM/RR'),null,'169166',null,null,'69010170','AVENIDA LEONARDO MALCHER','834','CASA 01','CENTRO','0320','06584993','9467-9435','KAKAUSAREL@HOTMAIL.COM');
